import os
import re
import subprocess
from collections import defaultdict

# Configuration
SCHEMA_FILE = "supabase/migrations/20260112180000_squashed_system_baseline.sql"
REPORT_FILE = "gravity_consolidation_plan.md"
MIGRATION_FILE = "supabase/migrations/20260114000005_archive_unused_tables.sql"
SEARCH_PATHS = ["src", "supabase/functions"]

def load_extermination_candidates(report_file):
    """Parses the markdown report to find tables in the Extermination Zone."""
    candidates = []
    zone_active = False
    
    if not os.path.exists(report_file):
        print(f"Report file {report_file} not found.")
        return []

    with open(report_file, 'r') as f:
        for line in f:
            if "## ☠️ Extermination Zone" in line:
                zone_active = True
                continue
            if zone_active and line.startswith("## "):
                zone_active = False
                break
            
            if zone_active and line.strip().startswith("| `"):
                # Extract table name from "| `table_name` | Domain | ..."
                match = re.search(r"\|\s+`([\w_]+)`", line)
                if match:
                    candidates.append(match.group(1))
    return candidates

def check_usage_in_codebase(table_name):
    """
    Greps the codebase for the table name.
    Returns True if found, False otherwise.
    Precise matching is tricky, so we'll look for string literals or obvious usages.
    """
    # Fallback to git grep since rg might not be installed
    command = [
        "git",
        "grep",
        "-l",
        f"{table_name}",
        "--",
        "src", "supabase/functions"
    ]
    
    try:
        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode == 0 and result.stdout.strip():
            # Found matches
            return True, result.stdout.strip().split('\n')
        return False, []
    except Exception as e:
        print(f"Error running grep: {e}")
        return True, [] # Assume used if grep fails for safety

def generate_archive_migration():
    print("Loading candidates from report...")
    candidates = load_extermination_candidates(REPORT_FILE)
    print(f"Found {len(candidates)} candidates for archiving.")

    archived_tables = []
    kept_tables = []

    migration_sql = [
        "-- Migration to archive unused tables",
        "-- Auto-generated by scripts/archive_migration_generator.py",
        "",
        "CREATE SCHEMA IF NOT EXISTS archive;",
        ""
    ]

    print("Scanning codebase for usage...")
    for table in candidates:
        is_used, files = check_usage_in_codebase(table)
        
        if is_used:
            print(f"⚠️  KEEPING `{table}` (Found in {len(files)} files)")
            kept_tables.append(table)
        else:
            # print(f"✅ ARCHIVING `{table}`")
            archived_tables.append(table)
            migration_sql.append(f"ALTER TABLE IF EXISTS public.{table} SET SCHEMA archive;")

    # Write migration file
    with open(MIGRATION_FILE, 'w') as f:
        f.write('\n'.join(migration_sql))
    
    # Generate Summary Report
    summary = f"""
# Archive Migration Summary

**Total Candidates:** {len(candidates)}
**Archived:** {len(archived_tables)}
**Kept (SafeGuard):** {len(kept_tables)}

## Kept Tables (Found in Code)
"""
    for t in kept_tables:
        summary += f"- `{t}`\n"

    print(summary)
    print(f"\nMigration generated: {MIGRATION_FILE}")

if __name__ == "__main__":
    generate_archive_migration()
