#!/usr/bin/env node
/**
 * Spanish Translation Script for The Quantum Club
 *
 * Walks every key in EN and ES JSON files. If the ES value is identical
 * to the EN value (still in English), it translates it to proper Spanish.
 * If ES already differs from EN, the existing translation is kept.
 *
 * Quality: Native Spanish, formal usted/su, professional HR/recruitment vocabulary.
 * Brand names kept: The Quantum Club, Club OS, Club AI, QUIN, Dashboard, Pipeline, KPI, CRM, API
 * Variables {{...}} and HTML tags preserved exactly.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

const BASE = join(import.meta.dirname, '..', 'src', 'i18n', 'locales');
const EN_DIR = join(BASE, 'en');
const ES_DIR = join(BASE, 'es');

const NAMESPACES = [
  'common', 'admin', 'analytics', 'auth', 'candidates',
  'compliance', 'contracts', 'jobs', 'meetings', 'messages',
  'onboarding', 'partner', 'settings'
];

// ============================================================================
// COMPREHENSIVE TRANSLATION DICTIONARY
// Keys are English strings (or substrings), values are Spanish translations.
// Organized by category for maintainability.
// ============================================================================

// --- Full phrase translations (checked first, exact match) ---
const FULL_PHRASE_MAP = new Map([
  // Common UI
  ["Save", "Guardar"],
  ["Cancel", "Cancelar"],
  ["Delete", "Eliminar"],
  ["Edit", "Editar"],
  ["Search", "Buscar"],
  ["Filter", "Filtrar"],
  ["Close", "Cerrar"],
  ["Open", "Abrir"],
  ["Add", "Agregar"],
  ["Remove", "Eliminar"],
  ["Update", "Actualizar"],
  ["Create", "Crear"],
  ["Submit", "Enviar"],
  ["Confirm", "Confirmar"],
  ["Back", "Volver"],
  ["Next", "Siguiente"],
  ["Previous", "Anterior"],
  ["Loading", "Cargando"],
  ["Loading...", "Cargando..."],
  ["Error", "Error"],
  ["Success", "Éxito"],
  ["Warning", "Advertencia"],
  ["Info", "Información"],
  ["Yes", "Sí"],
  ["No", "No"],
  ["OK", "Aceptar"],
  ["Done", "Listo"],
  ["Apply", "Aplicar"],
  ["Reset", "Restablecer"],
  ["Clear", "Borrar"],
  ["Retry", "Reintentar"],
  ["Refresh", "Actualizar"],
  ["More", "Más"],
  ["Less", "Menos"],
  ["Show", "Mostrar"],
  ["Hide", "Ocultar"],
  ["Enable", "Activar"],
  ["Disable", "Desactivar"],
  ["Enabled", "Activado"],
  ["Disabled", "Desactivado"],
  ["On", "Activado"],
  ["Off", "Desactivado"],
  ["Start", "Iniciar"],
  ["Stop", "Detener"],
  ["Pause", "Pausar"],
  ["Resume", "Reanudar"],
  ["Continue", "Continuar"],
  ["Skip", "Omitir"],
  ["Finish", "Finalizar"],
  ["Complete", "Completar"],
  ["Send", "Enviar"],
  ["Resend", "Reenviar"],
  ["Reply", "Responder"],
  ["Forward", "Reenviar"],
  ["Copy", "Copiar"],
  ["Paste", "Pegar"],
  ["Cut", "Cortar"],
  ["Select", "Seleccionar"],
  ["Deselect", "Deseleccionar"],
  ["Expand", "Expandir"],
  ["Collapse", "Contraer"],
  ["Minimize", "Minimizar"],
  ["Maximize", "Maximizar"],
  ["Pin", "Fijar"],
  ["Unpin", "Desfijar"],
  ["Lock", "Bloquear"],
  ["Unlock", "Desbloquear"],
  ["Archive", "Archivar"],
  ["Restore", "Restaurar"],
  ["Undo", "Deshacer"],
  ["Redo", "Rehacer"],
  ["Publish", "Publicar"],
  ["Unpublish", "Despublicar"],
  ["Preview", "Vista previa"],
  ["Print", "Imprimir"],
  ["Share", "Compartir"],
  ["Invite", "Invitar"],
  ["Join", "Unirse"],
  ["Leave", "Salir"],
  ["Connect", "Conectar"],
  ["Disconnect", "Desconectar"],
  ["Sync", "Sincronizar"],
  ["Import", "Importar"],
  ["Export", "Exportar"],
  ["Download", "Descargar"],
  ["Upload", "Subir"],
  ["Browse", "Explorar"],
  ["Explore", "Explorar"],
  ["View", "Ver"],
  ["Details", "Detalles"],
  ["Summary", "Resumen"],
  ["Overview", "Resumen"],
  ["History", "Historial"],
  ["Activity", "Actividad"],
  ["Log", "Registro"],
  ["Logs", "Registros"],
  ["Settings", "Configuración"],
  ["Preferences", "Preferencias"],
  ["Configuration", "Configuración"],
  ["Options", "Opciones"],
  ["Help", "Ayuda"],
  ["About", "Acerca de"],
  ["Support", "Soporte"],
  ["Documentation", "Documentación"],
  ["Guide", "Guía"],
  ["Tutorial", "Tutorial"],
  ["FAQ", "Preguntas frecuentes"],
  ["Contact", "Contacto"],
  ["Feedback", "Retroalimentación"],
  ["Report", "Reportar"],
  ["Reports", "Informes"],
  ["Notifications", "Notificaciones"],
  ["Alerts", "Alertas"],
  ["Announcement", "Anuncio"],
  ["Announcements", "Anuncios"],
  ["News", "Noticias"],
  ["Messages", "Mensajes"],
  ["Inbox", "Bandeja de entrada"],
  ["Sent", "Enviados"],
  ["Drafts", "Borradores"],
  ["Trash", "Papelera"],
  ["Spam", "Spam"],
  ["Starred", "Destacados"],
  ["Favorites", "Favoritos"],
  ["Bookmarks", "Marcadores"],
  ["Recent", "Recientes"],
  ["Popular", "Populares"],
  ["Trending", "En tendencia"],
  ["Featured", "Destacado"],
  ["Recommended", "Recomendado"],
  ["New", "Nuevo"],
  ["Old", "Antiguo"],
  ["All", "Todos"],
  ["None", "Ninguno"],
  ["Other", "Otro"],
  ["Unknown", "Desconocido"],
  ["Custom", "Personalizado"],
  ["Default", "Predeterminado"],
  ["Advanced", "Avanzado"],
  ["Basic", "Básico"],
  ["Pro", "Pro"],
  ["Premium", "Premium"],
  ["Free", "Gratuito"],
  ["Paid", "De pago"],
  ["Required", "Obligatorio"],
  ["Optional", "Opcional"],
  ["Mandatory", "Obligatorio"],
  ["Active", "Activo"],
  ["Inactive", "Inactivo"],
  ["Pending", "Pendiente"],
  ["Approved", "Aprobado"],
  ["Rejected", "Rechazado"],
  ["Completed", "Completado"],
  ["Failed", "Fallido"],
  ["Cancelled", "Cancelado"],
  ["Canceled", "Cancelado"],
  ["Expired", "Vencido"],
  ["Suspended", "Suspendido"],
  ["Blocked", "Bloqueado"],
  ["Banned", "Inhabilitado"],
  ["Verified", "Verificado"],
  ["Unverified", "No verificado"],
  ["Confirmed", "Confirmado"],
  ["Declined", "Rechazado"],
  ["Accepted", "Aceptado"],
  ["Withdrawn", "Retirado"],
  ["Draft", "Borrador"],
  ["Published", "Publicado"],
  ["Archived", "Archivado"],
  ["Deleted", "Eliminado"],
  ["Processing", "Procesando"],
  ["Processing...", "Procesando..."],
  ["Queued", "En cola"],
  ["Scheduled", "Programado"],
  ["In Progress", "En progreso"],
  ["In progress", "En progreso"],
  ["Total", "Total"],
  ["Count", "Cantidad"],
  ["Average", "Promedio"],
  ["Minimum", "Mínimo"],
  ["Maximum", "Máximo"],
  ["Min", "Mín."],
  ["Max", "Máx."],

  // Data & Fields
  ["Name", "Nombre"],
  ["Email", "Correo electrónico"],
  ["Phone", "Teléfono"],
  ["Address", "Dirección"],
  ["City", "Ciudad"],
  ["State", "Estado"],
  ["Country", "País"],
  ["Zip Code", "Código postal"],
  ["Status", "Estado"],
  ["Date", "Fecha"],
  ["Time", "Hora"],
  ["DateTime", "Fecha y hora"],
  ["Description", "Descripción"],
  ["Title", "Título"],
  ["Type", "Tipo"],
  ["Category", "Categoría"],
  ["Categories", "Categorías"],
  ["Priority", "Prioridad"],
  ["Notes", "Notas"],
  ["Comments", "Comentarios"],
  ["Tags", "Etiquetas"],
  ["Labels", "Etiquetas"],
  ["Profile", "Perfil"],
  ["Account", "Cuenta"],
  ["Password", "Contraseña"],
  ["Username", "Nombre de usuario"],
  ["Avatar", "Avatar"],
  ["Photo", "Foto"],
  ["Image", "Imagen"],
  ["Images", "Imágenes"],
  ["Video", "Video"],
  ["Videos", "Videos"],
  ["File", "Archivo"],
  ["Files", "Archivos"],
  ["Folder", "Carpeta"],
  ["Document", "Documento"],
  ["Documents", "Documentos"],
  ["Attachment", "Archivo adjunto"],
  ["Attachments", "Archivos adjuntos"],
  ["Link", "Enlace"],
  ["Links", "Enlaces"],
  ["URL", "URL"],
  ["Website", "Sitio web"],
  ["Color", "Color"],
  ["Size", "Tamaño"],
  ["Format", "Formato"],
  ["Language", "Idioma"],
  ["Languages", "Idiomas"],
  ["Currency", "Moneda"],
  ["Amount", "Monto"],
  ["Value", "Valor"],
  ["Quantity", "Cantidad"],
  ["Unit", "Unidad"],
  ["Rate", "Tarifa"],
  ["Percentage", "Porcentaje"],
  ["Ratio", "Relación"],
  ["Duration", "Duración"],
  ["Frequency", "Frecuencia"],
  ["Location", "Ubicación"],
  ["Timezone", "Zona horaria"],
  ["Version", "Versión"],
  ["Source", "Fuente"],
  ["Target", "Objetivo"],
  ["Result", "Resultado"],
  ["Results", "Resultados"],
  ["Reason", "Motivo"],
  ["Scope", "Alcance"],

  // Time
  ["Today", "Hoy"],
  ["Yesterday", "Ayer"],
  ["Tomorrow", "Mañana"],
  ["Now", "Ahora"],
  ["Never", "Nunca"],
  ["Always", "Siempre"],
  ["Daily", "Diario"],
  ["Weekly", "Semanal"],
  ["Monthly", "Mensual"],
  ["Yearly", "Anual"],
  ["Annually", "Anual"],
  ["Hourly", "Por hora"],
  ["Minute", "Minuto"],
  ["Minutes", "Minutos"],
  ["Hour", "Hora"],
  ["Hours", "Horas"],
  ["Day", "Día"],
  ["Days", "Días"],
  ["Week", "Semana"],
  ["Weeks", "Semanas"],
  ["Month", "Mes"],
  ["Months", "Meses"],
  ["Year", "Año"],
  ["Years", "Años"],
  ["ago", "hace"],
  ["left", "restante"],
  ["remaining", "restante"],
  ["This Week", "Esta semana"],
  ["This Month", "Este mes"],
  ["This Year", "Este año"],
  ["Last Week", "Semana pasada"],
  ["Last Month", "Mes pasado"],
  ["Last Year", "Año pasado"],
  ["Next Week", "Próxima semana"],
  ["Next Month", "Próximo mes"],

  // Navigation & Layout
  ["Home", "Inicio"],
  ["Dashboard", "Panel de control"],
  ["Menu", "Menú"],
  ["Sidebar", "Barra lateral"],
  ["Header", "Encabezado"],
  ["Footer", "Pie de página"],
  ["Navigation", "Navegación"],
  ["Breadcrumbs", "Ruta de navegación"],
  ["Tabs", "Pestañas"],
  ["Tab", "Pestaña"],
  ["Panel", "Panel"],
  ["Modal", "Modal"],
  ["Dialog", "Diálogo"],
  ["Popup", "Ventana emergente"],
  ["Tooltip", "Información emergente"],
  ["Dropdown", "Menú desplegable"],
  ["Table", "Tabla"],
  ["List", "Lista"],
  ["Grid", "Cuadrícula"],
  ["Card", "Tarjeta"],
  ["Cards", "Tarjetas"],
  ["Form", "Formulario"],
  ["Page", "Página"],
  ["Section", "Sección"],
  ["Row", "Fila"],
  ["Column", "Columna"],
  ["Columns", "Columnas"],
  ["Widget", "Widget"],
  ["Widgets", "Widgets"],
  ["Chart", "Gráfico"],
  ["Charts", "Gráficos"],
  ["Graph", "Gráfico"],

  // Business / HR / Recruitment
  ["Company", "Empresa"],
  ["Companies", "Empresas"],
  ["Organization", "Organización"],
  ["Department", "Departamento"],
  ["Team", "Equipo"],
  ["Teams", "Equipos"],
  ["Member", "Miembro"],
  ["Members", "Miembros"],
  ["Employee", "Empleado"],
  ["Employees", "Empleados"],
  ["Manager", "Gerente"],
  ["Director", "Director"],
  ["Executive", "Ejecutivo"],
  ["Recruiter", "Reclutador"],
  ["Recruiters", "Reclutadores"],
  ["Strategist", "Estratega"],
  ["Candidate", "Candidato"],
  ["Candidates", "Candidatos"],
  ["Applicant", "Postulante"],
  ["Applicants", "Postulantes"],
  ["Partner", "Socio"],
  ["Partners", "Socios"],
  ["Client", "Cliente"],
  ["Clients", "Clientes"],
  ["Prospect", "Prospecto"],
  ["Prospects", "Prospectos"],
  ["Lead", "Prospecto"],
  ["Leads", "Prospectos"],
  ["User", "Usuario"],
  ["Users", "Usuarios"],
  ["Admin", "Administración"],
  ["Administrator", "Administrador"],
  ["Staff", "Personal"],
  ["Role", "Rol"],
  ["Roles", "Roles"],
  ["Permission", "Permiso"],
  ["Permissions", "Permisos"],
  ["Job", "Puesto"],
  ["Jobs", "Puestos"],
  ["Position", "Puesto"],
  ["Positions", "Puestos"],
  ["Vacancy", "Vacante"],
  ["Vacancies", "Vacantes"],
  ["Opening", "Vacante"],
  ["Openings", "Vacantes"],
  ["Application", "Solicitud"],
  ["Applications", "Solicitudes"],
  ["Interview", "Entrevista"],
  ["Interviews", "Entrevistas"],
  ["Assessment", "Evaluación"],
  ["Assessments", "Evaluaciones"],
  ["Evaluation", "Evaluación"],
  ["Offer", "Oferta"],
  ["Offers", "Ofertas"],
  ["Placement", "Colocación"],
  ["Placements", "Colocaciones"],
  ["Hiring", "Contratación"],
  ["Recruitment", "Reclutamiento"],
  ["Onboarding", "Incorporación"],
  ["Offboarding", "Desvinculación"],
  ["Salary", "Salario"],
  ["Compensation", "Compensación"],
  ["Benefits", "Beneficios"],
  ["Commission", "Comisión"],
  ["Commissions", "Comisiones"],
  ["Bonus", "Bonificación"],
  ["Revenue", "Ingresos"],
  ["Income", "Ingreso"],
  ["Earnings", "Ganancias"],
  ["Profit", "Ganancia"],
  ["Cost", "Costo"],
  ["Costs", "Costos"],
  ["Budget", "Presupuesto"],
  ["Invoice", "Factura"],
  ["Invoices", "Facturas"],
  ["Payment", "Pago"],
  ["Payments", "Pagos"],
  ["Billing", "Facturación"],
  ["Contract", "Contrato"],
  ["Contracts", "Contratos"],
  ["Agreement", "Acuerdo"],
  ["Proposal", "Propuesta"],
  ["Proposals", "Propuestas"],
  ["Deal", "Negocio"],
  ["Deals", "Negocios"],
  ["Project", "Proyecto"],
  ["Projects", "Proyectos"],
  ["Task", "Tarea"],
  ["Tasks", "Tareas"],
  ["Milestone", "Hito"],
  ["Milestones", "Hitos"],
  ["Deadline", "Fecha límite"],
  ["Schedule", "Horario"],
  ["Calendar", "Calendario"],
  ["Agenda", "Agenda"],
  ["Meeting", "Reunión"],
  ["Meetings", "Reuniones"],
  ["Event", "Evento"],
  ["Events", "Eventos"],
  ["Appointment", "Cita"],
  ["Reminder", "Recordatorio"],
  ["Reminders", "Recordatorios"],
  ["Availability", "Disponibilidad"],
  ["Available", "Disponible"],
  ["Unavailable", "No disponible"],
  ["Busy", "Ocupado"],
  ["Skill", "Habilidad"],
  ["Skills", "Habilidades"],
  ["Experience", "Experiencia"],
  ["Education", "Educación"],
  ["Certification", "Certificación"],
  ["Certifications", "Certificaciones"],
  ["Portfolio", "Portafolio"],
  ["Resume", "Currículum"],
  ["CV", "CV"],
  ["Cover Letter", "Carta de presentación"],
  ["Reference", "Referencia"],
  ["References", "Referencias"],
  ["Referral", "Referido"],
  ["Referrals", "Referidos"],
  ["Performance", "Rendimiento"],
  ["Score", "Puntuación"],
  ["Rating", "Calificación"],
  ["Rank", "Posición"],
  ["Ranking", "Clasificación"],
  ["Growth", "Crecimiento"],
  ["Trend", "Tendencia"],
  ["Trends", "Tendencias"],
  ["Capacity", "Capacidad"],
  ["Workload", "Carga de trabajo"],
  ["Workflow", "Flujo de trabajo"],
  ["Workflows", "Flujos de trabajo"],
  ["Automation", "Automatización"],
  ["Template", "Plantilla"],
  ["Templates", "Plantillas"],
  ["Campaign", "Campaña"],
  ["Campaigns", "Campañas"],
  ["Outreach", "Captación"],
  ["Engagement", "Interacción"],
  ["Conversion", "Conversión"],
  ["Conversions", "Conversiones"],
  ["Retention", "Retención"],
  ["Churn", "Abandono"],
  ["Funnel", "Embudo"],
  ["Pipeline", "Pipeline"],
  ["Stage", "Etapa"],
  ["Stages", "Etapas"],
  ["Phase", "Fase"],
  ["Step", "Paso"],
  ["Steps", "Pasos"],
  ["Progress", "Progreso"],
  ["Milestone", "Hito"],
  ["Goal", "Objetivo"],
  ["Goals", "Objetivos"],
  ["Objective", "Objetivo"],
  ["Objectives", "Objetivos"],
  ["Metric", "Métrica"],
  ["Metrics", "Métricas"],
  ["Analytics", "Análisis"],
  ["Insights", "Información"],
  ["Intelligence", "Inteligencia"],
  ["Recommendation", "Recomendación"],
  ["Recommendations", "Recomendaciones"],
  ["Approval", "Aprobación"],
  ["Rejection", "Rechazo"],
  ["Notification", "Notificación"],
  ["Message", "Mensaje"],
  ["Note", "Nota"],
  ["Comment", "Comentario"],
  ["Feedback", "Retroalimentación"],
  ["Review", "Revisión"],
  ["Reviews", "Revisiones"],
  ["Audit", "Auditoría"],
  ["Compliance", "Cumplimiento"],
  ["Security", "Seguridad"],
  ["Privacy", "Privacidad"],
  ["Policy", "Política"],
  ["Policies", "Políticas"],
  ["Rule", "Regla"],
  ["Rules", "Reglas"],
  ["Condition", "Condición"],
  ["Conditions", "Condiciones"],
  ["Criteria", "Criterios"],
  ["Requirement", "Requisito"],
  ["Requirements", "Requisitos"],
  ["Feature", "Funcionalidad"],
  ["Features", "Funcionalidades"],
  ["Module", "Módulo"],
  ["Modules", "Módulos"],
  ["Plugin", "Complemento"],
  ["Extension", "Extensión"],
  ["Integration", "Integración"],
  ["Integrations", "Integraciones"],
  ["Webhook", "Webhook"],
  ["Webhooks", "Webhooks"],
  ["Token", "Token"],
  ["Tokens", "Tokens"],
  ["Key", "Clave"],
  ["Keys", "Claves"],
  ["Secret", "Secreto"],
  ["Credential", "Credencial"],
  ["Credentials", "Credenciales"],
  ["Session", "Sesión"],
  ["Sessions", "Sesiones"],
  ["Connection", "Conexión"],
  ["Connections", "Conexiones"],
  ["Network", "Red"],
  ["Actions", "Acciones"],
  ["Action", "Acción"],
  ["Trigger", "Disparador"],
  ["Triggers", "Disparadores"],
  ["Response", "Respuesta"],
  ["Request", "Solicitud"],
  ["Requests", "Solicitudes"],

  // Phrases
  ["No results found", "No se encontraron resultados"],
  ["No results", "Sin resultados"],
  ["Are you sure?", "¿Está seguro/a?"],
  ["Something went wrong", "Algo salió mal"],
  ["Please try again", "Por favor, inténtelo de nuevo"],
  ["Try again", "Intentar de nuevo"],
  ["No data available", "No hay datos disponibles"],
  ["No data", "Sin datos"],
  ["View all", "Ver todo"],
  ["View All", "Ver todo"],
  ["Save changes", "Guardar cambios"],
  ["Save Changes", "Guardar cambios"],
  ["Select all", "Seleccionar todo"],
  ["Select All", "Seleccionar todo"],
  ["Clear all", "Borrar todo"],
  ["Clear All", "Borrar todo"],
  ["Sign in", "Iniciar sesión"],
  ["Sign In", "Iniciar sesión"],
  ["Sign out", "Cerrar sesión"],
  ["Sign Out", "Cerrar sesión"],
  ["Sign up", "Registrarse"],
  ["Sign Up", "Registrarse"],
  ["Log in", "Iniciar sesión"],
  ["Log In", "Iniciar sesión"],
  ["Log out", "Cerrar sesión"],
  ["Log Out", "Cerrar sesión"],
  ["Go back", "Volver"],
  ["Go Back", "Volver"],
  ["Learn more", "Más información"],
  ["Learn More", "Más información"],
  ["Read more", "Leer más"],
  ["Read More", "Leer más"],
  ["See more", "Ver más"],
  ["See More", "Ver más"],
  ["Show more", "Mostrar más"],
  ["Show More", "Mostrar más"],
  ["Show less", "Mostrar menos"],
  ["Show Less", "Mostrar menos"],
  ["Load more", "Cargar más"],
  ["Load More", "Cargar más"],
  ["All caught up", "Todo al día"],
  ["No pending tasks", "Sin tareas pendientes"],
  ["Active Jobs", "Vacantes activas"],
  ["Top Performers", "Mejores resultados"],
  ["View Calendar", "Ver calendario"],
  ["Quick Launch", "Acceso rápido"],
  ["Coming soon", "Próximamente"],
  ["Coming Soon", "Próximamente"],
  ["Under construction", "En construcción"],
  ["Not found", "No encontrado"],
  ["Page not found", "Página no encontrada"],
  ["Access denied", "Acceso denegado"],
  ["Permission denied", "Permiso denegado"],
  ["Unauthorized", "No autorizado"],
  ["Forbidden", "Prohibido"],
  ["Not available", "No disponible"],
  ["No items", "Sin elementos"],
  ["No items found", "No se encontraron elementos"],
  ["Empty", "Vacío"],
  ["N/A", "N/D"],
  ["TBD", "Por definir"],
  ["Powered by", "Desarrollado por"],
  ["Sort by", "Ordenar por"],
  ["Sort By", "Ordenar por"],
  ["Group by", "Agrupar por"],
  ["Group By", "Agrupar por"],
  ["Filter by", "Filtrar por"],
  ["Filter By", "Filtrar por"],
  ["Search by", "Buscar por"],
  ["Order by", "Ordenar por"],
  ["Created at", "Fecha de creación"],
  ["Updated at", "Fecha de actualización"],
  ["Created by", "Creado por"],
  ["Updated by", "Actualizado por"],
  ["Last updated", "Última actualización"],
  ["Last modified", "Última modificación"],
  ["Added by", "Agregado por"],
  ["Assigned to", "Asignado a"],
  ["Managed by", "Gestionado por"],
  ["Owned by", "Propiedad de"],
  ["Shared with", "Compartido con"],
  ["Copied to clipboard", "Copiado al portapapeles"],
  ["Copy to clipboard", "Copiar al portapapeles"],
  ["Drag and drop", "Arrastrar y soltar"],
  ["Drag to reorder", "Arrastrar para reordenar"],
  ["Click to upload", "Haga clic para subir"],
  ["Drop files here", "Suelte los archivos aquí"],
  ["or", "o"],
  ["and", "y"],
  ["of", "de"],
  ["in", "en"],
  ["for", "para"],
  ["with", "con"],
  ["by", "por"],
  ["from", "de"],
  ["to", "a"],
  ["at", "en"],
  ["on", "en"],

  // Recruitment-specific
  ["Talent Pool", "Pool de talento"],
  ["Talent pool", "Pool de talento"],
  ["Shortlist", "Preselección"],
  ["Shortlisted", "Preseleccionado"],
  ["Screening", "Evaluación inicial"],
  ["Background Check", "Verificación de antecedentes"],
  ["Background check", "Verificación de antecedentes"],
  ["Reference Check", "Verificación de referencias"],
  ["Job Board", "Portal de empleo"],
  ["Job board", "Portal de empleo"],
  ["Job Description", "Descripción del puesto"],
  ["Job description", "Descripción del puesto"],
  ["Job Title", "Título del puesto"],
  ["Job title", "Título del puesto"],
  ["Hiring Manager", "Gerente de contratación"],
  ["Hiring manager", "Gerente de contratación"],
  ["Full-time", "Tiempo completo"],
  ["Full time", "Tiempo completo"],
  ["Part-time", "Medio tiempo"],
  ["Part time", "Medio tiempo"],
  ["Remote", "Remoto"],
  ["Hybrid", "Híbrido"],
  ["On-site", "Presencial"],
  ["Onsite", "Presencial"],
  ["Freelance", "Freelance"],
  ["Temporary", "Temporal"],
  ["Permanent", "Permanente"],
  ["Internship", "Pasantía"],
  ["Notice Period", "Período de preaviso"],
  ["Notice period", "Período de preaviso"],
  ["Probation", "Período de prueba"],
  ["Probation Period", "Período de prueba"],
  ["Work Experience", "Experiencia laboral"],
  ["Work experience", "Experiencia laboral"],
  ["Years of experience", "Años de experiencia"],
  ["Salary Range", "Rango salarial"],
  ["Salary range", "Rango salarial"],
  ["Expected Salary", "Salario esperado"],
  ["Current Salary", "Salario actual"],
  ["Entry Level", "Nivel inicial"],
  ["Entry level", "Nivel inicial"],
  ["Mid Level", "Nivel medio"],
  ["Mid level", "Nivel medio"],
  ["Senior Level", "Nivel senior"],
  ["Senior level", "Nivel senior"],
  ["Junior", "Junior"],
  ["Senior", "Senior"],
  ["Lead", "Líder"],
  ["Headcount", "Plantilla"],
  ["Headcount Planning", "Planificación de plantilla"],
  ["Time to Fill", "Tiempo de cobertura"],
  ["Time to fill", "Tiempo de cobertura"],
  ["Time to Hire", "Tiempo de contratación"],
  ["Time to hire", "Tiempo de contratación"],
  ["Cost per Hire", "Costo por contratación"],
  ["Cost per hire", "Costo por contratación"],
  ["Offer Letter", "Carta de oferta"],
  ["Offer letter", "Carta de oferta"],
  ["Scorecard", "Tarjeta de evaluación"],
  ["Scorecards", "Tarjetas de evaluación"],
  ["Culture Fit", "Afinidad cultural"],
  ["Culture fit", "Afinidad cultural"],
  ["Diversity", "Diversidad"],
  ["Inclusion", "Inclusión"],
  ["Equal Opportunity", "Igualdad de oportunidades"],
  ["Employer Branding", "Marca empleadora"],

  // Finance & Billing
  ["Subscription", "Suscripción"],
  ["Plan", "Plan"],
  ["Pricing", "Precios"],
  ["Checkout", "Pago"],
  ["Cart", "Carrito"],
  ["Order", "Pedido"],
  ["Orders", "Pedidos"],
  ["Receipt", "Recibo"],
  ["Refund", "Reembolso"],
  ["Discount", "Descuento"],
  ["Tax", "Impuesto"],
  ["Taxes", "Impuestos"],
  ["Fee", "Tarifa"],
  ["Fees", "Tarifas"],
  ["Balance", "Saldo"],
  ["Credit", "Crédito"],
  ["Debit", "Débito"],
  ["Transaction", "Transacción"],
  ["Transactions", "Transacciones"],
  ["Transfer", "Transferencia"],
  ["Payout", "Desembolso"],
  ["Payouts", "Desembolsos"],
  ["Overdue", "Vencido"],

  // System & Technical
  ["System", "Sistema"],
  ["Server", "Servidor"],
  ["Database", "Base de datos"],
  ["Cache", "Caché"],
  ["Queue", "Cola"],
  ["Service", "Servicio"],
  ["Services", "Servicios"],
  ["Health", "Estado"],
  ["Uptime", "Tiempo de actividad"],
  ["Downtime", "Tiempo de inactividad"],
  ["Latency", "Latencia"],
  ["Throughput", "Rendimiento"],
  ["Error Rate", "Tasa de error"],
  ["Success Rate", "Tasa de éxito"],
  ["Response Time", "Tiempo de respuesta"],
  ["Endpoint", "Endpoint"],
  ["Timeout", "Tiempo de espera"],
  ["Rate Limit", "Límite de velocidad"],
  ["Rate limit", "Límite de velocidad"],
  ["Backup", "Copia de seguridad"],
  ["Backups", "Copias de seguridad"],
  ["Migration", "Migración"],
  ["Deployment", "Despliegue"],
  ["Environment", "Entorno"],
  ["Production", "Producción"],
  ["Staging", "Preparación"],
  ["Development", "Desarrollo"],
  ["Testing", "Pruebas"],
  ["Debug", "Depuración"],
  ["Maintenance", "Mantenimiento"],
  ["Maintenance Mode", "Modo de mantenimiento"],

  // Misc
  ["Powered by AI", "Impulsado por IA"],
  ["AI-powered", "Impulsado por IA"],
  ["Generating...", "Generando..."],
  ["Generated", "Generado"],
  ["Analyzing...", "Analizando..."],
  ["Analyzed", "Analizado"],
  ["Saving...", "Guardando..."],
  ["Saved", "Guardado"],
  ["Saved!", "¡Guardado!"],
  ["Uploading...", "Subiendo..."],
  ["Uploaded", "Subido"],
  ["Downloading...", "Descargando..."],
  ["Downloaded", "Descargado"],
  ["Sending...", "Enviando..."],
  ["Connecting...", "Conectando..."],
  ["Connected", "Conectado"],
  ["Disconnected", "Desconectado"],
  ["Syncing...", "Sincronizando..."],
  ["Synced", "Sincronizado"],
  ["Verifying...", "Verificando..."],
  ["Initializing...", "Inicializando..."],
  ["Retrying...", "Reintentando..."],
  ["Updating...", "Actualizando..."],
  ["Updated", "Actualizado"],
  ["Created", "Creado"],
  ["Deleted", "Eliminado"],
  ["Copied", "Copiado"],
  ["Moved", "Movido"],
  ["Renamed", "Renombrado"],
  ["Restored", "Restaurado"],
  ["Imported", "Importado"],
  ["Exported", "Exportado"],
  ["Applied", "Aplicado"],
  ["Scheduled", "Programado"],
  ["Cancelled", "Cancelado"],
  ["Paused", "Pausado"],
  ["Resumed", "Reanudado"],
  ["Started", "Iniciado"],
  ["Stopped", "Detenido"],
  ["Finished", "Finalizado"],
  ["Ended", "Finalizado"],
  ["Joined", "Se unió"],
  ["Left", "Salió"],
  ["Online", "En línea"],
  ["Offline", "Desconectado"],
  ["Away", "Ausente"],
  ["Idle", "Inactivo"],
  ["Unknown", "Desconocido"],
  ["Urgent", "Urgente"],
  ["High", "Alta"],
  ["Medium", "Media"],
  ["Low", "Baja"],
  ["Critical", "Crítico"],
  ["Normal", "Normal"],
  ["Minor", "Menor"],
  ["Major", "Mayor"],
  ["Blocker", "Bloqueante"],
  ["Success!", "¡Éxito!"],
  ["Error!", "¡Error!"],
  ["Warning!", "¡Advertencia!"],
  ["Bulk Actions", "Acciones masivas"],
  ["Bulk actions", "Acciones masivas"],
  ["Select an option", "Seleccione una opción"],
  ["Choose an option", "Elija una opción"],
  ["No options available", "Sin opciones disponibles"],
  ["Enter a value", "Ingrese un valor"],
  ["Invalid input", "Entrada no válida"],
  ["Field is required", "Este campo es obligatorio"],
  ["This field is required", "Este campo es obligatorio"],
  ["Invalid email", "Correo electrónico no válido"],
  ["Invalid format", "Formato no válido"],
  ["Already exists", "Ya existe"],
  ["Not found", "No encontrado"],
  ["Confirm delete", "Confirmar eliminación"],
  ["Confirm Delete", "Confirmar eliminación"],
  ["Are you sure you want to delete?", "¿Está seguro/a de que desea eliminar?"],
  ["This action cannot be undone", "Esta acción no se puede deshacer"],
  ["This action cannot be undone.", "Esta acción no se puede deshacer."],
  ["Changes saved", "Cambios guardados"],
  ["Changes saved!", "¡Cambios guardados!"],
  ["Changes saved successfully", "Cambios guardados correctamente"],
  ["Changes saved successfully!", "¡Cambios guardados correctamente!"],
  ["No changes detected", "No se detectaron cambios"],
  ["Unsaved changes", "Cambios sin guardar"],
  ["You have unsaved changes", "Tiene cambios sin guardar"],
  ["Discard changes", "Descartar cambios"],
  ["Discard Changes", "Descartar cambios"],
  ["Keep editing", "Seguir editando"],
  ["Releasing soon", "Disponible próximamente"],
  ["Soon", "Próximamente"],
  ["Under Development", "En desarrollo"],
  ["Under development", "En desarrollo"],
  ["This feature is currently under development.", "Esta funcionalidad se encuentra actualmente en desarrollo."],
  ["Coming soon!", "¡Próximamente!"],
  ["Stay tuned", "Manténgase atento"],
  ["Reload Page", "Recargar página"],
  ["Reload page", "Recargar página"],
  ["Contact Support", "Contactar soporte"],
  ["Contact support", "Contactar soporte"],
  ["Try Again", "Intentar de nuevo"],
  ["Join Now", "Unirse ahora"],
  ["Join now", "Unirse ahora"],
  ["Get Started", "Comenzar"],
  ["Get started", "Comenzar"],
  ["Leave Meeting", "Salir de la reunión"],
  ["Leave meeting", "Salir de la reunión"],
  ["Toggle Sidebar", "Alternar barra lateral"],
  ["Send Message", "Enviar mensaje"],
  ["Stop Recording", "Detener grabación"],
  ["Voice Message", "Nota de voz"],
  ["Upload Image", "Subir imagen"],
  ["Mute sounds", "Silenciar sonidos"],
  ["Enable sounds", "Activar sonidos"],
  ["Open in new tab", "Abrir en nueva pestaña"],
  ["Strong Growth", "Crecimiento sólido"],
  ["New Users", "Nuevos usuarios"],
  ["All Statuses", "Todos los estados"],
  ["Last Login", "Último acceso"],
  ["Search by name, email, or location...", "Buscar por nombre, correo electrónico o ubicación..."],
  ["Search by name, email, or company...", "Buscar por nombre, correo electrónico o empresa..."],
  ["View Profile", "Ver perfil"],
  ["View profile", "Ver perfil"],
  ["Edit User", "Editar usuario"],
  ["Suspend", "Suspender"],
  ["Unsuspend", "Reactivar"],
  ["View as Candidate", "Ver como candidato"],
  ["Company Members", "Miembros de la empresa"],
  ["Loading partners...", "Cargando socios..."],
  ["No partners found", "No se encontraron socios"],
  ["No company", "Sin empresa"],
  ["Candidates exported", "Candidatos exportados"],
  ["Stop generation", "Detener generación"],

  // More admin-specific
  ["User Management", "Gestión de usuarios"],
  ["Member Management", "Gestión de miembros"],
  ["Company Management", "Gestión de empresas"],
  ["System Health", "Estado del sistema"],
  ["Bulk Operations", "Operaciones masivas"],
  ["Custom Fields", "Campos personalizados"],
  ["Workflow Builder", "Constructor de flujos de trabajo"],
  ["Approval Chains", "Cadenas de aprobación"],
  ["Notifications Config", "Configuración de notificaciones"],
  ["Report Builder", "Constructor de informes"],
  ["Avatar Traffic Control", "Control de tráfico de avatares"],
  ["Page Templates", "Plantillas de páginas"],
  ["AI Configuration", "Configuración de IA"],
  ["Blog Engine", "Motor de blog"],
  ["Email Builder", "Constructor de correos"],
  ["Security Hub", "Centro de seguridad"],
  ["MFA Enforcement", "Aplicación de MFA"],
  ["Session Management", "Gestión de sesiones"],
  ["Custom Roles", "Roles personalizados"],
  ["Status Page", "Página de estado"],
  ["IP Allowlist", "Lista de IPs permitidas"],
  ["Finance Hub", "Centro de finanzas"],
  ["Inventory Hub", "Centro de inventario"],
  ["Usage Metering", "Medición de uso"],
  ["Customer Health", "Salud del cliente"],
  ["Compliance Hub", "Centro de cumplimiento"],
  ["Consent Management", "Gestión de consentimiento"],
  ["EEO Compliance", "Cumplimiento EEO"],
  ["Enterprise Management", "Gestión empresarial"],
  ["Due Diligence Center", "Centro de due diligence"],
  ["Risk Management", "Gestión de riesgos"],
  ["Translations Hub", "Centro de traducciones"],
  ["Data Retention", "Retención de datos"],
  ["Investor Metrics", "Métricas para inversores"],
  ["Developer Portal", "Portal de desarrolladores"],
  ["Integration Marketplace", "Marketplace de integraciones"],
  ["All Projects", "Todos los proyectos"],
  ["All Proposals", "Todas las propuestas"],
  ["Disputes", "Disputas"],
  ["Social Management", "Gestión social"],
  ["Feature Control Center", "Centro de control de funcionalidades"],
  ["Employee Dashboard", "Panel del empleado"],
  ["Edge Function Command Center", "Centro de comando de funciones edge"],
  ["KPI Command Center", "Centro de comando KPI"],
  ["Agentic OS Hub", "Centro Agentic OS"],
  ["All Pages", "Todas las páginas"],
  ["My Profile", "Mi perfil"],
  ["My Skills", "Mis habilidades"],
  ["My Performance", "Mi rendimiento"],
  ["Email Settings", "Configuración de correo"],
  ["Help Center", "Centro de ayuda"],
  ["Support Tickets", "Tickets de soporte"],
  ["Submit Ticket", "Enviar ticket"],
  ["Admin Panel", "Panel de administración"],
  ["Meeting Intelligence", "Inteligencia de reuniones"],
  ["Cover Letter Builder", "Constructor de cartas de presentación"],
  ["My Analytics", "Mi análisis"],
  ["Referrals & Invites", "Referidos e invitaciones"],
  ["My Communications", "Mis comunicaciones"],
  ["Browse Projects", "Explorar proyectos"],
  ["Freelancer Setup", "Configuración de freelancer"],
  ["Gig Marketplace", "Marketplace de proyectos"],
  ["My Proposals", "Mis propuestas"],
  ["My Contracts", "Mis contratos"],
  ["Time Tracking", "Seguimiento de tiempo"],
  ["Social Feed", "Feed social"],
  ["Partner Hub", "Centro de socios"],
  ["Post Project", "Publicar proyecto"],
  ["Find Talent", "Encontrar talento"],
  ["Expert Marketplace", "Marketplace de expertos"],
  ["CRM Dashboard", "Panel CRM"],
  ["Reply Inbox", "Bandeja de respuestas"],
  ["CRM Settings", "Configuración CRM"],
  ["WhatsApp Hub", "Centro WhatsApp"],
  ["WhatsApp Booking", "Reservas por WhatsApp"],
  ["Partner Funnel", "Embudo de socios"],
  ["Partner Relationships", "Relaciones con socios"],
  ["Relationships Dashboard", "Panel de relaciones"],
  ["Talent Pool", "Pool de talento"],
  ["Talent Lists", "Listas de talento"],
  ["All Candidates", "Todos los candidatos"],
  ["All Jobs", "Todos los puestos"],
  ["Job Approvals", "Aprobaciones de puestos"],
  ["Job Board Distribution", "Distribución en portales de empleo"],
  ["All Companies", "Todas las empresas"],
  ["Target Companies", "Empresas objetivo"],
  ["Interview Kits", "Kits de entrevista"],
  ["Background Checks", "Verificación de antecedentes"],
  ["Employee Onboarding", "Incorporación de empleados"],
  ["Pipeline Stages", "Etapas del pipeline"],
  ["Offer Management", "Gestión de ofertas"],
  ["Job Templates", "Plantillas de puestos"],
  ["Candidate Scheduling", "Programación de candidatos"],
  ["Scorecard Library", "Biblioteca de tarjetas de evaluación"],
  ["Assessments Hub", "Centro de evaluaciones"],
  ["Global Analytics", "Análisis global"],
  ["Performance Hub", "Centro de rendimiento"],
  ["Communication Hub", "Centro de comunicaciones"],
  ["Meeting Analytics", "Análisis de reuniones"],
  ["AI Analytics Hub", "Centro de análisis de IA"],
  ["Time to Fill", "Tiempo de cobertura"],
  ["Recruiter Productivity", "Productividad del reclutador"],
  ["Source ROI", "ROI de fuentes"],
  ["Email Analytics", "Análisis de correo electrónico"],
  ["Headcount Planning", "Planificación de plantilla"],

  // Navigation groups
  ["Communication", "Comunicación"],
  ["Learning", "Aprendizaje"],
  ["AI & Tools", "IA y herramientas"],
  ["OS Notes", "Notas de OS"],
  ["Career", "Carrera"],
  ["Club Projects", "Proyectos del Club"],
  ["Social", "Social"],
  ["CRM & Outreach", "CRM y captación"],
  ["Partnerships", "Asociaciones"],
  ["Talent Management", "Gestión de talento"],
  ["Assessments & Games", "Evaluaciones y juegos"],
  ["Analytics & Intelligence", "Análisis e inteligencia"],
  ["Operations", "Operaciones"],
  ["Security & Monitoring", "Seguridad y monitoreo"],
  ["Finance", "Finanzas"],
  ["Governance", "Gobernanza"],
  ["Developer", "Desarrollador"],

  // Partner funnel specific
  ["Tell us about the Role", "Cuéntenos sobre el puesto"],
  ["The more context you share, the better your shortlist.", "Cuanta más información comparta, mejor será su lista de preselección."],
  ["What role are you looking to fill?", "¿Qué puesto desea cubrir?"],
  ["e.g. VP of Engineering, CFO, Head of Product", "Ej., VP de Ingeniería, CFO, Director de Producto"],
  ["What's driving this hire?", "¿Qué motiva esta contratación?"],
  ["Growth — scaling the team", "Crecimiento: ampliación del equipo"],
  ["Replacement — someone left", "Reemplazo: alguien se fue"],
  ["New function — building from scratch", "Nueva función: construir desde cero"],
  ["Confidential — discreet search", "Confidencial: búsqueda discreta"],
  ["Seniority level", "Nivel de antigüedad"],
  ["Seniority", "Antigüedad"],
  ["Director / VP", "Director / VP"],
  ["C-Suite", "C-Suite"],
  ["Head of / Senior Lead", "Director de área / Líder senior"],
  ["Specialist IC", "Especialista individual"],
  ["Anything else we should know?", "¿Hay algo más que debamos saber?"],
  ["Team size, reporting line, challenges with previous hires, specific skills…", "Tamaño del equipo, línea de reporte, desafíos con contrataciones anteriores, habilidades específicas..."],
  ["Where are you based?", "¿Dónde se encuentra ubicado?"],
  ["Please enter the role you're looking to fill", "Ingrese el puesto que desea cubrir"],
  ["Driving this hire", "Motivo de contratación"],
  ["Additional context", "Contexto adicional"],

  // More common UI phrases
  ["Rows per page", "Filas por página"],
  ["items per page", "elementos por página"],
  ["Showing", "Mostrando"],
  ["of", "de"],
  ["entries", "entradas"],
  ["items", "elementos"],
  ["selected", "seleccionados"],
  ["No records found", "No se encontraron registros"],
  ["No matching records", "No hay registros coincidentes"],
  ["First", "Primero"],
  ["Last", "Último"],
  ["Newest", "Más reciente"],
  ["Oldest", "Más antiguo"],
  ["Alphabetical", "Alfabético"],
  ["Relevance", "Relevancia"],
  ["Ascending", "Ascendente"],
  ["Descending", "Descendente"],
  ["asc", "asc"],
  ["desc", "desc"],
  ["true", "verdadero"],
  ["false", "falso"],
  ["Manage", "Administrar"],
  ["Configure", "Configurar"],
  ["Customize", "Personalizar"],
  ["Personalize", "Personalizar"],
  ["Optimize", "Optimizar"],
  ["Analyze", "Analizar"],
  ["Generate", "Generar"],
  ["Calculate", "Calcular"],
  ["Assign", "Asignar"],
  ["Unassign", "Desasignar"],
  ["Approve", "Aprobar"],
  ["Reject", "Rechazar"],
  ["Deny", "Denegar"],
  ["Grant", "Otorgar"],
  ["Revoke", "Revocar"],
  ["Escalate", "Escalar"],
  ["Resolve", "Resolver"],
  ["Dismiss", "Descartar"],
  ["Acknowledge", "Reconocer"],
  ["Ignore", "Ignorar"],
  ["Mute", "Silenciar"],
  ["Unmute", "Activar sonido"],
  ["Block", "Bloquear"],
  ["Unblock", "Desbloquear"],
  ["Follow", "Seguir"],
  ["Unfollow", "Dejar de seguir"],
  ["Like", "Me gusta"],
  ["Unlike", "Ya no me gusta"],
  ["React", "Reaccionar"],
  ["Bookmark", "Guardar"],
  ["Unbookmark", "Quitar de guardados"],
  ["Mention", "Mención"],
  ["Mentions", "Menciones"],
  ["Tag", "Etiquetar"],
  ["Untag", "Desetiquetar"],
  ["Flag", "Marcar"],
  ["Unflag", "Desmarcar"],
  ["Mark", "Marcar"],
  ["Unmark", "Desmarcar"],
  ["Mark as read", "Marcar como leído"],
  ["Mark as unread", "Marcar como no leído"],
  ["Duplicate", "Duplicar"],
  ["Clone", "Clonar"],
  ["Merge", "Combinar"],
  ["Split", "Dividir"],
  ["Move", "Mover"],
  ["Rename", "Renombrar"],
  ["Replace", "Reemplazar"],
  ["Swap", "Intercambiar"],
  ["Toggle", "Alternar"],
  ["Switch", "Cambiar"],
  ["Activate", "Activar"],
  ["Deactivate", "Desactivar"],
  ["Install", "Instalar"],
  ["Uninstall", "Desinstalar"],
  ["Upgrade", "Actualizar"],
  ["Downgrade", "Degradar"],
  ["Renew", "Renovar"],
  ["Terminate", "Terminar"],
  ["Extend", "Extender"],
  ["Shorten", "Acortar"],
  ["Increase", "Aumentar"],
  ["Decrease", "Disminuir"],
  ["Expand all", "Expandir todo"],
  ["Collapse all", "Contraer todo"],
  ["Expand All", "Expandir todo"],
  ["Collapse All", "Contraer todo"],
  ["Welcome back", "Bienvenido de nuevo"],
  ["Welcome Back", "Bienvenido de nuevo"],
  ["Good morning", "Buenos días"],
  ["Good afternoon", "Buenas tardes"],
  ["Good evening", "Buenas noches"],

  // ---- Error messages (full sentences) ----
  ["An error occurred while rendering this component", "Se produjo un error al renderizar este componente"],
  ["Payment Processing Error", "Error de procesamiento de pago"],
  ["There was an issue processing your payment. You have NOT been charged.", "Hubo un problema al procesar su pago. NO se le ha cobrado."],
  ["Please verify your payment details and try again. If the problem persists, contact your bank.", "Verifique los datos de su pago e intente de nuevo. Si el problema persiste, contacte a su banco."],
  ["Invalid Payment Information", "Información de pago no válida"],
  ["Some payment details are missing or incorrect.", "Faltan algunos datos de pago o son incorrectos."],
  ["Please check your card number, expiration date, and CVV.", "Verifique su número de tarjeta, fecha de vencimiento y CVV."],
  ["Connection Error", "Error de conexión"],
  ["We couldn't connect to the payment service. You have NOT been charged.", "No pudimos conectar con el servicio de pago. NO se le ha cobrado."],
  ["Check your internet connection and try again.", "Verifique su conexión a internet e intente de nuevo."],
  ["Payment Error", "Error de pago"],
  ["An unexpected error occurred during payment.", "Se produjo un error inesperado durante el pago."],
  ["If you're unsure whether you were charged, please contact support before retrying.", "Si no está seguro/a de si se le cobró, contacte a soporte antes de reintentar."],
  ["What to do:", "Qué hacer:"],
  ["Suggestion:", "Sugerencia:"],
  ["Technical Details", "Detalles técnicos"],
  ["Reference:", "Referencia:"],
  ["File:", "Archivo:"],
  ["File Too Large", "Archivo demasiado grande"],
  ["The file you're trying to upload exceeds the size limit.", "El archivo que intenta subir supera el límite de tamaño."],
  ["Please compress the file or choose a smaller one. Maximum size is typically 10MB.", "Comprima el archivo o elija uno más pequeño. El tamaño máximo es generalmente 10 MB."],
  ["Unsupported File Type", "Tipo de archivo no compatible"],
  ["This file format is not supported.", "Este formato de archivo no es compatible."],
  ["Please upload a file in a supported format (PDF, DOCX, PNG, JPG, etc.).", "Suba un archivo en un formato compatible (PDF, DOCX, PNG, JPG, etc.)."],
  ["Upload Interrupted", "Carga interrumpida"],
  ["The upload was interrupted due to a network issue.", "La carga se interrumpió debido a un problema de red."],
  ["Check your internet connection and try again. The file will not be partially uploaded.", "Verifique su conexión a internet e intente de nuevo. El archivo no se subirá parcialmente."],
  ["Storage Error", "Error de almacenamiento"],
  ["There was a problem with the file storage service.", "Hubo un problema con el servicio de almacenamiento de archivos."],
  ["Please try again later. If the problem persists, contact support.", "Intente de nuevo más tarde. Si el problema persiste, contacte a soporte."],
  ["Upload Failed", "Error al subir archivo"],
  ["An unexpected error occurred during upload.", "Se produjo un error inesperado durante la carga."],
  ["Please try uploading the file again.", "Intente subir el archivo de nuevo."],
  ["Camera/Microphone Access Required", "Se requiere acceso a cámara/micrófono"],
  ["Please allow access to your camera and microphone to join the meeting.", "Permita el acceso a su cámara y micrófono para unirse a la reunión."],
  ["Click the camera icon in your browser's address bar to update permissions.", "Haga clic en el icono de la cámara en la barra de direcciones de su navegador para actualizar los permisos."],
  ["Media Device Error", "Error de dispositivo multimedia"],
  ["There was a problem with your camera or microphone.", "Hubo un problema con su cámara o micrófono."],
  ["Try closing other apps using your camera, or try a different device.", "Intente cerrar otras aplicaciones que usen su cámara, o pruebe con un dispositivo diferente."],
  ["Connection Lost", "Conexión perdida"],
  ["The connection to the meeting was interrupted.", "La conexión con la reunión se interrumpió."],
  ["Check your internet connection and try rejoining.", "Verifique su conexión a internet e intente unirse de nuevo."],
  ["Meeting Error", "Error de reunión"],
  ["An unexpected error occurred in the meeting.", "Se produjo un error inesperado en la reunión."],
  ["Try refreshing the page or rejoining the meeting.", "Intente actualizar la página o unirse de nuevo a la reunión."],
  ["Connection Restored", "Conexión restablecida"],
  ["Reconnecting...", "Reconectando..."],
  ["Everything is working again.", "Todo funciona de nuevo."],
  ["We had trouble connecting. Please check your internet connection.", "Tuvimos problemas para conectar. Verifique su conexión a internet."],
  ["Will automatically retry when you're back online.", "Se reintentará automáticamente cuando vuelva a estar en línea."],
  ["You're offline. Some features may not work.", "Está sin conexión. Algunas funciones pueden no estar disponibles."],
  ["Back online!", "¡De vuelta en línea!"],
  ["More pages", "Más páginas"],

  // ---- Empty states ----
  ["Try adjusting your search or filters", "Intente ajustar su búsqueda o filtros"],
  ["Try using different keywords", "Intente usar palabras clave diferentes"],
  ["Check your spelling", "Verifique la ortografía"],
  ["Remove some filters to see more results", "Elimine algunos filtros para ver más resultados"],
  ["Nothing here yet", "Aún no hay nada aquí"],
  ["Data will appear here once available", "Los datos aparecerán aquí una vez estén disponibles"],
  ["Get started by adding your first item", "Comience agregando su primer elemento"],
  ["No matching items", "No hay elementos coincidentes"],
  ["Try changing your filters to see more results", "Intente cambiar sus filtros para ver más resultados"],

  // ---- Dialog / Pagination ----
  ["Enter reason...", "Ingrese el motivo..."],
  ["Image Preview", "Vista previa de imagen"],
  ["Full preview", "Vista previa completa"],
  ["Go to previous page", "Ir a la página anterior"],
  ["Go to next page", "Ir a la página siguiente"],
  ["Previous slide", "Diapositiva anterior"],
  ["Next slide", "Siguiente diapositiva"],
  ["Scroll left", "Desplazar a la izquierda"],
  ["Scroll right", "Desplazar a la derecha"],

  // ---- Model descriptions ----
  ["Quantum Club's proprietary model", "Modelo propio de Quantum Club"],
  ["Google's most capable model", "El modelo más potente de Google"],
  ["Fast and efficient", "Rápido y eficiente"],
  ["OpenAI's flagship model", "El modelo insignia de OpenAI"],

  // ---- Password ----
  ["Password strength", "Seguridad de la contraseña"],
  ["Weak", "Débil"],
  ["Fair", "Regular"],
  ["Good", "Buena"],
  ["Strong", "Segura"],
  ["At least 8 characters", "Al menos 8 caracteres"],
  ["Uppercase letter", "Letra mayúscula"],
  ["Lowercase letter", "Letra minúscula"],
  ["Number", "Número"],
  ["Special character", "Carácter especial"],
  ["Confirm Password", "Confirmar contraseña"],
  ["12+ characters", "12+ caracteres"],
  ["No common patterns", "Sin patrones comunes"],

  // ---- Breadcrumbs ----
  ["Offer Comparison", "Comparación de ofertas"],
  ["Interview Prep", "Preparación para entrevistas"],

  // ---- Sync ----
  ["Syncing", "Sincronizando"],

  // ---- Carousel / Nav / Misc ----
  ["breadcrumb", "ruta de navegación"],
  ["Quick actions", "Acciones rápidas"],
  ["Retry loading sidebar", "Reintentar cargar barra lateral"],
  ["or use email", "o use correo electrónico"],
  ["Install App", "Instalar aplicación"],
  ["How to Install", "Cómo instalar"],
  ["Not now", "Ahora no"],
  ["Install on iOS", "Instalar en iOS"],
  ["Got it", "Entendido"],
  ["Live Now", "En vivo"],
  ["Starting Soon", "Comienza pronto"],
  ["All Status", "Todos los estados"],
  ["All caught up!", "¡Todo al día!"],
  ["Tips", "Consejos"],
  ["No items found", "No se encontraron elementos"],

  // ---- Common short labels still in English ----
  ["Loading OS Notes...", "Cargando notas de OS..."],
  ["Hiring", "Contratación"],

  // ---- More recruitment-related full phrases ----
  ["New application received", "Nueva solicitud recibida"],
  ["Interview scheduled", "Entrevista programada"],
  ["Feedback pending", "Retroalimentación pendiente"],
  ["Offer accepted", "Oferta aceptada"],
  ["Candidate update", "Actualización de candidato"],
  ["View details", "Ver detalles"],
  ["View Details", "Ver detalles"],
  ["No more results", "No hay más resultados"],
  ["End of results", "Fin de los resultados"],
  ["Showing results for", "Mostrando resultados para"],
  ["Search results", "Resultados de búsqueda"],
  ["Clear filters", "Limpiar filtros"],
  ["Clear Filters", "Limpiar filtros"],
  ["Apply filters", "Aplicar filtros"],
  ["Apply Filters", "Aplicar filtros"],
  ["Reset filters", "Restablecer filtros"],
  ["Reset Filters", "Restablecer filtros"],
  ["No notifications", "Sin notificaciones"],
  ["Mark all as read", "Marcar todo como leído"],
  ["Mark all read", "Marcar todo como leído"],
  ["View all notifications", "Ver todas las notificaciones"],
  ["New notification", "Nueva notificación"],
  ["Just now", "Ahora mismo"],
  ["A moment ago", "Hace un momento"],
  ["a moment ago", "hace un momento"],
  ["Not specified", "No especificado"],
  ["Not set", "No establecido"],
  ["Pending review", "Revisión pendiente"],
  ["Pending Review", "Revisión pendiente"],
  ["Under review", "En revisión"],
  ["Under Review", "En revisión"],
  ["Needs attention", "Requiere atención"],
  ["Action required", "Acción requerida"],
  ["Action Required", "Acción requerida"],
  ["No action needed", "No se requiere acción"],
  ["In queue", "En cola"],
  ["On hold", "En espera"],
  ["On Hold", "En espera"],
  ["Waiting for approval", "Esperando aprobación"],
  ["Waiting for response", "Esperando respuesta"],
  ["Response received", "Respuesta recibida"],
  ["No response", "Sin respuesta"],
  ["New message", "Nuevo mensaje"],
  ["Unread messages", "Mensajes no leídos"],
  ["Read messages", "Mensajes leídos"],
  ["All messages", "Todos los mensajes"],
  ["Send email", "Enviar correo"],
  ["Compose email", "Redactar correo"],
  ["Email sent", "Correo enviado"],
  ["Email failed", "Error al enviar correo"],
  ["Schedule meeting", "Programar reunión"],
  ["Schedule Meeting", "Programar reunión"],
  ["Join meeting", "Unirse a la reunión"],
  ["Join Meeting", "Unirse a la reunión"],
  ["Start meeting", "Iniciar reunión"],
  ["End meeting", "Finalizar reunión"],
  ["Cancel meeting", "Cancelar reunión"],
  ["Meeting cancelled", "Reunión cancelada"],
  ["Meeting scheduled", "Reunión programada"],
  ["No upcoming meetings", "No hay reuniones próximas"],
  ["Upcoming meetings", "Próximas reuniones"],
  ["Past meetings", "Reuniones pasadas"],
  ["Meeting notes", "Notas de la reunión"],
  ["Add note", "Agregar nota"],
  ["Add Note", "Agregar nota"],
  ["Edit note", "Editar nota"],
  ["Delete note", "Eliminar nota"],
  ["Save note", "Guardar nota"],
  ["Add comment", "Agregar comentario"],
  ["Edit comment", "Editar comentario"],
  ["Delete comment", "Eliminar comentario"],
  ["Post comment", "Publicar comentario"],
  ["Add tag", "Agregar etiqueta"],
  ["Remove tag", "Eliminar etiqueta"],
  ["Apply tag", "Aplicar etiqueta"],
  ["Select date", "Seleccionar fecha"],
  ["Select time", "Seleccionar hora"],
  ["Select Date", "Seleccionar fecha"],
  ["Select Time", "Seleccionar hora"],
  ["Date range", "Rango de fechas"],
  ["Date Range", "Rango de fechas"],
  ["Start date", "Fecha de inicio"],
  ["End date", "Fecha de finalización"],
  ["Start Date", "Fecha de inicio"],
  ["End Date", "Fecha de finalización"],
  ["Due date", "Fecha de vencimiento"],
  ["Due Date", "Fecha de vencimiento"],
  ["Created date", "Fecha de creación"],
  ["Last login", "Último acceso"],
  ["Never logged in", "Nunca inició sesión"],
  ["Account created", "Cuenta creada"],
  ["Email verified", "Correo verificado"],
  ["Phone verified", "Teléfono verificado"],
  ["Not verified", "No verificado"],
  ["Verify email", "Verificar correo"],
  ["Verify phone", "Verificar teléfono"],
  ["Send verification code", "Enviar código de verificación"],
  ["Enter verification code", "Ingrese el código de verificación"],
  ["Code sent", "Código enviado"],
  ["Invalid code", "Código no válido"],
  ["Code expired", "Código expirado"],
  ["Resend code", "Reenviar código"],
  ["Change password", "Cambiar contraseña"],
  ["Update password", "Actualizar contraseña"],
  ["Current password", "Contraseña actual"],
  ["New password", "Nueva contraseña"],
  ["Confirm new password", "Confirmar nueva contraseña"],
  ["Password changed", "Contraseña cambiada"],
  ["Password updated", "Contraseña actualizada"],
  ["Forgot password", "Olvidé mi contraseña"],
  ["Reset password", "Restablecer contraseña"],
  ["Create account", "Crear cuenta"],
  ["Delete account", "Eliminar cuenta"],
  ["Account settings", "Configuración de la cuenta"],
  ["Profile settings", "Configuración del perfil"],
  ["Notification settings", "Configuración de notificaciones"],
  ["Privacy settings", "Configuración de privacidad"],
  ["Security settings", "Configuración de seguridad"],
  ["General settings", "Configuración general"],
  ["Display settings", "Configuración de pantalla"],
  ["Email notifications", "Notificaciones por correo"],
  ["Push notifications", "Notificaciones push"],
  ["Desktop notifications", "Notificaciones de escritorio"],
  ["Mobile notifications", "Notificaciones móviles"],
  ["Turn on", "Activar"],
  ["Turn off", "Desactivar"],
  ["Turn On", "Activar"],
  ["Turn Off", "Desactivar"],
  ["Turned on", "Activado"],
  ["Turned off", "Desactivado"],
  ["Switch on", "Activar"],
  ["Switch off", "Desactivar"],

  // ---- Admin specific full phrases ----
  ["Pending Requests", "Solicitudes pendientes"],
  ["Role Distribution", "Distribución de roles"],
  ["Role distribution", "Distribución de roles"],
  ["No staff found", "No se encontró personal"],
  ["Loading staff...", "Cargando personal..."],
  ["Search by name, email, or role...", "Buscar por nombre, correo electrónico o rol..."],
  ["Company members", "Miembros de la empresa"],
  ["New Users (7d)", "Nuevos usuarios (7d)"],

  // ---- Remaining short broken translations ----
  ["Invalid Payment Information", "Información de pago no válida"],
  ["Unsupported File Type", "Tipo de archivo no compatible"],
  ["Upload Interrupted", "Carga interrumpida"],
  ["Upload Failed", "Error al subir archivo"],
  ["Meeting Error", "Error de reunión"],
  ["Payment Error", "Error de pago"],
  ["Check your spelling", "Verifique la ortografía"],
  ["Back online!", "¡De vuelta en línea!"],
  ["Fast and efficient", "Rápido y eficiente"],

  // ---- Additional patterns ----
  ["pagination", "paginación"],
  ["breadcrumb", "ruta de navegación"],
  ["logo", "logo"],
  ["pending", "pendiente"],
]);

// ============================================================================
// WORD-LEVEL TRANSLATION MAP
// For translating individual English words within mixed/compound strings.
// Applied when the full string doesn't match FULL_PHRASE_MAP.
// ============================================================================

const WORD_MAP = new Map([
  // Sorted by length descending to match longer words first
  ["Recommendations", "Recomendaciones"],
  ["Communications", "Comunicaciones"],
  ["Configurations", "Configuraciones"],
  ["Relationships", "Relaciones"],
  ["Configuration", "Configuración"],
  ["Communication", "Comunicación"],
  ["Notifications", "Notificaciones"],
  ["Announcement", "Anuncio"],
  ["Announcements", "Anuncios"],
  ["Achievements", "Logros"],
  ["Achievement", "Logro"],
  ["Requirements", "Requisitos"],
  ["Intelligence", "Inteligencia"],
  ["Marketplace", "Marketplace"],
  ["Observation", "Observación"],
  ["Information", "Información"],
  ["Performance", "Rendimiento"],
  ["Application", "Solicitud"],
  ["Applications", "Solicitudes"],
  ["Certification", "Certificación"],
  ["Automation", "Automatización"],
  ["Description", "Descripción"],
  ["Provisioning", "Aprovisionamiento"],
  ["Distribution", "Distribución"],
  ["Productivity", "Productividad"],
  ["Management", "Gestión"],
  ["Scheduling", "Programación"],
  ["Compliance", "Cumplimiento"],
  ["Integration", "Integración"],
  ["Integrations", "Integraciones"],
  ["Monitoring", "Monitoreo"],
  ["Assessment", "Evaluación"],
  ["Assessments", "Evaluaciones"],
  ["Background", "Antecedentes"],
  ["Operations", "Operaciones"],
  ["Enterprise", "Empresarial"],
  ["Candidates", "Candidatos"],
  ["Candidate", "Candidato"],
  ["Strategist", "Estratega"],
  ["Onboarding", "Incorporación"],
  ["Interviews", "Entrevistas"],
  ["Interview", "Entrevista"],
  ["Engagement", "Interacción"],
  ["Conversion", "Conversión"],
  ["Diligence", "Diligencia"],
  ["Templates", "Plantillas"],
  ["Template", "Plantilla"],
  ["Approvals", "Aprobaciones"],
  ["Approval", "Aprobación"],
  ["Analytics", "Análisis"],
  ["Settings", "Configuración"],
  ["Security", "Seguridad"],
  ["Overview", "Resumen"],
  ["Workload", "Carga de trabajo"],
  ["Workflow", "Flujo de trabajo"],
  ["Partners", "Socios"],
  ["Partner", "Socio"],
  ["Members", "Miembros"],
  ["Member", "Miembro"],
  ["Company", "Empresa"],
  ["Companies", "Empresas"],
  ["Customer", "Cliente"],
  ["Customers", "Clientes"],
  ["Employee", "Empleado"],
  ["Employees", "Empleados"],
  ["Recruiter", "Reclutador"],
  ["Activity", "Actividad"],
  ["Calendar", "Calendario"],
  ["Meetings", "Reuniones"],
  ["Meeting", "Reunión"],
  ["Sessions", "Sesiones"],
  ["Session", "Sesión"],
  ["Feedback", "Retroalimentación"],
  ["Pipeline", "Pipeline"],
  ["Capacity", "Capacidad"],
  ["Projects", "Proyectos"],
  ["Project", "Proyecto"],
  ["Disputes", "Disputas"],
  ["Proposals", "Propuestas"],
  ["Proposal", "Propuesta"],
  ["Inventory", "Inventario"],
  ["Webhooks", "Webhooks"],
  ["Webhook", "Webhook"],
  ["Contacts", "Contactos"],
  ["Contact", "Contacto"],
  ["Insights", "Información"],
  ["Campaigns", "Campañas"],
  ["Campaign", "Campaña"],
  ["Features", "Funcionalidades"],
  ["Feature", "Funcionalidad"],
  ["Patterns", "Patrones"],
  ["Pattern", "Patrón"],
  ["Retention", "Retención"],
  ["Registry", "Registro"],
  ["Platform", "Plataforma"],
  ["Requests", "Solicitudes"],
  ["Request", "Solicitud"],
  ["Bookmark", "Favorito"],
  ["Messages", "Mensajes"],
  ["Message", "Mensaje"],
  ["Earnings", "Ganancias"],
  ["Pending", "Pendiente"],
  ["Loading", "Cargando"],
  ["Metrics", "Métricas"],
  ["Reports", "Informes"],
  ["Report", "Informe"],
  ["Filters", "Filtros"],
  ["Export", "Exportar"],
  ["Import", "Importar"],
  ["Search", "Buscar"],
  ["Status", "Estado"],
  ["Health", "Estado"],
  ["Custom", "Personalizado"],
  ["Talent", "Talento"],
  ["Source", "Fuente"],
  ["Budget", "Presupuesto"],
  ["Social", "Social"],
  ["Global", "Global"],
  ["System", "Sistema"],
  ["Module", "Módulo"],
  ["Modules", "Módulos"],
  ["Active", "Activo"],
  ["Revenue", "Ingresos"],
  ["Growth", "Crecimiento"],
  ["Stages", "Etapas"],
  ["Stage", "Etapa"],
  ["Target", "Objetivo"],
  ["Scoring", "Puntuación"],
  ["Builder", "Constructor"],
  ["Editor", "Editor"],
  ["Viewer", "Visor"],
  ["Center", "Centro"],
  ["Command", "Comando"],
  ["Control", "Control"],
  ["Summary", "Resumen"],
  ["Details", "Detalles"],
  ["Detail", "Detalle"],
  ["History", "Historial"],
  ["Actions", "Acciones"],
  ["Action", "Acción"],
  ["Manage", "Gestionar"],
  ["Teams", "Equipos"],
  ["Roles", "Roles"],
  ["Users", "Usuarios"],
  ["User", "Usuario"],
  ["Staff", "Personal"],
  ["Admin", "Administración"],
  ["Queue", "Cola"],
  ["Alerts", "Alertas"],
  ["Alert", "Alerta"],
  ["Trends", "Tendencias"],
  ["Trend", "Tendencia"],
  ["Score", "Puntuación"],
  ["Cards", "Tarjetas"],
  ["Card", "Tarjeta"],
  ["Lists", "Listas"],
  ["List", "Lista"],
  ["Views", "Vistas"],
  ["Rules", "Reglas"],
  ["Rule", "Regla"],
  ["Roles", "Roles"],
  ["Role", "Rol"],
  ["Goals", "Objetivos"],
  ["Goal", "Objetivo"],
  ["Notes", "Notas"],
  ["Note", "Nota"],
  ["Tasks", "Tareas"],
  ["Task", "Tarea"],
  ["Links", "Enlaces"],
  ["Link", "Enlace"],
  ["Hub", "Centro"],
  ["Feed", "Feed"],
  ["Jobs", "Puestos"],
  ["Job", "Puesto"],
  ["new", "nuevo"],
  ["total", "total"],
  ["all", "todos"],
  ["the", "el"],
  ["and", "y"],
  ["for", "para"],
  ["with", "con"],
  ["from", "de"],
  ["this", "este"],
  ["that", "ese"],
  ["your", "su"],
  ["our", "nuestro"],
  ["their", "su"],
  ["has", "tiene"],
  ["have", "tiene"],
  ["been", "sido"],
  ["will", "será"],
  ["can", "puede"],
  ["are", "son"],
  ["not", "no"],
  ["was", "fue"],
]);

// ============================================================================
// TRANSLATION ENGINE
// ============================================================================

/**
 * Translate a single English string to Spanish.
 * Preserves {{variables}}, <tags>, brand names.
 */
function translateString(enValue) {
  if (typeof enValue !== 'string') return enValue;

  // Don't translate empty strings
  if (!enValue.trim()) return enValue;

  // Don't translate if it's only variables/HTML/technical tokens
  const stripped = enValue.replace(/\{\{[^}]+\}\}/g, '').replace(/<[^>]+>/g, '').trim();
  if (!stripped) return enValue;

  // Check full phrase map first (exact match)
  if (FULL_PHRASE_MAP.has(enValue)) {
    return FULL_PHRASE_MAP.get(enValue);
  }

  // Check if it's just a single word in the word map
  if (WORD_MAP.has(enValue)) {
    return WORD_MAP.get(enValue);
  }

  // Try case-insensitive match on full phrase map
  for (const [key, val] of FULL_PHRASE_MAP) {
    if (key.toLowerCase() === enValue.toLowerCase()) {
      // Preserve original casing pattern
      return val;
    }
  }

  // --- Intelligent substring/word-based translation ---
  // Extract and preserve {{variables}} and <html> tags
  const preserveTokens = [];
  let working = enValue;

  // Preserve {{variables}}
  working = working.replace(/\{\{[^}]+\}\}/g, (match) => {
    preserveTokens.push(match);
    return `__TOKEN_${preserveTokens.length - 1}__`;
  });

  // Preserve <html> tags
  working = working.replace(/<[^>]+>/g, (match) => {
    preserveTokens.push(match);
    return `__TOKEN_${preserveTokens.length - 1}__`;
  });

  // Try full phrase lookup on the cleaned string
  if (FULL_PHRASE_MAP.has(working)) {
    let result = FULL_PHRASE_MAP.get(working);
    // Restore tokens
    for (let i = 0; i < preserveTokens.length; i++) {
      result = result.replace(`__TOKEN_${i}__`, preserveTokens[i]);
    }
    return result;
  }

  // Word-by-word translation for compound strings
  // Split on word boundaries but preserve punctuation and whitespace
  let translated = working;

  // Sort WORD_MAP keys by length descending so longer matches take priority
  const sortedWords = [...WORD_MAP.entries()].sort((a, b) => b[0].length - a[0].length);

  for (const [eng, esp] of sortedWords) {
    // Use word boundary regex for replacement
    const regex = new RegExp(`\\b${escapeRegex(eng)}\\b`, 'g');
    translated = translated.replace(regex, esp);
  }

  // Restore tokens
  for (let i = 0; i < preserveTokens.length; i++) {
    translated = translated.replace(`__TOKEN_${i}__`, preserveTokens[i]);
  }

  return translated;
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Detect "Spanglish" — ES values that are contaminated with English words.
 * These are partial translations that mixed Spanish and English and should
 * be re-translated from EN.
 */
const ENGLISH_MARKERS = [
  // Common English words that should NOT appear in proper Spanish translations
  // (case-sensitive to avoid false positives)
  /\bthe\b/i,
  /\byour\b/i,
  /\byou\b/i,
  /\bwith\b/i,
  /\bfrom\b/i,
  /\bthis\b/i,
  /\bthat\b/i,
  /\bwhat\b/i,
  /\bwhen\b/i,
  /\bwhere\b/i,
  /\bhave\b/i,
  /\bhas\b/i,
  /\bbeen\b/i,
  /\bwill\b/i,
  /\bwould\b/i,
  /\bcould\b/i,
  /\bshould\b/i,
  /\bcan\b/i,
  /\bare\b/i,
  /\bwas\b/i,
  /\bwere\b/i,
  /\bnot\b/i,
  /\bhere\b/i,
  /\bthere\b/i,
  /\binto\b/i,
  /\babout\b/i,
  /\btheir\b/i,
  /\bthey\b/i,
  /\bthem\b/i,
  /\bsome\b/i,
  /\bany\b/i,
  /\bbefore\b/,
  /\bafter\b/,
  /\bbetween\b/,
  /\bduring\b/,
  /\bthrough\b/,
  /\bagainst\b/,
  /\bsettings\b/i,
  /\bloading\b/i,
  /\btracking\b/i,
  /\bprocessing\b/i,
  /\bbuilder\b/i,
  /\bmanagement\b/i,
  /\bschedule\b/i,
  /\bscheduling\b/i,
  /\bintelligence\b/i,
  /\bdashboard\b(?!.*\bpanel\b)/i,  // Dashboard alone (not "Dashboard panel" which is fine)
  /\boverall\b/i,
  /\bcurrent\b/i,
  /\bplease\b/i,
  /\bchecks\b/i,
  /\bconfiguration\b/i,
  /\bdistribution\b/i,
  /\bproductivity\b/i,
  /\boperations\b/i,
  /\benforcement\b/i,
  /\bmetering\b/i,
  /\bretention\b/i,
  /\bdiligence\b/i,
  /\bsomething\b/i,
  /\bmanager\b/i,
  /\bviewer\b/i,
  /\bresource\b/i,
  /\bmanage\b/i,
  /\breview\b/i,
  /\brecord\b/i,
  /\brecords\b/i,
  /\bupload\b/i,
  /\bdownload\b/i,
  /\bintegration\b/i,
  /\bmonitoring\b/i,
  /\bfrequency\b/i,
  /\bperformance\b/i,
  /\btimeout\b/i,
  /\bresponse\b/i,
  /\brequired\b/i,
  /\bsupported\b/i,
  /\bconnection\b/i,
  /\binterrupted\b/i,
  /\bunexpected\b/i,
  /\boccurred\b/i,
  /\bverify\b/i,
  /\b(?:is|are|was|were|be|being)\s+(?:a|an|the|not|no|currently|already)\b/i,
];

// Brand names and technical terms that are OK in Spanish text
const SAFE_ENGLISH = new Set([
  'club', 'ai', 'os', 'crm', 'api', 'kpi', 'pipeline', 'dashboard',
  'quantum', 'feed', 'blog', 'radio', 'pilot', 'hub', 'pro',
  'whatsapp', 'webhook', 'webhooks', 'token', 'tokens', 'url',
  'ssl', 'gdpr', 'mfa', 'sso', 'eeo', 'cv', 'pdf', 'csv',
  'json', 'html', 'css', 'ip', 'agentic', 'quin', 'freelance',
  'senior', 'junior', 'lead', 'spam', 'stealth', 'marketplace',
  'dpa', 'baa', 'live', 'ok', 'email', 'online', 'offline',
  'video', 'chat', 'app', 'widget', 'plugin', 'premium', 'startup',
  'scale-up', 'rrss', 'rr.hh', 'roi', 'linkedin', 'google',
  'apple', 'github', 'safari', 'chrome', 'firefox', 'streak',
  'default', 'slack', 'zoom', 'teams', 'meet', 'livekit',
  'stripe', 'resend', 'twilio', 'moneybird', 'instantly',
  'apify', 'fathom', 'fireflies', 'elevenlabs', 'brandfetch',
  'greenhouse', 'findymail', 'millionverifier',
]);

// Common English words that appear in short Spanglish compounds (2 words)
// These are words that should never be in a proper Spanish translation
const SHORT_ENGLISH_WORDS = new Set([
  'page', 'pages', 'tab', 'tabs', 'panel', 'board', 'builder',
  'tracking', 'management', 'scheduling', 'configuration',
  'hub', 'center', 'control', 'command', 'engine',
  'kits', 'checks', 'onboarding', 'intelligence',
  'templates', 'approvals', 'distribution', 'library',
  'productivity', 'analytics', 'enforcement', 'metering',
  'retention', 'diligence', 'marketplace', 'portal',
  'operations', 'monitoring', 'allowlist', 'planning',
  'relationships', 'requests', 'projects', 'proposals',
  'funnel', 'settings', 'candidates', 'companies', 'jobs',
  'statuses', 'login', 'members', 'staff', 'partners',
  'found', 'exported', 'loading', 'processing',
  'my', 'all', 'new', 'total', 'view', 'edit',
  'open', 'close', 'save', 'send', 'stop', 'start',
  'quick', 'actions', 'image', 'sounds', 'generation',
  'voice', 'message', 'recording', 'sidebar', 'meeting',
  'support', 'now', 'again', 'retry', 'retrying',
  'reload', 'leave', 'contact', 'toggle',
  'error', 'failed', 'interrupted', 'invalid',
  'unsupported', 'technical', 'details', 'information',
  'type', 'online', 'offline', 'attempt', 'check',
  'spelling', 'fast', 'efficient', 'preview', 'full',
  'file', 'reference', 'suggestion', 'payment',
  'storage', 'connection', 'restored', 'lost',
  'device', 'media', 'camera', 'microphone',
  'access', 'required', 'strong', 'weak', 'fair',
  'good', 'medium', 'patterns', 'characters',
  'uppercase', 'lowercase', 'special', 'character',
  'number', 'strength', 'password', 'confirm',
]);

function isSpanglish(esValue, enValue) {
  if (typeof esValue !== 'string' || typeof enValue !== 'string') return false;

  // If it's identical to EN, it's not "Spanglish" - it's untranslated (handled separately)
  if (esValue === enValue) return false;

  // Strip {{variables}}, <tags>, brand names, and technical terms before checking
  let cleaned = esValue
    .replace(/\{\{[^}]+\}\}/g, '')
    .replace(/<[^>]+>/g, '')
    .replace(/\b(?:The Quantum Club|Club OS|Club AI|Club Pilot|Club Radio|QUIN)\b/gi, '');

  // Remove known safe English words (brands, tech terms)
  for (const safe of SAFE_ENGLISH) {
    const safeRegex = new RegExp(`\\b${escapeRegex(safe)}\\b`, 'gi');
    cleaned = cleaned.replace(safeRegex, '');
  }

  const words = cleaned.trim().split(/\s+/).filter(w => w.length > 0);

  // For short strings (1-3 words), check if any word is a known English word
  // that shouldn't be in proper Spanish
  if (words.length <= 3 && words.length > 0) {
    for (const word of words) {
      const lower = word.toLowerCase().replace(/[^a-záéíóúñü]/g, '');
      if (lower && SHORT_ENGLISH_WORDS.has(lower)) {
        return true;
      }
    }
  }

  // For longer strings, use the marker pattern approach
  // Count how many English marker patterns match
  let englishHits = 0;
  for (const pattern of ENGLISH_MARKERS) {
    if (pattern.test(cleaned)) {
      englishHits++;
    }
  }

  // Also check for SHORT_ENGLISH_WORDS in longer strings
  for (const word of words) {
    const lower = word.toLowerCase().replace(/[^a-záéíóúñü]/g, '');
    if (lower && SHORT_ENGLISH_WORDS.has(lower)) {
      englishHits++;
    }
  }

  // For strings with 3+ words, even 1 hit is suspicious if there are other common English words
  if (words.length >= 3) {
    // Check for very common English function words that never appear in Spanish
    const englishFunctionWords = /\b(?:the|an?|is|are|was|were|be|been|being|have|has|had|do|does|did|will|would|could|should|may|might|shall|can|must|need|dare|ought|to|of|in|for|on|at|by|with|from|into|through|during|before|after|above|below|between|under|over|if|or|but|so|yet|nor|not|than|then|when|while|where|how|what|which|who|whom|whose|that|this|these|those|there|here|it|its|he|she|they|them|their|his|her|we|our|us|you|your|my|me|am|isn't|aren't|wasn't|weren't|hasn't|haven't|hadn't|doesn't|don't|didn't|won't|wouldn't|couldn't|shouldn't|can't|mustn't|needn't|no|yes|up|down|out|off|back|away|again|also|too|very|much|more|most|less|least|just|only|still|already|even|never|always|often|sometimes|usually|please|try|check|get|set|let|make|take|give|keep|put|come|go|see|look|find|use|used|using|work|works|working|some|any|all|every|each|both|few|many|other|another|such|next|last|same|different|own|new|old|large|small|big|long|short|high|low|good|bad|right|wrong|first|second|third|sure|able|because|since|until|unless|though|although|however|therefore|otherwise|instead|rather|whether|either|neither|once|twice|enough|quite|rather|available|currently|recently|already|immediately|automatically|successfully|previously|temporarily|permanently|likely|unlikely|possible|impossible|necessary|required|supported|expected|allowed|supposed|unable|below|above)\b/gi;
    const fnMatches = cleaned.match(englishFunctionWords);
    if (fnMatches && fnMatches.length >= 1) {
      englishHits += fnMatches.length;
    }
  }

  // If 2+ English indicators found, it's Spanglish
  return englishHits >= 2;
}

/**
 * Recursively walk EN and ES objects.
 * If ES value === EN value, translate it.
 * If ES value is Spanglish (mixed English/Spanish), re-translate from EN.
 * If ES value is a proper translation, keep it.
 * If key exists in EN but not in ES, translate and add it.
 */
function mergeTranslations(enObj, esObj) {
  const result = {};

  for (const key of Object.keys(enObj)) {
    const enVal = enObj[key];
    const esVal = esObj?.[key];

    if (typeof enVal === 'object' && enVal !== null && !Array.isArray(enVal)) {
      // Recurse into nested objects
      result[key] = mergeTranslations(enVal, typeof esVal === 'object' ? esVal : {});
    } else if (typeof enVal === 'string') {
      if (esVal === undefined || esVal === enVal) {
        // ES is missing or identical to EN — translate it
        result[key] = translateString(enVal);
      } else if (isSpanglish(esVal, enVal)) {
        // ES is contaminated Spanglish — re-translate from EN
        result[key] = translateString(enVal);
      } else {
        // ES already differs and is proper — keep existing translation
        result[key] = esVal;
      }
    } else {
      // Numbers, booleans, arrays, etc. — keep as-is
      result[key] = esVal !== undefined ? esVal : enVal;
    }
  }

  return result;
}

// ============================================================================
// MAIN EXECUTION
// ============================================================================

let totalKeys = 0;
let translatedKeys = 0;
let spanglishFixed = 0;
let keptKeys = 0;

function countChanges(enObj, esObj, newObj) {
  for (const key of Object.keys(enObj)) {
    const enVal = enObj[key];

    if (typeof enVal === 'object' && enVal !== null && !Array.isArray(enVal)) {
      countChanges(enVal, esObj?.[key] || {}, newObj[key]);
    } else if (typeof enVal === 'string') {
      totalKeys++;
      const esVal = esObj?.[key];
      if (esVal === undefined || esVal === enVal) {
        translatedKeys++;
      } else if (isSpanglish(esVal, enVal)) {
        spanglishFixed++;
      } else {
        keptKeys++;
      }
    }
  }
}

console.log('=== Spanish Translation Script ===\n');
console.log(`EN directory: ${EN_DIR}`);
console.log(`ES directory: ${ES_DIR}\n`);

for (const ns of NAMESPACES) {
  const enFile = join(EN_DIR, `${ns}.json`);
  const esFile = join(ES_DIR, `${ns}.json`);

  if (!existsSync(enFile)) {
    console.warn(`  SKIP: ${ns}.json — EN file not found`);
    continue;
  }

  const enData = JSON.parse(readFileSync(enFile, 'utf8'));
  const esData = existsSync(esFile) ? JSON.parse(readFileSync(esFile, 'utf8')) : {};

  // Reset counters per namespace
  totalKeys = 0;
  translatedKeys = 0;
  spanglishFixed = 0;
  keptKeys = 0;

  const result = mergeTranslations(enData, esData);

  countChanges(enData, esData, result);

  // Write the result
  writeFileSync(esFile, JSON.stringify(result, null, 2) + '\n', 'utf8');

  console.log(`  ${ns}.json — ${totalKeys} keys total, ${translatedKeys} translated, ${spanglishFixed} spanglish fixed, ${keptKeys} kept existing`);
}

console.log('\nDone! All 13 namespaces processed.');
