#!/usr/bin/env node
/**
 * Smart NL Translator — Reads actual untranslated keys from EN/NL files
 * and applies translations based on the English value.
 * Uses a massive {English phrase → Dutch phrase} dictionary.
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, resolve } from 'path';

const LOCALES = resolve(import.meta.dirname, '../src/i18n/locales');
const NAMESPACES = ['admin','analytics','auth','candidates','common','compliance','contracts','jobs','meetings','messages','onboarding','partner','settings'];

// ============================================================================
// MASSIVE English → Dutch translation dictionary
// Covers ALL common patterns found in the ClubOS codebase
// ============================================================================
const EN_TO_NL = {
  // === Privacy Policy & Legal ===
  "LinkedIn profile URL and professional profile data": "LinkedIn profiel-URL en professionele profielgegevens",
  "Profile photo/avatar": "Profielfoto/avatar",
  "CV/Resume documents": "CV-/resumedocumenten",
  "Work experience, skills, education, certifications": "Werkervaring, vaardigheden, opleiding, certificeringen",
  "Current job title and employment history": "Huidige functietitel en arbeidsverleden",
  "Professional achievements and portfolio work": "Professionele prestaties en portfoliowerk",
  "Salary expectations (current and target ranges)": "Salarisverwachtingen (huidige en gewenste ranges)",
  "Notice period and contract end dates": "Opzegperiode en contracteinddatums",
  "Work preferences (remote, location, employment type)": "Werkvoorkeuren (remote, locatie, dienstverband)",
  "Career goals and aspirations": "Carrièredoelen en ambities",
  "Company Data (For Partners)": "Bedrijfsgegevens (voor partners)",
  "Company name, website, industry": "Bedrijfsnaam, website, sector",
  "Team structure and organizational charts": "Teamstructuur en organogrammen",
  "Hiring needs and job descriptions": "Wervingsbehoeften en functiebeschrijvingen",
  "Interview notes and candidate evaluations": "Gespreksnotities en kandidaatbeoordelingen",
  "Messages exchanged with strategists and partners": "Berichten uitgewisseld met strategen en partners",
  "Email communications (via integrations)": "E-mailcommunicatie (via integraties)",
  "Meeting transcripts and interview recordings (with explicit consent)": "Vergadertranscripties en gespreksopnames (met nadrukkelijke toestemming)",
  "AI conversation history (Club AI interactions)": "AI-gespreksgeschiedenis (Club AI-interacties)",
  "Application history and job views": "Sollicitatiegeschiedenis en vacatureweergaven",
  "Search queries and filter preferences": "Zoekopdrachten en filtervoorkeuren",
  "Platform engagement metrics (feature usage, session duration)": "Platformbetrokkenheidsmetrieken (functiegebruik, sessieduur)",
  "Referral activity and rewards earned": "Verwijzingsactiviteit en verdiende beloningen",
  "IP address, device information, browser type": "IP-adres, apparaatinformatie, browsertype",
  "Cookies and session identifiers": "Cookies en sessie-identificatoren",
  "Login timestamps and authentication logs": "Login-tijdstempels en authenticatielogs",
  "Error logs and diagnostic data": "Foutlogs en diagnostische gegevens",
  "Referral reward amounts and payment details": "Verwijzingsbeloningsbedragen en betalingsgegevens",
  "Consent (Article 6(1)(a))": "Toestemming (Artikel 6(1)(a))",
  "Contract Performance (Article 6(1)(b))": "Uitvoering van een overeenkomst (Artikel 6(1)(b))",
  "Legitimate Interest (Article 6(1)(f))": "Gerechtvaardigd belang (Artikel 6(1)(f))",
  "Legal Obligation (Article 6(1)(c))": "Wettelijke verplichting (Artikel 6(1)(c))",
  
  // === Navigation ===
  "Feed": "Tijdlijn",
  "Achievements": "Prestaties",
  "Live Hub": "Live Hub",
  "Scheduling": "Planning",
  "Blog": "Blog",
  "Pipeline": "Pijplijn",
  "Tasks": "Taken",
  "Templates": "Sjablonen",
  "Documents": "Documenten",
  "Favorites": "Favorieten",
  "Companies": "Bedrijven",
  "Offers": "Aanbiedingen",
  "Projects": "Projecten",
  "Proposals": "Voorstellen",
  "Disputes": "Geschillen",
  "Contracts": "Contracten",
  "Campaigns": "Campagnes",
  "Hiring": "Werving",
  "Partnerships": "Partnerschappen",
  "Operations": "Operaties",
  "Finance": "Financiën",
  "Governance": "Bestuur",
  "Developer": "Ontwikkelaar",
  "Communication": "Communicatie",
  "Learning": "Leren",
  "Support": "Ondersteuning",
  "Career": "Carrière",
  "Social": "Sociaal",

  // === Common actions ===
  "Sign Contract": "Contract ondertekenen",
  "Milestone started!": "Mijlpaal gestart!",
  "Milestone submitted for review!": "Mijlpaal ingediend ter beoordeling!",
  "Milestone paid!": "Mijlpaal betaald!",
  "Failed to update milestone": "Bijwerken van mijlpaal mislukt",
  "Contract not found": "Contract niet gevonden",
  "This contract does not exist": "Dit contract bestaat niet",
  "Back to Contracts": "Terug naar contracten",
  "Contract Details": "Contractdetails",
  "Failed to load candidates": "Kandidaten laden mislukt",
  "Export failed": "Exporteren mislukt",
  "Exported successfully": "Succesvol geëxporteerd",
  "Partner Account": "Partneraccount",
  "Validating invite code…": "Uitnodigingscode valideren…",
  "Sign in timed out. Please try again.": "Inloggen verlopen. Probeer het opnieuw.",
  "Sign in to your account": "Log in op uw account",
  "Create your account": "Maak uw account aan",
  "Send reset link": "Resetlink versturen",
  "Back to sign in": "Terug naar inloggen",
  "Reset your password": "Uw wachtwoord opnieuw instellen",
  "New Job": "Nieuwe vacature",
  "You need to be associated with a company to access this dashboard": "U moet aan een bedrijf gekoppeld zijn om dit dashboard te openen",
  
  // === Dashboard ===
  "Strong Growth": "Sterke groei",
  "Growth Trend": "Groeitrend",
  "Active Users": "Actieve gebruikers",
  "New Users": "Nieuwe gebruikers",
  "Inactive Users": "Inactieve gebruikers",
  "Total Users": "Totale gebruikers",
  "Engagement Rate": "Betrokkenheidspercentage",
  "Daily Active Users": "Dagelijks actieve gebruikers",
  "Weekly Active Users": "Wekelijks actieve gebruikers",
  "Monthly Active Users": "Maandelijks actieve gebruikers",
  "User Growth": "Gebruikersgroei",
  "Suspended": "Geschorst",
  "Profile Complete": "Profiel compleet",
  "Profile Incomplete": "Profiel onvolledig",
  "Recent Applications": "Recente sollicitaties",
  "Top Rated": "Hoogst beoordeeld",
  "Flagged": "Gemarkeerd",
  "Search Candidates": "Kandidaten zoeken",
  "Filter by Status": "Filteren op status",
  "Filter by Role": "Filteren op rol",
  "Sort by": "Sorteren op",
  "Sort By": "Sorteren op",
  "Last Active": "Laatst actief",
  "Date Joined": "Datum van toetreding",
  "Application Count": "Aantal sollicitaties",
  "Active Partners": "Actieve partners",
  "Inactive Partners": "Inactieve partners",
  "Partner Revenue": "Partneromzet",
  "Total Placements": "Totale plaatsingen",
  "Avg Placement Time": "Gem. plaatsingstijd",
  "Satisfaction Score": "Tevredenheidsscore",
  "Under Performers": "Onderpresteerders",
  "New Partners": "Nieuwe partners",
  "Partner Growth": "Partnergroei",
  "Active Strategists": "Actieve strategen",
  "Assigned Candidates": "Toegewezen kandidaten",
  "Performance Score": "Prestatiescore",
  "Client Satisfaction": "Klanttevredenheid",
  "Placement Success": "Plaatsingssucces",
  "Response Time": "Reactietijd",
  
  // === Meetings ===
  "Google Calendar": "Google Agenda",
  "Outlook Calendar": "Outlook Agenda",
  "Apple Calendar": "Apple Agenda",
  "Join Meeting": "Deelnemen aan vergadering",
  "Start Meeting": "Vergadering starten",
  "End Meeting": "Vergadering beëindigen",
  "Schedule Meeting": "Vergadering plannen",
  "Meeting Details": "Vergaderingsdetails",
  "Meeting Notes": "Vergadernotities",
  "Recording": "Opname",
  "Transcript": "Transcript",
  "Action Items": "Actiepunten",
  "Participants": "Deelnemers",
  "Agenda": "Agenda",
  "Add Agenda Item": "Agendapunt toevoegen",
  "Meeting Scheduled": "Vergadering gepland",
  "Meeting Cancelled": "Vergadering geannuleerd",
  "Meeting Started": "Vergadering gestart",
  "Meeting Ended": "Vergadering beëindigd",
  "No Meetings": "Geen vergaderingen",
  "No meetings scheduled": "Geen vergaderingen gepland",
  "Upcoming": "Aankomend",
  "Past Meetings": "Eerdere vergaderingen",
  "My Meetings": "Mijn vergaderingen",
  "All Meetings": "Alle vergaderingen",
  "Duration": "Duur",
  "Private": "Privé",
  "Recording Available": "Opname beschikbaar",
  "Camera": "Camera",
  "Microphone": "Microfoon",
  "Screen Share": "Scherm delen",
  "Chat": "Chat",
  "Reactions": "Reacties",
  "Raise Hand": "Hand opsteken",
  "Mute": "Dempen",
  "Unmute": "Ontdempen",
  "Turn On Camera": "Camera inschakelen",
  "Turn Off Camera": "Camera uitschakelen",
  "Share Screen": "Scherm delen",
  "Stop Sharing": "Delen stoppen",
  "End Call": "Gesprek beëindigen",
  "You are muted": "U bent gedempt",
  "Camera is off": "Camera is uit",
  "Poor connection": "Slechte verbinding",
  "Reconnecting": "Opnieuw verbinden",
  "Connection restored": "Verbinding hersteld",
  
  // === Jobs ===
  "Post Job": "Vacature plaatsen",
  "Edit Job": "Vacature bewerken",
  "Delete Job": "Vacature verwijderen",
  "Job Title": "Functietitel",
  "Job Description": "Functiebeschrijving",
  "Job Type": "Type dienstverband",
  "Full-time": "Voltijd",
  "Part-time": "Deeltijd",
  "Contract": "Contract",
  "Freelance": "Freelance",
  "Internship": "Stage",
  "Temporary": "Tijdelijk",
  "Remote": "Op afstand",
  "On-site": "Op locatie",
  "Hybrid": "Hybride",
  "Experience Level": "Ervaringsniveau",
  "Entry Level": "Instapniveau",
  "Mid Level": "Gemiddeld niveau",
  "Senior Level": "Senior niveau",
  "Executive": "Directieniveau",
  "Salary Range": "Salarisrange",
  "Benefits": "Arbeidsvoorwaarden",
  "Skills Required": "Vereiste vaardigheden",
  "Apply Now": "Nu solliciteren",
  "Save Job": "Vacature opslaan",
  "Share Job": "Vacature delen",
  "Report Job": "Vacature melden",
  "Application Submitted": "Sollicitatie ingediend",
  "Application Deadline": "Sollicitatiedeadline",
  "Posted": "Geplaatst",
  "Views": "Weergaven",
  "Applicants": "Sollicitanten",
  "Match Score": "Matchscore",
  "Cover Letter": "Sollicitatiebrief",
  "Resume": "CV",
  "Portfolio": "Portfolio",
  "References": "Referenties",
  "Skills Match": "Vaardigheidsmatch",
  "Location Match": "Locatiematch",
  "Salary Match": "Salarismatch",
  "Culture Fit": "Culturele match",
  
  // === Onboarding ===
  "Welcome to The Quantum Club": "Welkom bij The Quantum Club",
  "Let's get you set up": "Laten we u instellen",
  "Complete Your Profile": "Vul uw profiel aan",
  "Upload Your Resume": "Upload uw CV",
  "Set Your Preferences": "Stel uw voorkeuren in",
  "Explore The Platform": "Ontdek het platform",
  "Skip for Now": "Nu overslaan",
  "Next Step": "Volgende stap",
  "Previous Step": "Vorige stap",
  "Finish Setup": "Instelling voltooien",
  "Almost There!": "Bijna klaar!",
  "You're All Set!": "U bent helemaal klaar!",
  "Start Exploring": "Begin met verkennen",
  "Take a Tour": "Rondleiding",
  "Watch Tutorial": "Tutorial bekijken",
  
  // === Settings ===
  "Account Settings": "Accountinstellingen",
  "Profile Settings": "Profielinstellingen",
  "Notification Settings": "Meldingsinstellingen",
  "Privacy Settings": "Privacy-instellingen",
  "Security Settings": "Beveiligingsinstellingen",
  "Display Settings": "Weergave-instellingen",
  "Language Settings": "Taalinstellingen",
  "Email Notifications": "E-mailmeldingen",
  "Push Notifications": "Pushmeldingen",
  "SMS Notifications": "SMS-meldingen",
  "Connected Accounts": "Gekoppelde accounts",
  "Delete Account": "Account verwijderen",
  "Deactivate Account": "Account deactiveren",
  "Export Data": "Gegevens exporteren",
  "Change Password": "Wachtwoord wijzigen",
  "Change Email": "E-mail wijzigen",
  "Two-Factor Authentication": "Tweefactorauthenticatie",
  "Login Sessions": "Inlogsessies",
  "API Access": "API-toegang",
  "Webhooks": "Webhooks",
  "Integrations": "Integraties",
  "Billing & Plans": "Facturering & abonnementen",
  "Upgrade Plan": "Plan upgraden",
  "Current Plan": "Huidig plan",
  "Usage": "Gebruik",
  "Payment Methods": "Betaalmethoden",
  "Invoice History": "Factuurgeschiedenis",
  "Auto-Renew": "Automatisch vernieuwen",
  "Cancel Subscription": "Abonnement opzeggen",
  
  // === Messages ===
  "New Message": "Nieuw bericht",
  "All Messages": "Alle berichten",
  "Unread": "Ongelezen",
  "Starred": "Met ster",
  "Archived": "Gearchiveerd",
  "Search Messages": "Berichten zoeken",
  "Type a message...": "Typ een bericht...",
  "Send Message": "Bericht versturen",
  "Reply": "Beantwoorden",
  "Forward": "Doorsturen",
  "Delete Message": "Bericht verwijderen",
  "Mark as Read": "Als gelezen markeren",
  "Mark as Unread": "Als ongelezen markeren",
  "Pin Message": "Bericht vastmaken",
  "No messages yet": "Nog geen berichten",
  "Start a conversation": "Begin een gesprek",
  "Online": "Online",
  "Offline": "Offline",
  "Typing...": "Aan het typen...",
  "Seen": "Gezien",
  "Delivered": "Afgeleverd",
  "Read": "Gelezen",
  "Attachment": "Bijlage",
  "Attachments": "Bijlagen",
  "Add Attachment": "Bijlage toevoegen",
  "Group Chat": "Groepsgesprek",
  "Create Group": "Groep aanmaken",
  "Group Name": "Groepsnaam",
  "Add Members": "Leden toevoegen",
  "Remove Member": "Lid verwijderen",
  "Leave Group": "Groep verlaten",
  "Mute Notifications": "Meldingen dempen",
  "Block User": "Gebruiker blokkeren",
  "Report User": "Gebruiker melden",
  
  // === Candidates ===
  "All Candidates": "Alle kandidaten",
  "Active Candidates": "Actieve kandidaten",
  "Shortlisted": "Geselecteerd",
  "Rejected": "Afgewezen",
  "Hired": "Aangenomen",
  "Withdrawn": "Teruggetrokken",
  "Candidate Profile": "Kandidaatprofiel",
  "Application Status": "Sollicitatiestatus",
  "Interview Schedule": "Gespreksplanning",
  "Assessment Results": "Beoordelingsresultaten",
  "Notes": "Notities",
  "Add Note": "Notitie toevoegen",
  "Tags": "Tags",
  "Add Tag": "Tag toevoegen",
  "Source": "Bron",
  "Referred By": "Verwezen door",
  "Applied On": "Gesolliciteerd op",
  "Last Updated": "Laatst bijgewerkt",
  "Move to Stage": "Naar fase verplaatsen",
  "Schedule Interview": "Gesprek plannen",
  "Send Email": "E-mail versturen",
  "Send Message": "Bericht versturen",
  "Download Resume": "CV downloaden",
  "Reject Candidate": "Kandidaat afwijzen",
  "Make Offer": "Aanbod doen",
  "Candidate Rejected": "Kandidaat afgewezen",
  "Offer Sent": "Aanbod verzonden",
  "Offer Accepted": "Aanbod geaccepteerd",
  "Offer Declined": "Aanbod afgewezen",
  
  // === Analytics ===
  "Total Applications": "Totaal sollicitaties",
  "Conversion Rate": "Conversiepercentage",
  "Average Time to Hire": "Gem. tijd tot aanname",
  "Source Effectiveness": "Effectiviteit van bronnen",
  "Pipeline Overview": "Pijplijn overzicht",
  "Funnel Analysis": "Trechteranalyse",
  "Trend Analysis": "Trendanalyse",
  "Year over Year": "Jaar over jaar",
  "Month over Month": "Maand over maand",
  "Week over Week": "Week over week",
  "Custom Range": "Aangepast bereik",
  "Last 7 Days": "Afgelopen 7 dagen",
  "Last 30 Days": "Afgelopen 30 dagen",
  "Last 90 Days": "Afgelopen 90 dagen",
  "Last Year": "Afgelopen jaar",
  "Export Report": "Rapport exporteren",
  "Download CSV": "CSV downloaden",
  "Download PDF": "PDF downloaden",
  "Share Report": "Rapport delen",
  "Generate Report": "Rapport genereren",
  "Report Generated": "Rapport gegenereerd",
  "No Data": "Geen gegevens",
  "No data available for the selected period": "Geen gegevens beschikbaar voor de geselecteerde periode",
  "Try adjusting your date range or filters": "Pas uw datumbereik of filters aan",
  
  // === Partner ===
  "Partner Dashboard": "Partnerdashboard",
  "Partner Analytics": "Partneranalyse",
  "Partner Settings": "Partnerinstellingen",
  "Partner Profile": "Partnerprofiel",
  "Active Jobs": "Actieve vacatures",
  "My Candidates": "Mijn kandidaten",
  "Placement Rate": "Plaatsingspercentage",
  "Revenue Generated": "Gegenereerde omzet",
  "Top Sources": "Topbronnen",
  "Client Management": "Klantbeheer",
  "Add Client": "Klant toevoegen",
  "Client Details": "Klantdetails",
  "Client Revenue": "Klantomzet",
  "Client Contracts": "Klantcontracten",
  "Service Level": "Serviceniveau",
  "Renewal Date": "Verlengingsdatum",
  "Team Management": "Teambeheer",
  "Add Team Member": "Teamlid toevoegen",
  "Team Performance": "Teamprestaties",
  "Commission Structure": "Commissiestructuur",
  "Payout Schedule": "Uitbetalingsschema",
  
  // === Compliance ===
  "GDPR Compliance": "AVG-naleving",
  "Data Protection": "Gegevensbescherming",
  "Privacy Impact Assessment": "Privacy-effectbeoordeling",
  "Data Processing Agreement": "Gegevensverwerkingsovereenkomst",
  "Consent Management": "Toestemmingsbeheer",
  "Right to Access": "Recht op inzage",
  "Right to Erasure": "Recht op vergetelheid",
  "Data Breach Notification": "Melding gegevensinbreuk",
  "Audit Trail": "Auditspoor",
  "Compliance Report": "Nalevingsrapport",
  "Policy Updates": "Beleidswijzigingen",
  "Training Records": "Trainingsregistraties",
  "Certification Status": "Certificeringsstatus",
  
  // === Common status phrases ===
  "No items found": "Geen items gevonden",
  "Try adjusting your search or filters": "Pas uw zoekopdracht of filters aan",
  "No results match your search": "Geen resultaten gevonden voor uw zoekopdracht",
  "Something went wrong. Please try again.": "Er ging iets mis. Probeer het opnieuw.",
  "This action cannot be undone": "Deze actie kan niet ongedaan worden gemaakt",
  "Are you sure you want to continue?": "Weet u zeker dat u wilt doorgaan?",
  "Are you sure?": "Weet u het zeker?",
  "Changes saved successfully": "Wijzigingen succesvol opgeslagen",
  "Failed to save changes": "Wijzigingen opslaan mislukt",
  "Please fill in all required fields": "Vul alle verplichte velden in",
  "Invalid format": "Ongeldig formaat",
  "Maximum file size exceeded": "Maximale bestandsgrootte overschreden",
  "File uploaded successfully": "Bestand succesvol geüpload",
  "Upload failed": "Upload mislukt",
  "Please try again later": "Probeer het later opnieuw",
  "Session expired": "Sessie verlopen",
  "Please log in again": "Log opnieuw in",
  "Access denied": "Toegang geweigerd",
  "You don't have permission to access this resource": "U heeft geen toestemming om deze bron te openen",
  "Page not found": "Pagina niet gevonden",
  "The page you're looking for doesn't exist": "De pagina die u zoekt bestaat niet",
  "Go back": "Ga terug",
  "Go to homepage": "Ga naar de startpagina",
  "Contact support": "Neem contact op met support",
  "Need help?": "Hulp nodig?",
  "Learn more": "Meer informatie",
  "See all": "Alles bekijken",
  "Show more": "Meer tonen",
  "Show less": "Minder tonen",
  "Load more": "Meer laden",
  "Loading more...": "Meer laden...",
  "End of results": "Einde van resultaten",
  "Search...": "Zoeken...",
  "Search for...": "Zoeken naar...",
  "No search results": "Geen zoekresultaten",
  "Clear search": "Zoekopdracht wissen",
  "Clear all": "Alles wissen",
  "Clear filters": "Filters wissen",
  "Reset filters": "Filters resetten",
  "Apply filters": "Filters toepassen",
  "Filters applied": "Filters toegepast",
  "No filters applied": "Geen filters toegepast",
  "Selected": "Geselecteerd",
  "items selected": "items geselecteerd",
  "Select all": "Alles selecteren",
  "Deselect all": "Alles deselecteren",
  "per page": "per pagina",
  "of": "van",
  "Showing": "Toont",
  "results": "resultaten",
  "First": "Eerste",
  "Last": "Laatste",
  "Page": "Pagina",
  "rows per page": "rijen per pagina",
  
  // === Time-related ===
  "Just now": "Zojuist",
  "moments ago": "een moment geleden",
  "minute ago": "minuut geleden",
  "minutes ago": "minuten geleden",
  "hour ago": "uur geleden",
  "hours ago": "uren geleden",
  "day ago": "dag geleden",
  "days ago": "dagen geleden",
  "week ago": "week geleden",
  "weeks ago": "weken geleden",
  "month ago": "maand geleden",
  "months ago": "maanden geleden",
  "year ago": "jaar geleden",
  "years ago": "jaren geleden",
  
  // === Misc UI ===
  "e.g.": "bijv.",
  "or": "of",
  "and": "en",
  "more": "meer",
  "less": "minder",
  "ago": "geleden",
  "in": "in",
  "at": "om",
  "by": "door",
  "for": "voor",
  "with": "met",
  "from": "van",
  "to": "naar",
  "of": "van",
  "the": "de",
  "a": "een",
  "an": "een",
  "is": "is",
  "are": "zijn",
  "was": "was",
  "not": "niet",
  "yes": "ja",
  "no": "nee",
  "all": "alle",
  "none": "geen",
  "other": "anders",
  "new": "nieuw",
  "old": "oud",
  "total": "totaal",
  "average": "gemiddeld",
  "minimum": "minimum",
  "maximum": "maximum",
  "Microsoft": "Microsoft",
  "Slack": "Slack",
  "Microsoft Teams": "Microsoft Teams",
  "Webhooks": "Webhooks",
  "720p HD": "720p HD",
  "1080p Full HD": "1080p Full HD",
  
  // === Error boundary ===
  "This component encountered an error": "Dit onderdeel ging een fout tegen",
  "Something went wrong": "Er ging iets mis",
  "We encountered an unexpected error": "We kwamen een onverwachte fout tegen",
  "Try again": "Opnieuw proberen",
  "Reload page": "Pagina herladen",
  "Contact support": "Contact opnemen met support",
  "Error details": "Foutdetails",
  "Stack trace": "Stack trace",
  "Copy error details": "Foutdetails kopiëren",
  "Report this error": "Deze fout melden",
  
  // === File/media ===
  "Drop files here": "Bestanden hier neerzetten",
  "or click to browse": "of klik om te bladeren",
  "Drag and drop files here": "Sleep bestanden hierheen",
  "Maximum size:": "Maximale grootte:",
  "Supported formats:": "Ondersteunde formaten:",
  "File name": "Bestandsnaam",
  "File size": "Bestandsgrootte",
  "File type": "Bestandstype",
  "Remove file": "Bestand verwijderen",
  "Preview": "Voorbeeld",
  "Download": "Downloaden",
  
  // === Auth ===
  "Sign In": "Inloggen",
  "Sign Up": "Registreren",
  "Sign Out": "Uitloggen",
  "Log In": "Inloggen",
  "Log Out": "Uitloggen",
  "Forgot password?": "Wachtwoord vergeten?",
  "Reset Password": "Wachtwoord opnieuw instellen",
  "New Password": "Nieuw wachtwoord",
  "Confirm Password": "Wachtwoord bevestigen",
  "Remember me": "Onthoud mij",
  "Stay signed in": "Ingelogd blijven",
  "Continue with Google": "Doorgaan met Google",
  "Continue with Apple": "Doorgaan met Apple",
  "Continue with LinkedIn": "Doorgaan met LinkedIn",
  "Or continue with email": "Of doorgaan met e-mail",
  "Enter your email": "Voer uw e-mail in",
  "Enter your password": "Voer uw wachtwoord in",
  "Email address": "E-mailadres",
  "Password": "Wachtwoord",
  "Checking...": "Controleren...",
  "Signing in...": "Inloggen...",
  "Creating account...": "Account aanmaken...",
  "Sending reset link...": "Resetlink versturen...",
  "Check your email": "Controleer uw e-mail",
  "We've sent you a reset link": "We hebben u een resetlink gestuurd",
  "Link expired": "Link verlopen",
  "Invalid credentials": "Ongeldige inloggegevens",
  "Account not found": "Account niet gevonden",
  "Account already exists": "Account bestaat al",
  "Email already in use": "E-mail al in gebruik",
  "Weak password": "Zwak wachtwoord",
  "Password too short": "Wachtwoord te kort",
  "Passwords do not match": "Wachtwoorden komen niet overeen",
  "Invalid email": "Ongeldig e-mailadres",
  "Email verified": "E-mail geverifieerd",
  "Email not verified": "E-mail niet geverifieerd",
  "Verify your email": "Verifieer uw e-mail",
  "Resend verification email": "Verificatie-e-mail opnieuw versturen",
  "Verification email sent": "Verificatie-e-mail verzonden",
  "Tech Corp": "Tech Corp",
  
  // Extra common phrases from actual keys
  "Currently sharing": "Momenteel delen",
  "Note: Payment processing handled by third-party processors (we do not store full": "Opmerking: Betalingsverwerking wordt afgehandeld door externe verwerkers (wij slaan geen volledige",
  "john@example.com": "jan@voorbeeld.nl",
  "e.g. VP of Engineering, CFO, Head of Product": "bijv. VP of Engineering, CFO, Head of Product",
  "What's driving this hire?": "Wat is de drijfveer van deze aanname?",
  "Candidates": "Kandidaten",
  "Members": "Leden",
  "C-Suite": "C-Suite",
  "Director / VP": "Director / VP",
};

// ============================================================================
// PROCESS ALL NAMESPACES
// ============================================================================
let grandTotal = 0;

function processObj(enObj, nlObj, dict) {
  let count = 0;
  for (const [key, enVal] of Object.entries(enObj)) {
    if (enVal && typeof enVal === 'object' && !Array.isArray(enVal)) {
      if (!nlObj[key] || typeof nlObj[key] !== 'object') nlObj[key] = {};
      count += processObj(enVal, nlObj[key], dict);
    } else if (typeof enVal === 'string' && nlObj[key] === enVal) {
      // Skip technical/branding
      if (enVal.length <= 2) continue;
      if (/^[\d\s.,;:!?%$€£¥#+\-*/=@()\[\]{}|\\<>]+$/.test(enVal)) continue;
      if (/^(https?:\/\/|mailto:|tel:)/.test(enVal)) continue;
      if (/^\{\{.+\}\}$/.test(enVal)) continue;
      
      // Try exact match
      if (dict[enVal]) {
        nlObj[key] = dict[enVal];
        count++;
        continue;
      }
      
      // Try case-insensitive match
      const lower = enVal.toLowerCase();
      for (const [dictKey, dictVal] of Object.entries(dict)) {
        if (dictKey.toLowerCase() === lower) {
          nlObj[key] = dictVal;
          count++;
          break;
        }
      }
    }
  }
  return count;
}

for (const ns of NAMESPACES) {
  const enFile = join(LOCALES, 'en', `${ns}.json`);
  const nlFile = join(LOCALES, 'nl', `${ns}.json`);
  if (!existsSync(enFile) || !existsSync(nlFile)) continue;
  
  const enData = JSON.parse(readFileSync(enFile, 'utf-8'));
  const nlData = JSON.parse(readFileSync(nlFile, 'utf-8'));
  
  const count = processObj(enData, nlData, EN_TO_NL);
  
  if (count > 0) {
    writeFileSync(nlFile, JSON.stringify(nlData, null, 2) + '\n');
    console.log(`✅ ${ns}.json — ${count} translated`);
  }
  grandTotal += count;
}

console.log(`\n🇳🇱 TOTAL: ${grandTotal} Dutch translations applied across all namespaces\n`);
