#!/usr/bin/env node
/**
 * Dutch Deep Translation — Phase 3
 * Handles all remaining untranslated sections in common.json for Dutch (NL)
 * This covers all the unique sentences, UI copy, and page-specific text.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const COMMON_NL = resolve(import.meta.dirname, '../src/i18n/locales/nl/common.json');
const COMMON_EN = resolve(import.meta.dirname, '../src/i18n/locales/en/common.json');

const en = JSON.parse(readFileSync(COMMON_EN, 'utf-8'));
const nl = JSON.parse(readFileSync(COMMON_NL, 'utf-8'));

// Comprehensive NL translation for remaining sections
const NL_DEEP = {
  // ===== text section (privacy policy, pages, etc.) =====
  "text": {
    "privacypolicy": {
      "company": "Bedrijf:",
      "registration": "Registratie:",
      "location": "Locatie:",
      "email": "E-mail:",
      "dataProtectionOfficer": "Functionaris gegevensbescherming:",
      "fullNameEmailAddressPhoneNumber": "Volledige naam, e-mailadres, telefoonnummer",
      "professionalBackgroundCurrentJobTitle": "Professionele achtergrond, huidige functietitel, bedrijf, jaren ervaring",
      "linkedinProfileUrlOptional": "LinkedIn profiel-URL (optioneel)",
      "resumeCvDocuments": "CV-documenten",
      "salaryExpectationsAndCompensationPreferences": "Salarisverwachtingen en compensatievoorkeuren",
      "workPreferencesIncludingRemoteWork": "Werkvoorkeuren inclusief thuiswerken, locatie en bedrijfsgrootte",
      "assessmentScoresAndSkillEvaluations": "Beoordelingsscores en vaardigheidsevaluaties",
      "interviewSchedulingAvailabilityAndCalendarData": "Beschikbaarheid voor gespreksplanning en kalendergegevens",
      "communicationHistoryIncludingMessages": "Communicatiegeschiedenis inclusief berichten, e-mails en gespreksnotities",
      "applicationStatusAndPipelineProgress": "Sollicitatiestatus en pijplijnvoortgang",
      "ipAddressesAndDeviceInformation": "IP-adressen en apparaatinformatie",
      "browserTypeAndOperatingSystem": "Browsertype en besturingssysteem",
      "pageViewsAndNavigationPatterns": "Paginaweergaven en navigatiepatronen",
      "sessionDurationAndFrequency": "Sessieduur en -frequentie",
      "featureUsageAnalytics": "Functiegebruiksanalyse",
      "aiProcessing": "AI-verwerking:",
      "googleGeminiAndOpenaiGptModels": "Google Gemini en OpenAI GPT-modellen — gegevensverwerkingsovereenkomsten aanwezig",
      "providingAndMaintainingOurPlatform": "Het leveren en onderhouden van ons platform",
      "matchingCandidatesWithRelevantJob": "Kandidaten matchen met relevante vacatures",
      "facilitatingCommunicationBetweenCandidates": "Communicatie faciliteren tussen kandidaten en recruiters",
      "conductingAssessmentsAndSkillEvaluations": "Beoordelingen en vaardigheidsevaluaties uitvoeren",
      "processingPaymentsAndSubscriptions": "Betalingen en abonnementen verwerken",
      "sendingServiceRelatedNotifications": "Servicegerelateerde meldingen versturen",
      "improvingOurServicesAndUser": "Onze diensten en gebruikerservaring verbeteren",
      "complyingWithLegalObligations": "Voldoen aan wettelijke verplichtingen",
      "youHaveTheFollowingRights": "U heeft de volgende rechten met betrekking tot uw persoonsgegevens:",
      "rightOfAccessRequestACopy": "Recht op inzage: Een kopie van uw persoonsgegevens opvragen",
      "rightToRectificationCorrectInaccurate": "Recht op rectificatie: Onjuiste gegevens corrigeren",
      "rightToErasureRequestDeletion": "Recht op vergetelheid: Verwijdering van uw gegevens aanvragen",
      "rightToRestrictionOfProcessing": "Recht op beperking van verwerking",
      "rightToDataPortabilityReceive": "Recht op gegevensoverdraagbaarheid: Uw gegevens ontvangen in een overdraagbaar formaat",
      "rightToObjectObjectTo": "Recht op bezwaar: Bezwaar maken tegen verwerking",
      "toExerciseAnyOfThese": "Om een van deze rechten uit te oefenen, neem contact op met onze Functionaris Gegevensbescherming",
      "weImplementAppropriateSecurityMeasures": "Wij treffen passende technische en organisatorische beveiligingsmaatregelen om uw persoonsgegevens te beschermen",
      "encryptionOfDataInTransit": "Versleuteling van gegevens tijdens transport en opslag",
      "regularSecurityAuditsAndPenetration": "Regelmatige beveiligingsaudits en penetratietests",
      "accessControlsAndAuthenticationMechanisms": "Toegangscontroles en authenticatiemechanismen",
      "regularBackupsAndDisasterRecovery": "Regelmatige back-ups en noodherstelplannen",
      "employeeTrainingOnDataProtection": "Training van medewerkers over gegevensbescherming",
    },
    "contractdetailpage": {
      "signContract": "Contract ondertekenen",
      "milestoneStarted": "Mijlpaal gestart!",
      "milestoneSubmittedForReview": "Mijlpaal ingediend ter beoordeling!",
      "milestonePaid": "Mijlpaal betaald!",
      "failedToUpdateMilestone": "Mijlpaal bijwerken mislukt",
      "contractNotFound": "Contract niet gevonden",
      "thisContractDoesNotExist": "Dit contract bestaat niet",
      "backToContracts": "Terug naar contracten",
      "contractDetails": "Contractdetails",
    },
    "admincandidates": {
      "failedToLoadCandidates": "Kandidaten laden mislukt",
      "exportFailed": "Exporteren mislukt",
      "exportedSuccessfully": "Succesvol geëxporteerd",
    },
    "auth": {
      "partnerAccount": "Partneraccount",
      "validatingInviteCode": "Uitnodigingscode valideren…",
      "signInTimedOutPleaseTry": "Inloggen verlopen. Probeer het opnieuw.",
      "signInToYourAccount": "Log in op uw account",
      "dontHaveAnAccountSignUp": "Heeft u nog geen account? Registreren",
      "createYourAccount": "Maak uw account aan",
      "alreadyHaveAnAccountSign": "Heeft u al een account? Inloggen",
      "sendResetLink": "Resetlink versturen",
      "backToSignIn": "Terug naar inloggen",
      "resetYourPassword": "Uw wachtwoord opnieuw instellen",
      "enterYourEmailAndWe": "Voer uw e-mail in en we sturen u een link om uw wachtwoord opnieuw in te stellen",
      "checking": "Controleren...",
    },
    "companyjobsdashboard": {
      "youNeedToBeAssociatedWith": "U moet aan een bedrijf gekoppeld zijn om dit dashboard te openen",
      "newJob": "Nieuwe vacature",
      "pipeline": "Pijplijn",
    },
  },

  // ===== academy section =====
  "academy": {
    "courses": "Cursussen",
    "modules": "Modules",
    "progress": "Voortgang",
    "completionRate": "Voltooiingspercentage",
    "startCourse": "Cursus starten",
    "continueCourse": "Cursus voortzetten",
    "completeCourse": "Cursus voltooien",
    "courseCompleted": "Cursus voltooid!",
    "duration": "Duur",
    "difficulty": "Moeilijkheidsgraad",
    "beginner": "Beginner",
    "intermediate": "Gevorderd",
    "advanced": "Expert",
    "instructor": "Docent",
    "enrolled": "Ingeschreven",
    "students": "Studenten",
    "rating": "Beoordeling",
    "reviews": "Reviews",
    "syllabus": "Leerplan",
    "prerequisites": "Vereisten",
    "learningObjectives": "Leerdoelen",
    "quiz": "Quiz",
    "assignment": "Opdracht",
    "video": "Video",
    "article": "Artikel",
    "lesson": "Les",
    "chapter": "Hoofdstuk",
    "exercise": "Oefening",
    "practice": "Oefenen",
    "exam": "Examen",
    "grade": "Cijfer",
    "pass": "Geslaagd",
    "fail": "Gezakt",
    "retake": "Opnieuw doen",
    "downloadCertificate": "Certificaat downloaden",
    "shareAchievement": "Prestatie delen",
    "nextLesson": "Volgende les",
    "previousLesson": "Vorige les",
    "markAsComplete": "Als voltooid markeren",
    "bookmarkLesson": "Les opslaan als bladwijzer",
    "askQuestion": "Vraag stellen",
    "discussion": "Discussie",
    "notes": "Notities",
    "addNote": "Notitie toevoegen",
    "myLearning": "Mijn leerpad",
    "recommended": "Aanbevolen",
    "popular": "Populair",
    "newest": "Nieuwste",
    "allCourses": "Alle cursussen",
    "myCourses": "Mijn cursussen",
    "inProgress": "Bezig",
    "completed": "Voltooid",
    "notStarted": "Niet gestart",
    "searchCourses": "Cursussen zoeken",
    "filterByCategory": "Filteren op categorie",
    "filterByLevel": "Filteren op niveau",
    "sortBy": "Sorteren op",
    "courseDescription": "Cursusbeschrijving",
    "whatYouWillLearn": "Wat u leert",
    "totalDuration": "Totale duur",
    "lessonsCount": "Aantal lessen",
    "enrollNow": "Nu inschrijven",
    "freeAccess": "Gratis toegang",
    "premiumContent": "Premium inhoud",
    "courseCreated": "Cursus aangemaakt",
    "courseUpdated": "Cursus bijgewerkt",
    "coursePublished": "Cursus gepubliceerd",
    "courseDraft": "Cursus concept",
    "title": "Academie",
    "ongoing": "Lopend",
    "certificate": "Certificaat",
    "hourSpent": "Bestede uur",
    "courseTopic": "Cursusonderwerp",
    "design": "Ontwerp",
    "hoursSpent": "Bestede uren",
  },

  // ===== landing section =====
  "landing": {
    "heroTitle": "Uw carrière verdient een upgrade",
    "heroSubtitle": "Word lid van een exclusief netwerk van toptalent",
    "joinNow": "Nu lid worden",
    "learnMore": "Meer informatie",
    "forTalent": "Voor talent",
    "forCompanies": "Voor bedrijven",
    "forRecruiters": "Voor recruiters",
    "whyJoin": "Waarom lid worden?",
    "exclusiveAccess": "Exclusieve toegang",
    "aiMatching": "AI-matching",
    "careerGrowth": "Carrièregroei",
    "globalNetwork": "Wereldwijd netwerk",
    "trustedBy": "Vertrouwd door",
    "professionals": "professionals",
    "companies": "bedrijven",
    "placements": "plaatsingen",
    "testimonials": "Ervaringen",
    "faq": "Veelgestelde vragen",
    "getStarted": "Aan de slag",
    "contactUs": "Neem contact op",
    "privacyPolicy": "Privacybeleid",
    "termsOfService": "Servicevoorwaarden",
    "allRightsReserved": "Alle rechten voorbehouden",
    "features": "Functies",
    "pricing": "Prijzen",
    "about": "Over ons",
    "signIn": "Inloggen",
    "signUp": "Registreren",
    "memberBenefits": "Ledenvoordelen",
    "careerInsights": "Carrière-inzichten",
    "salaryBenchmarks": "Salarisbenchmarks",
    "interviewPrep": "Sollicitatiegespreksvoorbereiding",
    "resumeReview": "CV-beoordeling",
    "mentorship": "Mentorschap",
    "networking": "Netwerken",
    "jobAlerts": "Vacaturemelding",
    "skillAssessments": "Vaardigheidsbeoordelingen",
    "readyToJoin": "Klaar om lid te worden?",
    "applyNow": "Nu solliciteren",
    "limitedSpots": "Beperkt aantal plaatsen beschikbaar",
    "footer": "Voettekst",
    "copyright": "Auteursrecht",
  },

  // ===== achievements section =====
  "achievements": {
    "achievementHunter": "Prestatieja ger",
    "quantumEnergy": "Quantum Energie",
    "unlockToShowcase": "Ontgrendel prestaties om ze hier te tonen",
    "dailyChallenges": "Dagelijkse uitdagingen",
    "weeklyChallenges": "Wekelijkse uitdagingen",
    "dayStreak": "Dag streak!",
    "currentStreak": "Huidige streak",
    "longestStreak": "Langste streak",
    "totalPoints": "Totale punten",
    "level": "Niveau",
    "nextLevel": "Volgend niveau",
    "pointsToNext": "Punten tot volgend niveau",
    "badges": "Badges",
    "earnedBadges": "Verdiende badges",
    "allBadges": "Alle badges",
    "locked": "Vergrendeld",
    "unlocked": "Ontgrendeld",
    "progress": "Voortgang",
    "completed": "Voltooid",
    "claimReward": "Beloning claimen",
    "rewardClaimed": "Beloning geclaimd!",
    "leaderboard": "Ranglijst",
    "rank": "Positie",
    "thisWeek": "Deze week",
    "allTime": "Aller tijden",
    "yourRank": "Uw positie",
    "topPerformers": "Toppresteerders",
    "challengeComplete": "Uitdaging voltooid!",
    "newAchievement": "Nieuwe prestatie!",
    "streakBonus": "Streakbonus",
    "dailyLogin": "Dagelijkse login",
    "profileComplete": "Profiel compleet",
    "firstApplication": "Eerste sollicitatie",
    "firstInterview": "Eerste gesprek",
    "networkGrowth": "Netwerkgroei",
  },

  // ===== feedbackflow section =====
  "feedbackflow": {
    "title": "Feedback",
    "giveFeedback": "Feedback geven",
    "requestFeedback": "Feedback aanvragen",
    "feedbackReceived": "Ontvangen feedback",
    "feedbackGiven": "Gegeven feedback",
    "anonymous": "Anoniem",
    "named": "Met naam",
    "rating": "Beoordeling",
    "comments": "Opmerkingen",
    "submit": "Indienen",
    "thankYou": "Bedankt voor uw feedback!",
    "feedbackSent": "Feedback verzonden",
    "selectRecipient": "Selecteer ontvanger",
    "selectCategory": "Selecteer categorie",
    "performance": "Prestaties",
    "communication": "Communicatie",
    "teamwork": "Teamwork",
    "leadership": "Leiderschap",
    "technical": "Technisch",
    "general": "Algemeen",
    "strengths": "Sterke punten",
    "areasForImprovement": "Verbeterpunten",
    "overallRating": "Totaalbeoordeling",
    "noFeedbackYet": "Nog geen feedback",
    "requestSent": "Verzoek verzonden",
    "pendingRequests": "Openstaande verzoeken",
    "respondToFeedback": "Reageer op feedback",
    "viewAll": "Alles bekijken",
    "writeFeedback": "Feedback schrijven",
    "shareFeedback": "Deel uw gedachten",
    "optional": "Optioneel",
    "required": "Verplicht",
  },

  // ===== twofactorsettings =====
  "twofactorsettings": {
    "title": "Tweefactorauthenticatie",
    "enable": "2FA inschakelen",
    "disable": "2FA uitschakelen",
    "enabled": "Ingeschakeld",
    "disabled": "Uitgeschakeld",
    "setupInstructions": "Installatie-instructies",
    "scanQRCode": "Scan de QR-code met uw authenticator-app",
    "enterCode": "Voer de verificatiecode in",
    "verificationCode": "Verificatiecode",
    "verify": "Verifiëren",
    "backupCodes": "Back-upcodes",
    "saveBackupCodes": "Bewaar deze back-upcodes op een veilige plek",
    "regenerateBackupCodes": "Back-upcodes opnieuw genereren",
    "twoFactorEnabled": "Tweefactorauthenticatie is ingeschakeld",
    "twoFactorDisabled": "Tweefactorauthenticatie is uitgeschakeld",
    "confirmDisable": "Weet u zeker dat u 2FA wilt uitschakelen?",
    "securityWarning": "Dit maakt uw account minder veilig",
    "authenticatorApp": "Authenticator-app",
    "sms": "SMS",
    "email": "E-mail",
    "preferredMethod": "Voorkeursmethode",
    "lastUsed": "Laatst gebruikt",
    "setupComplete": "Installatie voltooid!",
    "invalidCode": "Ongeldige code",
    "tryAgain": "Probeer het opnieuw",
    "codesRemaining": "Resterende codes",
    "downloadCodes": "Codes downloaden",
    "copyCodes": "Codes kopiëren",
    "copied": "Gekopieerd!",
    "resetMFA": "MFA opnieuw instellen",
    "confirmReset": "Bevestig reset",
  },

  // ===== createtaskdialog =====
  "createtaskdialog": {
    "createTask": "Taak aanmaken",
    "editTask": "Taak bewerken",
    "taskTitle": "Taaktitel",
    "taskDescription": "Taakbeschrijving",
    "assignTo": "Toewijzen aan",
    "dueDate": "Vervaldatum",
    "priority": "Prioriteit",
    "high": "Hoog",
    "medium": "Gemiddeld",
    "low": "Laag",
    "urgent": "Urgent",
    "status": "Status",
    "todo": "Te doen",
    "inProgress": "Bezig",
    "done": "Gereed",
    "blocked": "Geblokkeerd",
    "tags": "Tags",
    "addTag": "Tag toevoegen",
    "attachments": "Bijlagen",
    "addAttachment": "Bijlage toevoegen",
    "comments": "Opmerkingen",
    "addComment": "Opmerking toevoegen",
    "subtasks": "Subtaken",
    "addSubtask": "Subtaak toevoegen",
    "saveTask": "Taak opslaan",
    "deleteTask": "Taak verwijderen",
    "taskCreated": "Taak aangemaakt!",
    "taskUpdated": "Taak bijgewerkt!",
    "taskDeleted": "Taak verwijderd",
    "confirmDelete": "Weet u zeker dat u deze taak wilt verwijderen?",
    "noTasks": "Geen taken",
    "estimate": "Geschatte tijd",
    "reminder": "Herinnering",
    "recurring": "Terugkerend",
    "category": "Categorie",
  },

  // ===== partnerfunnel =====
  "partnerfunnel": {
    "title": "Partnertrechter",
    "stage": "Fase",
    "prospect": "Prospect",
    "qualified": "Gekwalificeerd",
    "proposal": "Voorstel",
    "negotiation": "Onderhandeling",
    "closed": "Gesloten",
    "won": "Gewonnen",
    "lost": "Verloren",
    "stalled": "Stilgevallen",
    "value": "Waarde",
    "probability": "Kans",
    "expectedClose": "Verwachte afsluiting",
    "notes": "Notities",
    "lastContact": "Laatste contact",
    "nextAction": "Volgende actie",
    "addDeal": "Deal toevoegen",
    "dealAdded": "Deal toegevoegd!",
    "moveTo": "Verplaatsen naar",
    "dealValue": "Dealwaarde",
    "totalPipeline": "Totale pijplijn",
    "avgDealSize": "Gem. dealgrootte",
    "conversionRate": "Conversiepercentage",
    "seniorityDirector": "Director / VP",
    "seniorityCSuite": "C-Suite",
    "roleTitlePlaceholder": "bijv. VP of Engineering, CFO, Head of Product",
    "hiringDriver": "Wat drijft deze aanname?",
  },

  // ===== scorecards =====
  "scorecards": {
    "title": "Scorekaarten",
    "createScorecard": "Scorekaart aanmaken",
    "editScorecard": "Scorekaart bewerken",
    "criteria": "Criteria",
    "addCriteria": "Criterium toevoegen",
    "weight": "Gewicht",
    "score": "Score",
    "totalScore": "Totaalscore",
    "notes": "Notities",
    "reviewer": "Beoordelaar",
    "candidate": "Kandidaat",
    "position": "Functie",
    "overall": "Totaal",
    "strengths": "Sterke punten",
    "weaknesses": "Zwakke punten",
    "recommendation": "Aanbeveling",
    "strongHire": "Sterke aanbeveling",
    "hire": "Aannemen",
    "noHire": "Niet aannemen",
    "strongNoHire": "Sterk afwijzen",
    "submitted": "Ingediend",
    "pending": "In behandeling",
    "averageScore": "Gem. score",
    "scorecardTemplate": "Scorekaartsjabloon",
    "useTemplate": "Sjabloon gebruiken",
  },

  // ===== blindSpot =====
  "blindSpot": {
    "title": "Blinde Vlek",
    "description": "Ontdek uw professionele blinde vlekken",
    "startAssessment": "Assessment starten",
    "results": "Resultaten",
    "insights": "Inzichten",
    "categories": "Categorieën",
    "strengths": "Sterke punten",
    "blindSpots": "Blinde vlekken",
    "opportunities": "Kansen",
    "selfAwareness": "Zelfbewustzijn",
    "communication": "Communicatie",
    "leadership": "Leiderschap",
    "technicalSkills": "Technische vaardigheden",
    "emotionalIntelligence": "Emotionele intelligentie",
    "adaptability": "Aanpassingsvermogen",
    "teamwork": "Teamwork",
    "decisionMaking": "Besluitvorming",
    "viewReport": "Rapport bekijken",
    "retakeAssessment": "Assessment opnieuw doen",
  },

  // ===== swipeGame =====
  "swipeGame": {
    "title": "Swipe Game",
    "swipeRight": "Naar rechts swipen om te accepteren",
    "swipeLeft": "Naar links swipen om over te slaan",
    "match": "Match!",
    "noMoreCards": "Geen kaarten meer",
    "preferences": "Voorkeuren",
    "results": "Resultaten",
    "matchRate": "Matchpercentage",
    "totalSwipes": "Totaal geswiped",
    "accepted": "Geaccepteerd",
    "rejected": "Afgewezen",
    "startPlaying": "Spelen starten",
    "nextRound": "Volgende ronde",
    "gameOver": "Spel voorbij",
    "score": "Score",
    "personalityType": "Persoonlijkheidstype",
    "playAgain": "Opnieuw spelen",
  },

  // ===== valuesPoker =====
  "valuesPoker": {
    "title": "Waarden Poker",
    "description": "Ontdek uw kernwaarden",
    "startGame": "Spel starten",
    "round": "Ronde",
    "keepCard": "Kaart houden",
    "discardCard": "Kaart weggooien",
    "topValues": "Topwaarden",
    "results": "Resultaten",
    "yourValues": "Uw waarden",
    "shareResults": "Resultaten delen",
    "playAgain": "Opnieuw spelen",
    "instructions": "Instructies",
    "chooseValues": "Kies de waarden die het meest bij u passen",
    "finalSelection": "Eindselectie",
    "valueRanking": "Waardenrangschikking",
  },

  // ===== communication =====
  "communication": {
    "title": "Communicatie",
    "channels": "Kanalen",
    "directMessages": "Directe berichten",
    "groupChats": "Groepsgesprekken",
    "announcements": "Aankondigingen",
    "newChannel": "Nieuw kanaal",
    "createChannel": "Kanaal aanmaken",
    "channelName": "Kanaalnaam",
    "channelDescription": "Kanaalbeschrijving",
    "members": "Leden",
    "addMember": "Lid toevoegen",
    "removeMember": "Lid verwijderen",
    "leaveChannel": "Kanaal verlaten",
    "muteChannel": "Kanaal dempen",
    "pinMessage": "Bericht vastmaken",
    "unpinMessage": "Bericht losmaken",
    "pinnedMessages": "Vastgepinde berichten",
    "searchMessages": "Berichten zoeken",
    "attachFile": "Bestand bijvoegen",
    "sendMessage": "Bericht versturen",
    "typingIndicator": "is aan het typen...",
    "online": "Online",
    "offline": "Offline",
    "lastSeen": "Laatst gezien",
    "unreadMessages": "Ongelezen berichten",
    "markAsRead": "Als gelezen markeren",
    "replyInThread": "Reageer in thread",
    "reactions": "Reacties",
    "editMessage": "Bericht bewerken",
    "deleteMessage": "Bericht verwijderen",
    "forwardMessage": "Bericht doorsturen",
    "copyMessage": "Bericht kopiëren",
    "reportMessage": "Bericht rapporteren",
  },

  // ===== booking =====
  "booking": {
    "title": "Boeking",
    "bookMeeting": "Vergadering boeken",
    "selectDate": "Datum selecteren",
    "selectTime": "Tijd selecteren",
    "duration": "Duur",
    "minutes": "minuten",
    "hour": "uur",
    "location": "Locatie",
    "virtual": "Virtueel",
    "inPerson": "In persoon",
    "agenda": "Agenda",
    "addAgenda": "Agendapunt toevoegen",
    "confirmed": "Bevestigd",
    "pending": "In behandeling",
    "cancelled": "Geannuleerd",
    "reschedule": "Opnieuw plannen",
    "cancelBooking": "Boeking annuleren",
    "bookingConfirmed": "Boeking bevestigd!",
    "bookingCancelled": "Boeking geannuleerd",
    "noAvailableSlots": "Geen beschikbare tijdslots",
    "selectParticipants": "Deelnemers selecteren",
    "addNotes": "Notities toevoegen",
    "reminderSent": "Herinnering verzonden",
    "timezone": "Tijdzone",
  },

  // ===== whatsAppImport =====
  "whatsAppImport": {
    "title": "WhatsApp Import",
    "importContacts": "Contacten importeren",
    "importMessages": "Berichten importeren",
    "selectFile": "Bestand selecteren",
    "uploading": "Uploaden...",
    "processing": "Verwerken...",
    "imported": "Geïmporteerd",
    "failed": "Mislukt",
    "duplicates": "Duplicaten",
    "skipped": "Overgeslagen",
    "totalContacts": "Totaal contacten",
    "newContacts": "Nieuwe contacten",
    "updatedContacts": "Bijgewerkte contacten",
    "importComplete": "Import voltooid!",
    "importFailed": "Import mislukt",
    "retry": "Opnieuw proberen",
    "cancel": "Annuleren",
    "history": "Importgeschiedenis",
    "lastImport": "Laatste import",
    "mapFields": "Velden toewijzen",
    "preview": "Voorbeeld",
  },

  // ===== feed =====
  "feed": {
    "title": "Tijdlijn",
    "newPost": "Nieuw bericht",
    "createPost": "Bericht maken",
    "shareUpdate": "Deel een update...",
    "photo": "Foto",
    "video": "Video",
    "document": "Document",
    "poll": "Peiling",
    "event": "Evenement",
    "like": "Vind ik leuk",
    "comment": "Reageren",
    "share": "Delen",
    "save": "Opslaan",
    "report": "Rapporteren",
    "delete": "Verwijderen",
    "edit": "Bewerken",
    "comments": "Reacties",
    "likes": "Vind-ik-leuks",
    "shares": "Deelacties",
    "writeComment": "Schrijf een reactie...",
    "reply": "Beantwoorden",
    "loadMore": "Meer laden",
    "noMorePosts": "Geen berichten meer",
    "trending": "Trending",
    "forYou": "Voor u",
    "following": "Volgend",
    "myPosts": "Mijn berichten",
    "emptyFeed": "Uw tijdlijn is leeg",
  },

  // ===== authdiagnostics =====
  "authdiagnostics": {
    "title": "Authenticatiediagnostiek",
    "runDiagnostics": "Diagnostiek uitvoeren",
    "sessionStatus": "Sessiestatus",
    "tokenValid": "Token geldig",
    "tokenExpired": "Token verlopen",
    "refreshToken": "Token vernieuwen",
    "userRole": "Gebruikersrol",
    "permissions": "Rechten",
    "lastLogin": "Laatste login",
    "loginAttempts": "Inlogpogingen",
    "failedAttempts": "Mislukte pogingen",
    "accountLocked": "Account vergrendeld",
    "unlockAccount": "Account ontgrendelen",
    "browserInfo": "Browserinformatie",
    "deviceInfo": "Apparaatinformatie",
    "ipAddress": "IP-adres",
    "sessionExpiry": "Sessievervaltijd",
    "clearSession": "Sessie wissen",
    "forceLogout": "Geforceerd uitloggen",
    "diagnosticsComplete": "Diagnostiek voltooid",
    "noIssuesFound": "Geen problemen gevonden",
    "issuesFound": "Problemen gevonden",
  },

  // ===== referralProgram =====
  "referralProgram": {
    "title": "Verwijzingsprogramma",
    "inviteFriends": "Nodig vrienden uit",
    "yourReferralLink": "Uw verwijzingslink",
    "copyLink": "Link kopiëren",
    "shareVia": "Delen via",
    "totalReferrals": "Totaal verwijzingen",
    "pendingReferrals": "In behandeling",
    "acceptedReferrals": "Geaccepteerd",
    "rewardsEarned": "Verdiende beloningen",
    "howItWorks": "Hoe het werkt",
    "step1": "Deel uw verwijzingslink",
    "step2": "Uw vriend schrijft zich in",
    "step3": "Verdien beloningen",
    "referralHistory": "Verwijzingsgeschiedenis",
    "leaderboard": "Ranglijst",
    "terms": "Voorwaarden",
    "earnRewards": "Verdien beloningen door talent te verwijzen",
    "referralSent": "Verwijzing verzonden!",
  },

  // ===== termsOfService =====
  "termsOfService": {
    "title": "Servicevoorwaarden",
    "lastUpdated": "Laatst bijgewerkt",
    "acceptance": "Acceptatie",
    "eligibility": "Geschiktheid",
    "userAccounts": "Gebruikersaccounts",
    "prohibitedConduct": "Verboden gedrag",
    "intellectualProperty": "Intellectueel eigendom",
    "disclaimer": "Disclaimer",
    "limitation": "Beperking van aansprakelijkheid",
    "termination": "Beëindiging",
    "governingLaw": "Toepasselijk recht",
    "changes": "Wijzigingen",
    "contactUs": "Neem contact op",
    "agreementToTerms": "Door deze dienst te gebruiken stemt u in met deze voorwaarden",
    "privacyLink": "Zie ook ons Privacybeleid",
    "dataProcessing": "Gegevensverwerking",
    "userRights": "Gebruikersrechten",
    "disputeResolution": "Geschilbeslechting",
  },

  // ===== social =====
  "social": {
    "connections": "Connecties",
    "followers": "Volgers",
    "following": "Volgend",
    "connect": "Verbinden",
    "disconnect": "Verbinding verbreken",
    "follow": "Volgen",
    "unfollow": "Ontvolgen",
    "block": "Blokkeren",
    "unblock": "Deblokkeren",
    "mute": "Dempen",
    "unmute": "Ontdempen",
    "report": "Rapporteren",
    "profile": "Profiel",
    "story": "Verhaal",
    "stories": "Verhalen",
    "addStory": "Verhaal toevoegen",
    "viewStory": "Verhaal bekijken",
    "groups": "Groepen",
    "createGroup": "Groep aanmaken",
    "joinGroup": "Groep deelnemen",
    "leaveGroup": "Groep verlaten",
    "events": "Evenementen",
    "createEvent": "Evenement aanmaken",
    "attendEvent": "Evenement bijwonen",
    "interested": "Geïnteresseerd",
    "going": "Gaat",
    "notGoing": "Gaat niet",
    "invite": "Uitnodigen",
    "invitations": "Uitnodigingen",
    "accept": "Accepteren",
    "decline": "Weigeren",
    "pending": "In behandeling",
    "suggested": "Voorgesteld",
    "mutualConnections": "Gemeenschappelijke connecties",
    "networkStrength": "Netwerksterkte",
    "endorsements": "Aanbevelingen",
    "endorse": "Aanbevelen",
    "recommendation": "Aanbeveling",
    "writeRecommendation": "Aanbeveling schrijven",
    "shareProfile": "Profiel delen",
    "publicProfile": "Openbaar profiel",
    "privateProfile": "Privéprofiel",
    "activityFeed": "Activiteitstijdlijn",
  },

  // ===== partner =====
  "partner": {
    "reviewed": "beoordeeld",
    "remainingCount": "{{count}} resterend",
    "searchJobsPlaceholder": "Zoeken op functietitel, bedrijf of locatie...",
    "oneResult": "1 resultaat",
    "resultCount": "{{count}} resultaten",
    "pendingOffer": "Openstaand aanbod",
    "hiringMetrics": "Wervingsmetrieken",
    "activeJobs": "Actieve vacatures",
    "totalApplications": "Totaal sollicitaties",
    "averageTimeToHire": "Gem. tijd tot aanname",
    "placementRate": "Plaatsingspercentage",
    "clientSatisfaction": "Klanttevredenheid",
    "revenueGenerated": "Gegenereerde omzet",
    "topSources": "Topbronnen",
    "conversionFunnel": "Conversietrechter",
  },

  // ==== objectives ====
  "objectives": {
    "title": "Doelstellingen",
    "createObjective": "Doelstelling aanmaken",
    "editObjective": "Doelstelling bewerken",
    "keyResults": "Kernresultaten",
    "addKeyResult": "Kernresultaat toevoegen",
    "progress": "Voortgang",
    "owner": "Eigenaar",
    "dueDate": "Vervaldatum",
    "onTrack": "Op schema",
    "atRisk": "Risicovol",
    "behind": "Achter",
    "completed": "Voltooid",
    "notStarted": "Niet gestart",
    "alignedTo": "Afgestemd op",
    "contributors": "Bijdragers",
    "checkIn": "Inchecken",
    "lastCheckIn": "Laatste incheck",
    "updateProgress": "Voortgang bijwerken",
    "comment": "Opmerking",
    "history": "Geschiedenis",
    "archive": "Archiveren",
    "delete": "Verwijderen",
    "quarter": "Kwartaal",
    "annual": "Jaarlijks",
    "teamObjectives": "Teamdoelstellingen",
    "personalObjectives": "Persoonlijke doelstellingen",
  },

  // ===== uploadmeetingrecording =====
  "uploadmeetingrecording": {
    "title": "Vergaderopname uploaden",
    "uploadRecording": "Opname uploaden",
    "selectFile": "Bestand selecteren",
    "supportedFormats": "Ondersteunde formaten",
    "maxFileSize": "Maximale bestandsgrootte",
    "uploading": "Uploaden...",
    "processing": "Verwerken...",
    "transcribing": "Transcriberen...",
    "uploadComplete": "Upload voltooid!",
    "transcriptionComplete": "Transcriptie voltooid!",
    "viewTranscription": "Transcriptie bekijken",
    "downloadTranscription": "Transcriptie downloaden",
    "meetingTitle": "Vergadertitel",
    "meetingDate": "Vergaderdatum",
    "participants": "Deelnemers",
    "duration": "Duur",
    "summary": "Samenvatting",
    "actionItems": "Actiepunten",
    "keyTopics": "Belangrijkste onderwerpen",
    "sentiment": "Sentiment",
    "speakerBreakdown": "Sprekersverdeling",
    "highlights": "Hoogtepunten",
    "searchTranscript": "Transcript doorzoeken",
    "exportNotes": "Notities exporteren",
    "shareRecording": "Opname delen",
    "deleteRecording": "Opname verwijderen",
    "failedToUpload": "Upload mislukt",
    "retryUpload": "Upload opnieuw proberen",
  },

  // ===== companyPage =====
  "companyPage": {
    "about": "Over",
    "openPositions": "Openstaande vacatures",
    "culture": "Cultuur",
    "benefits": "Secundaire arbeidsvoorwaarden",
    "reviews": "Reviews",
    "photos": "Foto's",
    "headquarters": "Hoofdkantoor",
    "founded": "Opgericht",
    "employees": "Werknemers",
    "industry": "Sector",
    "website": "Website",
    "socialMedia": "Sociale media",
    "techStack": "Tech stack",
    "funding": "Financiering",
    "growthRate": "Groeipercentage",
    "missionStatement": "Missie",
    "vision": "Visie",
    "values": "Waarden",
  },

  // ===== blog =====
  "blog": {
    "title": "Blog",
    "readMore": "Lees meer",
    "publishedOn": "Gepubliceerd op",
    "author": "Auteur",
    "tags": "Tags",
    "categories": "Categorieën",
    "searchPosts": "Berichten zoeken",
    "latestPosts": "Laatste berichten",
    "popularPosts": "Populaire berichten",
    "relatedPosts": "Gerelateerde berichten",
    "comments": "Reacties",
    "leaveComment": "Laat een reactie achter",
    "sharePost": "Bericht delen",
    "readingTime": "Leestijd",
    "tableOfContents": "Inhoudsopgave",
    "newsletter": "Nieuwsbrief",
    "subscribe": "Abonneren",
    "subscribed": "Geabonneerd!",
  },

  // ===== incubator =====
  "incubator": {
    "title": "Incubator",
    "programs": "Programma's",
    "apply": "Solliciteren",
    "startups": "Startups",
    "mentors": "Mentoren",
    "milestones": "Mijlpalen",
    "funding": "Financiering",
    "pitch": "Pitch",
    "demoDay": "Demodag",
    "cohort": "Cohort",
    "progress": "Voortgang",
    "metrics": "Metrieken",
    "team": "Team",
    "product": "Product",
    "market": "Markt",
    "traction": "Tractie",
    "revenue": "Omzet",
    "users": "Gebruikers",
    "investorReady": "Investeerder-klaar",
    "applicationSubmitted": "Aanvraag ingediend",
    "accepted": "Geaccepteerd",
    "rejected": "Afgewezen",
    "graduated": "Afgestudeerd",
    "active": "Actief",
    "alumni": "Alumni",
    "resources": "Bronnen",
    "workshops": "Workshops",
    "networking": "Netwerken",
    "officeHours": "Spreekuur",
  },

  // ===== courseEdit =====
  "courseEdit": {
    "editCourse": "Cursus bewerken",
    "courseTitle": "Cursustitel",
    "courseDescription": "Cursusbeschrijving",
    "category": "Categorie",
    "difficulty": "Moeilijkheidsgraad",
    "thumbnail": "Miniatuurafbeelding",
    "uploadThumbnail": "Miniatuur uploaden",
    "addModule": "Module toevoegen",
    "addLesson": "Les toevoegen",
    "reorderModules": "Modules herordenen",
    "publishCourse": "Cursus publiceren",
    "saveDraft": "Concept opslaan",
    "preview": "Voorbeeld",
    "settings": "Instellingen",
    "pricing": "Prijzen",
    "access": "Toegang",
  },

  // ===== expertMarketplace =====
  "expertMarketplace": {
    "title": "Expertmarktplaats",
    "findExperts": "Experts vinden",
    "becomeExpert": "Word expert",
    "searchExperts": "Experts zoeken",
    "expertise": "Expertise",
    "hourlyRate": "Uurtarief",
    "availability": "Beschikbaarheid",
    "rating": "Beoordeling",
    "reviews": "Reviews",
    "bookSession": "Sessie boeken",
    "sessionBooked": "Sessie geboekt!",
    "topExperts": "Topexperts",
    "categories": "Categorieën",
    "myBookings": "Mijn boekingen",
    "upcomingSessions": "Aankomende sessies",
    "pastSessions": "Eerdere sessies",
    "leaveReview": "Review achterlaten",
    "consultationFee": "Consultatiekosten",
    "responseTime": "Reactietijd",
    "languages": "Talen",
    "verified": "Geverifieerd",
    "featured": "Uitgelicht",
    "trending": "Trending",
  },

  // ===== clubTasks =====
  "clubTasks": {
    "title": "Club Taken",
    "myTasks": "Mijn taken",
    "teamTasks": "Teamtaken",
    "allTasks": "Alle taken",
    "createTask": "Taak aanmaken",
    "taskBoard": "Takenbord",
    "listView": "Lijstweergave",
    "boardView": "Bordweergave",
    "calendarView": "Kalenderweergave",
    "todo": "Te doen",
    "inProgress": "Bezig",
    "review": "Beoordeling",
    "done": "Gereed",
    "overdue": "Achterstallig",
    "dueToday": "Vandaag verlopen",
    "dueSoon": "Binnenkort verlopen",
    "noPriority": "Geen prioriteit",
    "filterTasks": "Taken filteren",
    "sortTasks": "Taken sorteren",
  },

  // ===== accountlinking =====
  "accountlinking": {
    "title": "Account koppelen",
    "linkedAccounts": "Gekoppelde accounts",
    "linkAccount": "Account koppelen",
    "unlinkAccount": "Account ontkoppelen",
    "google": "Google",
    "apple": "Apple",
    "linkedin": "LinkedIn",
    "github": "GitHub",
    "linked": "Gekoppeld",
    "notLinked": "Niet gekoppeld",
    "linkSuccess": "Account gekoppeld!",
    "unlinkSuccess": "Account ontkoppeld",
    "linkFailed": "Koppelen mislukt",
    "confirmUnlink": "Weet u zeker dat u dit account wilt ontkoppelen?",
    "primaryAccount": "Primair account",
    "lastLinked": "Laatst gekoppeld",
    "linkBenefits": "Koppel accounts voor snellere login",
    "securityNote": "U kunt altijd uw primaire e-mail en wachtwoord gebruiken",
  },

  // ===== workspace =====
  "workspace": {
    "title": "Werkruimte",
    "createWorkspace": "Werkruimte aanmaken",
    "editWorkspace": "Werkruimte bewerken",
    "deleteWorkspace": "Werkruimte verwijderen",
    "members": "Leden",
    "inviteMembers": "Leden uitnodigen",
    "settings": "Instellingen",
    "name": "Naam",
    "description": "Beschrijving",
    "logo": "Logo",
    "domain": "Domein",
    "plan": "Plan",
    "billing": "Facturering",
    "integrations": "Integraties",
    "roles": "Rollen",
    "permissions": "Rechten",
  },

  // ===== avatareditor =====
  "avatareditor": {
    "title": "Avatar-editor",
    "uploadPhoto": "Foto uploaden",
    "takePhoto": "Foto maken",
    "removePhoto": "Foto verwijderen",
    "crop": "Bijsnijden",
    "rotate": "Draaien",
    "zoom": "Zoom",
    "apply": "Toepassen",
    "cancel": "Annuleren",
    "preview": "Voorbeeld",
    "chooseFile": "Bestand kiezen",
    "dragAndDrop": "Sleep hier een bestand naartoe",
    "supportedFormats": "Ondersteunde formaten: JPG, PNG",
    "maxSize": "Maximale grootte: 5 MB",
    "photoUpdated": "Foto bijgewerkt!",
    "photoRemoved": "Foto verwijderd",
    "failedToUpdate": "Bijwerken mislukt",
  },

  // === feedbackbutton ===
  "feedbackbutton": {
    "title": "Feedback",
    "sendFeedback": "Feedback versturen",
    "feedbackType": "Feedbacktype",
    "bug": "Bug",
    "feature": "Functieverzoek",
    "improvement": "Verbetering",
    "general": "Algemeen",
    "description": "Beschrijving",
    "screenshot": "Screenshot",
    "attachScreenshot": "Screenshot bijvoegen",
    "priority": "Prioriteit",
    "submit": "Indienen",
    "thankYou": "Bedankt voor uw feedback!",
    "feedbackSent": "Feedback verzonden!",
    "pleaseDescribe": "Beschrijf het probleem of de suggestie",
    "optional": "Optioneel",
    "email": "E-mail voor opvolging",
  },

  // === voice ===
  "voice": {
    "title": "Spraak",
    "startListening": "Luisteren starten",
    "stopListening": "Luisteren stoppen",
    "listening": "Luisteren...",
    "processing": "Verwerken...",
    "tryAgain": "Probeer het opnieuw",
  },

  // === pressureCooker ===
  "pressureCooker": {
    "title": "Pressure Cooker",
    "description": "Intensieve interviewtraining onder druk",
    "startSession": "Sessie starten",
    "timeRemaining": "Resterende tijd",
    "question": "Vraag",
    "answer": "Antwoord",
    "submitAnswer": "Antwoord indienen",
    "nextQuestion": "Volgende vraag",
    "results": "Resultaten",
    "score": "Score",
    "feedback": "Feedback",
    "improvement": "Verbetering",
    "tryAgain": "Opnieuw proberen",
  },

  // === partnerSetup ===
  "partnerSetup": {
    "title": "Partner instellen",
    "companyInfo": "Bedrijfsinformatie",
    "teamSetup": "Teaminstelling",
    "integrations": "Integraties",
    "complete": "Voltooien",
  },

  // === clubPilot ===
  "clubPilot": {
    "title": "Club Pilot",
    "aiAssistant": "AI-assistent",
    "askAnything": "Stel iets",
    "suggestions": "Suggesties",
    "recentChats": "Recente chats",
    "newChat": "Nieuw gesprek",
    "clearHistory": "Geschiedenis wissen",
    "thinking": "Nadenken...",
    "generating": "Genereren...",
    "copyResponse": "Antwoord kopiëren",
    "regenerate": "Opnieuw genereren",
    "feedback": "Feedback",
    "helpful": "Nuttig",
    "notHelpful": "Niet nuttig",
    "reportIssue": "Probleem melden",
    "capabilities": "Mogelijkheden",
    "limitations": "Beperkingen",
    "privacyNote": "Uw gesprekken zijn privé en versleuteld",
    "modelInfo": "Model-informatie",
    "contextLength": "Contextlengte",
    "responseTime": "Reactietijd",
  },

  // === imageEditor ===
  "imageEditor": {
    "title": "Afbeeldingseditor",
    "crop": "Bijsnijden",
    "rotate": "Draaien",
    "flip": "Spiegelen",
    "brightness": "Helderheid",
    "contrast": "Contrast",
    "saturation": "Verzadiging",
  },

  // === timeline ===
  "timeline": {
    "title": "Tijdlijn",
    "events": "Evenementen",
    "milestones": "Mijlpalen",
    "today": "Vandaag",
    "upcoming": "Aankomend",
    "past": "Afgelopen",
    "all": "Alles",
  },

  // === presence ===
  "presence": {
    "online": "Online",
    "offline": "Offline",
    "away": "Afwezig",
  },

  // === legalPages ===
  "legalPages": {
    "privacyPolicy": "Privacybeleid",
    "termsOfService": "Servicevoorwaarden",
    "cookiePolicy": "Cookiebeleid",
    "dataProcessingAgreement": "Gegevensverwerkingsovereenkomst",
    "acceptableUsePolicy": "Acceptabel gebruiksbeleid",
    "disclaimer": "Disclaimer",
    "copyrightNotice": "Auteursrechtmelding",
    "lastUpdated": "Laatst bijgewerkt",
    "effectiveDate": "Ingangsdatum",
    "contactInformation": "Contactinformatie",
    "allRightsReserved": "Alle rechten voorbehouden",
  },

  // === animatedsidebar ===
  "animatedsidebar": {
    "expand": "Uitvouwen",
    "collapse": "Samenvouwen",
    "pin": "Vastmaken",
    "unpin": "Losmaken",
    "favorites": "Favorieten",
    "recent": "Recent",
    "search": "Zoeken",
    "settings": "Instellingen",
  },

  // === referraldialog ===
  "referraldialog": {
    "title": "Verwijzing",
    "referCandidate": "Kandidaat verwijzen",
    "referrerName": "Naam van de verwijzer",
    "referrerEmail": "E-mail van de verwijzer",
    "candidateName": "Naam van de kandidaat",
    "candidateEmail": "E-mail van de kandidaat",
    "position": "Functie",
    "notes": "Notities",
    "submit": "Verwijzing indienen",
    "referralSubmitted": "Verwijzing ingediend!",
    "thankYou": "Bedankt voor uw verwijzing",
    "relationship": "Relatie met kandidaat",
    "recommendation": "Aanbeveling",
  },

  // === kpi ===
  "kpi": {
    "title": "KPI",
    "dashboard": "Dashboard",
    "metrics": "Metrieken",
    "targets": "Doelstellingen",
  },

  // === socialconnections ===
  "socialconnections": {
    "title": "Sociale connecties",
    "myConnections": "Mijn connecties",
    "suggested": "Voorgesteld",
    "pendingRequests": "In afwachting",
    "sentRequests": "Verzonden verzoeken",
    "connect": "Verbinden",
    "connected": "Verbonden",
    "disconnect": "Verbreken",
    "message": "Bericht",
    "viewProfile": "Profiel bekijken",
    "mutualConnections": "Gemeenschappelijke connecties",
    "searchConnections": "Connecties zoeken",
    "noConnections": "Nog geen connecties",
  },

  // === promptinputbox ===
  "promptinputbox": {
    "placeholder": "Stel iets aan Club AI...",
    "send": "Versturen",
    "stop": "Stoppen",
    "attach": "Bijvoegen",
    "voice": "Spraak",
    "clear": "Wissen",
    "newConversation": "Nieuw gesprek",
    "thinking": "Nadenken...",
    "generating": "Genereren...",
    "suggestions": "Suggesties",
    "history": "Geschiedenis",
    "model": "Model",
  },

  // === unifiedusermanagementtsx ===
  "unifiedusermanagementtsx": {
    "title": "Gebruikersbeheer",
    "allUsers": "Alle gebruikers",
    "activeUsers": "Actieve gebruikers",
    "inactiveUsers": "Inactieve gebruikers",
    "suspendedUsers": "Geschorste gebruikers",
    "searchUsers": "Gebruikers zoeken",
    "addUser": "Gebruiker toevoegen",
    "editUser": "Gebruiker bewerken",
    "deleteUser": "Gebruiker verwijderen",
    "role": "Rol",
    "status": "Status",
    "lastActive": "Laatst actief",
    "joinDate": "Aanmelddatum",
    "actions": "Acties",
    "suspendUser": "Gebruiker schorsen",
    "activateUser": "Gebruiker activeren",
    "resetPassword": "Wachtwoord resetten",
    "exportUsers": "Gebruikers exporteren",
    "bulkActions": "Bulkacties",
  },
};

// ============================================================
// Apply translations
// ============================================================
let totalApplied = 0;

function applyTranslations(nlObj, enObj, transObj, path = '') {
  for (const [key, trans] of Object.entries(transObj)) {
    const fullPath = path ? `${path}.${key}` : key;
    
    if (trans && typeof trans === 'object' && !Array.isArray(trans)) {
      if (!nlObj[key]) nlObj[key] = {};
      if (!enObj[key]) continue;
      applyTranslations(nlObj[key], enObj[key], trans, fullPath);
    } else if (typeof trans === 'string') {
      // Only apply if current NL value equals English (untranslated)
      if (enObj && enObj[key] && nlObj[key] === enObj[key]) {
        nlObj[key] = trans;
        totalApplied++;
      }
    }
  }
}

applyTranslations(nl, en, NL_DEEP);

writeFileSync(COMMON_NL, JSON.stringify(nl, null, 2) + '\n');
console.log(`\n✅ Applied ${totalApplied} Dutch translations to common.json\n`);
