import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { CalendarIcon, Plus, Lock, Globe, Bot, Shield } from 'lucide-react';
import { format } from 'date-fns';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

interface CreateMeetingDialogProps {
  trigger?: React.ReactNode;
  onMeetingCreated?: (meeting: any) => void;
}

export function CreateMeetingDialog({ trigger, onMeetingCreated }: CreateMeetingDialogProps) {
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [agenda, setAgenda] = useState('');
  const [date, setDate] = useState<Date>();
  const [time, setTime] = useState('09:00');
  const [duration, setDuration] = useState(30);
  const [allowGuests, setAllowGuests] = useState(false);
  const [requireApproval, setRequireApproval] = useState(false);
  const [accessType, setAccessType] = useState<'invite_only' | 'public' | 'password'>('invite_only');
  const [password, setPassword] = useState('');
  const [maxParticipants, setMaxParticipants] = useState<number | undefined>();
  const [enableNotetaker, setEnableNotetaker] = useState(true);
  const [isCreating, setIsCreating] = useState(false);

  const handleCreate = async () => {
    if (!title || !date) {
      toast.error('Please fill in all required fields');
      return;
    }

    setIsCreating(true);
    try {
      // Combine date and time
      const [hours, minutes] = time.split(':').map(Number);
      const scheduledStart = new Date(date);
      scheduledStart.setHours(hours, minutes, 0, 0);
      
      const scheduledEnd = new Date(scheduledStart);
      scheduledEnd.setMinutes(scheduledEnd.getMinutes() + duration);

      const { data: meeting, error } = await supabase
        .from('meetings')
        .insert([{
          host_id: (await supabase.auth.getUser()).data.user?.id,
          meeting_code: '', // Will be auto-generated by trigger
          title,
          description,
          agenda,
          scheduled_start: scheduledStart.toISOString(),
          scheduled_end: scheduledEnd.toISOString(),
          timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          allow_guests: allowGuests,
          require_approval: requireApproval,
          access_type: accessType,
          meeting_password: accessType === 'password' ? password : null,
          max_participants: maxParticipants,
          enable_notetaker: enableNotetaker,
          settings: {
            duration_minutes: duration
          }
        }])
        .select()
        .single();

      if (error) throw error;

      toast.success('Meeting created successfully');
      onMeetingCreated?.(meeting);
      setOpen(false);
      
      // Reset form
      setTitle('');
      setDescription('');
      setAgenda('');
      setDate(undefined);
      setTime('09:00');
      setDuration(30);
      setAllowGuests(false);
      setRequireApproval(false);
      setAccessType('invite_only');
      setPassword('');
      setMaxParticipants(undefined);
    } catch (error: any) {
      console.error('Error creating meeting:', error);
      toast.error(error.message || 'Failed to create meeting');
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || (
          <Button className="gap-2">
            <Plus className="h-4 w-4" />
            Schedule Meeting
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Schedule New Meeting</DialogTitle>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Basic Info */}
          <div className="space-y-4">
            <div>
              <Label htmlFor="title">Meeting Title *</Label>
              <Input
                id="title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="e.g., Weekly Team Sync"
              />
            </div>

            <div>
              <Label htmlFor="description">Description</Label>
              <Textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="What's this meeting about?"
                rows={3}
              />
            </div>

            <div>
              <Label htmlFor="agenda">Agenda</Label>
              <Textarea
                id="agenda"
                value={agenda}
                onChange={(e) => setAgenda(e.target.value)}
                placeholder="Meeting agenda and topics"
                rows={2}
              />
            </div>
          </div>

          {/* Date & Time */}
          <div className="grid grid-cols-3 gap-4">
            <div className="col-span-2">
              <Label>Date *</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    className={cn(
                      "w-full justify-start text-left font-normal",
                      !date && "text-muted-foreground"
                    )}
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {date ? format(date, "PPP") : "Pick a date"}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={date}
                    onSelect={setDate}
                    disabled={(date) => date < new Date(new Date().setHours(0, 0, 0, 0))}
                  />
                </PopoverContent>
              </Popover>
            </div>

            <div>
              <Label htmlFor="time">Time</Label>
              <Input
                id="time"
                type="time"
                value={time}
                onChange={(e) => setTime(e.target.value)}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="duration">Duration (minutes)</Label>
              <Select value={duration.toString()} onValueChange={(v) => setDuration(parseInt(v))}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="15">15 minutes</SelectItem>
                  <SelectItem value="30">30 minutes</SelectItem>
                  <SelectItem value="45">45 minutes</SelectItem>
                  <SelectItem value="60">1 hour</SelectItem>
                  <SelectItem value="90">1.5 hours</SelectItem>
                  <SelectItem value="120">2 hours</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label htmlFor="max-participants">Max Participants</Label>
              <Input
                id="max-participants"
                type="number"
                min="2"
                value={maxParticipants || ''}
                onChange={(e) => setMaxParticipants(e.target.value ? parseInt(e.target.value) : undefined)}
                placeholder="Unlimited"
              />
            </div>
          </div>

          {/* AI Notetaker */}
          <div className="space-y-4 p-4 rounded-lg bg-muted/50">
            <h4 className="font-semibold flex items-center gap-2">
              <Bot className="h-4 w-4" />
              AI Assistant
            </h4>
            
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <Label>Club AI Notetaker</Label>
                <p className="text-xs text-muted-foreground">
                  AI bot will join, record, transcribe, and generate meeting insights
                </p>
              </div>
              <Switch
                checked={enableNotetaker}
                onCheckedChange={setEnableNotetaker}
              />
            </div>
          </div>

          {/* Access Settings */}
          <div className="space-y-4 p-4 rounded-lg bg-muted/50">
            <h4 className="font-semibold flex items-center gap-2">
              <Shield className="h-4 w-4" />
              Access & Privacy
            </h4>

            <div>
              <Label>Access Type</Label>
              <Select value={accessType} onValueChange={(v: any) => setAccessType(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="invite_only">
                    <div className="flex items-center gap-2">
                      <Lock className="h-4 w-4" />
                      Invite Only
                    </div>
                  </SelectItem>
                  <SelectItem value="public">
                    <div className="flex items-center gap-2">
                      <Globe className="h-4 w-4" />
                      Public (Anyone with link)
                    </div>
                  </SelectItem>
                  <SelectItem value="password">
                    <div className="flex items-center gap-2">
                      <Lock className="h-4 w-4" />
                      Password Protected
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            {accessType === 'password' && (
              <div>
                <Label htmlFor="password">Meeting Password</Label>
                <Input
                  id="password"
                  type="text"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Enter password"
                />
              </div>
            )}

            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <Label>Allow Non-Members</Label>
                <p className="text-xs text-muted-foreground">
                  Let guests join without a Quantum Club account
                </p>
              </div>
              <Switch
                checked={allowGuests}
                onCheckedChange={setAllowGuests}
              />
            </div>

            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <Label>Require Approval</Label>
                <p className="text-xs text-muted-foreground">
                  Participants must request to join
                </p>
              </div>
              <Switch
                checked={requireApproval}
                onCheckedChange={setRequireApproval}
              />
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-4">
            <Button
              variant="outline"
              onClick={() => setOpen(false)}
              className="flex-1"
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreate}
              disabled={isCreating || !title || !date}
              className="flex-1"
            >
              {isCreating ? 'Creating...' : 'Create Meeting'}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}