import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { FileText, Search, Download, Plus, Clock, CheckCircle2, XCircle } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AppLayout } from "@/components/AppLayout";

interface AuditRequest {
  id: string;
  request_number: string;
  audit_type: string;
  audit_scope: string;
  audit_purpose: string;
  requester_name: string;
  requester_email: string;
  company_id: string | null;
  status: string;
  priority: string;
  due_date: string | null;
  requested_documents: string[] | null;
  created_at: string;
  updated_at: string;
}

export default function AuditRequestsPage() {
  const [requests, setRequests] = useState<AuditRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const { toast } = useToast();

  useEffect(() => {
    loadAuditRequests();
  }, []);

  const loadAuditRequests = async () => {
    try {
      const { data, error } = await supabase
        .from("audit_requests")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      setRequests(data || []);
    } catch (error) {
      console.error("Error loading audit requests:", error);
      toast({
        title: "Error",
        description: "Failed to load audit requests",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const createAuditRequest = async (formData: any) => {
    try {
      const { error } = await supabase.from("audit_requests").insert([
        {
          request_number: '', // Auto-generated by trigger
          audit_type: formData.audit_type,
          audit_scope: formData.audit_scope,
          audit_purpose: formData.audit_purpose,
          requester_name: formData.requester_name,
          requester_email: formData.requester_email,
          priority: formData.priority,
          due_date: formData.due_date,
          requested_documents: formData.requested_documents?.split(",").map((d: string) => d.trim()),
          status: "pending",
        },
      ]);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Audit request created successfully",
      });

      loadAuditRequests();
    } catch (error) {
      console.error("Error creating audit request:", error);
      toast({
        title: "Error",
        description: "Failed to create audit request",
        variant: "destructive",
      });
    }
  };

  const updateRequestStatus = async (id: string, status: string) => {
    try {
      const { error } = await supabase
        .from("audit_requests")
        .update({ status })
        .eq("id", id);

      if (error) throw error;

      toast({
        title: "Success",
        description: `Request marked as ${status}`,
      });

      loadAuditRequests();
    } catch (error) {
      console.error("Error updating status:", error);
      toast({
        title: "Error",
        description: "Failed to update request status",
        variant: "destructive",
      });
    }
  };

  const getStatusBadge = (status: string) => {
    const styles = {
      pending: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
      in_progress: "bg-blue-500/10 text-blue-500 border-blue-500/20",
      completed: "bg-green-500/10 text-green-500 border-green-500/20",
      rejected: "bg-red-500/10 text-red-500 border-red-500/20",
    };

    return (
      <Badge className={styles[status as keyof typeof styles] || ""}>
        {status.replace("_", " ")}
      </Badge>
    );
  };

  const getPriorityBadge = (priority: string) => {
    const styles = {
      low: "bg-gray-500/10 text-gray-500 border-gray-500/20",
      medium: "bg-orange-500/10 text-orange-500 border-orange-500/20",
      high: "bg-red-500/10 text-red-500 border-red-500/20",
      urgent: "bg-purple-500/10 text-purple-500 border-purple-500/20",
    };

    return (
      <Badge className={styles[priority as keyof typeof styles] || ""}>
        {priority}
      </Badge>
    );
  };

  const filteredRequests = requests.filter((request) => {
    const matchesSearch =
      request.request_number.toLowerCase().includes(searchTerm.toLowerCase()) ||
      request.requester_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      request.audit_type.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesStatus = statusFilter === "all" || request.status === statusFilter;

    return matchesSearch && matchesStatus;
  });

  const stats = {
    total: requests.length,
    pending: requests.filter((r) => r.status === "pending").length,
    in_progress: requests.filter((r) => r.status === "in_progress").length,
    completed: requests.filter((r) => r.status === "completed").length,
  };

  return (
    <AppLayout>
      <div className="container mx-auto p-6 space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-foreground">Audit Requests</h1>
            <p className="text-muted-foreground mt-1">
              Manage customer audit requests and compliance documentation
            </p>
          </div>
          <CreateAuditRequestDialog onSubmit={createAuditRequest} />
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium text-muted-foreground">
                Total Requests
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-foreground">{stats.total}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <Clock className="h-4 w-4 text-yellow-500" />
                Pending
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-foreground">{stats.pending}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <FileText className="h-4 w-4 text-blue-500" />
                In Progress
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-foreground">{stats.in_progress}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-500" />
                Completed
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-foreground">{stats.completed}</div>
            </CardContent>
          </Card>
        </div>

        {/* Filters */}
        <Card>
          <CardContent className="pt-6">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search by request number, requester, or audit type..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10"
                />
              </div>
              <Select value={statusFilter} onValueChange={setStatusFilter}>
                <SelectTrigger className="w-full md:w-[200px]">
                  <SelectValue placeholder="Filter by status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Statuses</SelectItem>
                  <SelectItem value="pending">Pending</SelectItem>
                  <SelectItem value="in_progress">In Progress</SelectItem>
                  <SelectItem value="completed">Completed</SelectItem>
                  <SelectItem value="rejected">Rejected</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        {/* Requests List */}
        <div className="space-y-4">
          {loading ? (
            <Card>
              <CardContent className="py-12 text-center text-muted-foreground">
                Loading audit requests...
              </CardContent>
            </Card>
          ) : filteredRequests.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center text-muted-foreground">
                No audit requests found
              </CardContent>
            </Card>
          ) : (
            filteredRequests.map((request) => (
              <Card key={request.id}>
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <CardTitle className="text-lg">{request.request_number}</CardTitle>
                        {getStatusBadge(request.status)}
                        {getPriorityBadge(request.priority)}
                      </div>
                      <CardDescription>
                        {request.audit_type} - {request.audit_scope}
                      </CardDescription>
                    </div>
                    <div className="flex gap-2">
                      {request.status === "pending" && (
                        <>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => updateRequestStatus(request.id, "in_progress")}
                          >
                            Start Review
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => updateRequestStatus(request.id, "rejected")}
                          >
                            Reject
                          </Button>
                        </>
                      )}
                      {request.status === "in_progress" && (
                        <Button
                          size="sm"
                          onClick={() => updateRequestStatus(request.id, "completed")}
                        >
                          Mark Complete
                        </Button>
                      )}
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                    <div>
                      <p className="text-muted-foreground">Requester</p>
                      <p className="font-medium text-foreground">
                        {request.requester_name} ({request.requester_email})
                      </p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Due Date</p>
                      <p className="font-medium text-foreground">
                        {request.due_date
                          ? new Date(request.due_date).toLocaleDateString()
                          : "Not set"}
                      </p>
                    </div>
                    <div className="md:col-span-2">
                      <p className="text-muted-foreground">Purpose</p>
                      <p className="font-medium text-foreground">{request.audit_purpose}</p>
                    </div>
                    {request.requested_documents && request.requested_documents.length > 0 && (
                      <div className="md:col-span-2">
                        <p className="text-muted-foreground mb-2">Requested Documents</p>
                        <div className="flex flex-wrap gap-2">
                          {request.requested_documents.map((doc, idx) => (
                            <Badge key={idx} variant="outline">
                              {doc}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>
      </div>
    </AppLayout>
  );
}

function CreateAuditRequestDialog({ onSubmit }: { onSubmit: (data: any) => void }) {
  const [open, setOpen] = useState(false);
  const [formData, setFormData] = useState({
    audit_type: "",
    audit_scope: "",
    audit_purpose: "",
    requester_name: "",
    requester_email: "",
    priority: "medium",
    due_date: "",
    requested_documents: "",
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(formData);
    setOpen(false);
    setFormData({
      audit_type: "",
      audit_scope: "",
      audit_purpose: "",
      requester_name: "",
      requester_email: "",
      priority: "medium",
      due_date: "",
      requested_documents: "",
    });
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="h-4 w-4 mr-2" />
          New Request
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Create Audit Request</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="audit_type">Audit Type</Label>
              <Select
                value={formData.audit_type}
                onValueChange={(value) => setFormData({ ...formData, audit_type: value })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="SOC 2">SOC 2</SelectItem>
                  <SelectItem value="ISO 27001">ISO 27001</SelectItem>
                  <SelectItem value="GDPR">GDPR</SelectItem>
                  <SelectItem value="HIPAA">HIPAA</SelectItem>
                  <SelectItem value="Internal">Internal</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="priority">Priority</Label>
              <Select
                value={formData.priority}
                onValueChange={(value) => setFormData({ ...formData, priority: value })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select priority" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">Low</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="urgent">Urgent</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="audit_scope">Audit Scope</Label>
            <Input
              id="audit_scope"
              value={formData.audit_scope}
              onChange={(e) => setFormData({ ...formData, audit_scope: e.target.value })}
              placeholder="e.g., Security controls, Data processing"
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="audit_purpose">Audit Purpose</Label>
            <Textarea
              id="audit_purpose"
              value={formData.audit_purpose}
              onChange={(e) => setFormData({ ...formData, audit_purpose: e.target.value })}
              placeholder="Describe the purpose of this audit..."
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="requester_name">Requester Name</Label>
              <Input
                id="requester_name"
                value={formData.requester_name}
                onChange={(e) => setFormData({ ...formData, requester_name: e.target.value })}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="requester_email">Requester Email</Label>
              <Input
                id="requester_email"
                type="email"
                value={formData.requester_email}
                onChange={(e) => setFormData({ ...formData, requester_email: e.target.value })}
                required
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="due_date">Due Date</Label>
            <Input
              id="due_date"
              type="date"
              value={formData.due_date}
              onChange={(e) => setFormData({ ...formData, due_date: e.target.value })}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="requested_documents">Requested Documents (comma-separated)</Label>
            <Textarea
              id="requested_documents"
              value={formData.requested_documents}
              onChange={(e) => setFormData({ ...formData, requested_documents: e.target.value })}
              placeholder="e.g., Security policies, Incident response plan, Access logs"
            />
          </div>

          <div className="flex justify-end gap-2">
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button type="submit">Create Request</Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
