-- Fix data.sql export: avoid format() variadic argument limit (>100)

CREATE OR REPLACE FUNCTION public.tqc_generate_data_dump()
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  out text := '';
  v_schema_name text;
  v_table_name text;
  cols text;
  values_expr text;
  rows_text text;
  rows_sql text;
  fq_table_ident text;
BEGIN
  out := out || '-- data.sql\n';
  out := out || '-- Generated by backend data-dump\n';
  out := out || '-- Run AFTER schema.sql\n\n';

  out := out || 'BEGIN;\n';

  -- Disable triggers to tolerate FK ordering/cycles
  FOR v_schema_name, v_table_name IN
    SELECT t.schema_name, t.table_name FROM public.tqc__list_user_tables() t
  LOOP
    out := out || format('ALTER TABLE %I.%I DISABLE TRIGGER ALL;\n', v_schema_name, v_table_name);
  END LOOP;
  out := out || E'\n';

  FOR v_schema_name, v_table_name IN
    SELECT t.schema_name, t.table_name FROM public.tqc__list_user_tables() t
  LOOP
    -- Precompute fully-qualified identifier once for string concatenation
    fq_table_ident := quote_ident(v_schema_name) || '.' || quote_ident(v_table_name);

    SELECT string_agg(format('%I', c.column_name), ', ' ORDER BY c.ordinal_position)
      INTO cols
    FROM information_schema.columns c
    WHERE c.table_schema = v_schema_name AND c.table_name = v_table_name;

    SELECT string_agg(format('quote_nullable(%I)', c.column_name), ' || '', '' || ' ORDER BY c.ordinal_position)
      INTO values_expr
    FROM information_schema.columns c
    WHERE c.table_schema = v_schema_name AND c.table_name = v_table_name;

    out := out || format('-- Data: %I.%I\n', v_schema_name, v_table_name);

    -- Build INSERT statements WITHOUT nested format() calls (prevents 100-argument limit)
    rows_sql :=
      'SELECT string_agg(' ||
        quote_literal('INSERT INTO ' || fq_table_ident || ' (' || cols || ') OVERRIDING SYSTEM VALUE VALUES (') ||
        ' || ' || values_expr ||
        ' || ' || quote_literal(');') ||
      ', E''\n'') ' ||
      'FROM ' || fq_table_ident;

    EXECUTE rows_sql INTO rows_text;

    IF rows_text IS NOT NULL AND length(rows_text) > 0 THEN
      out := out || rows_text || E'\n\n';
    ELSE
      out := out || E'-- (no rows)\n\n';
    END IF;
  END LOOP;

  FOR v_schema_name, v_table_name IN
    SELECT t.schema_name, t.table_name FROM public.tqc__list_user_tables() t
  LOOP
    out := out || format('ALTER TABLE %I.%I ENABLE TRIGGER ALL;\n', v_schema_name, v_table_name);
  END LOOP;

  out := out || 'COMMIT;\n';

  RETURN out;
END;
$function$;
