-- Fix exports: exclude system schemas and remove ambiguous identifiers

CREATE OR REPLACE FUNCTION public.tqc__list_user_schemas()
RETURNS TABLE(schema_name text)
LANGUAGE sql
STABLE
SET search_path TO 'public', 'pg_catalog'
AS $function$
  SELECT nspname::text AS schema_name
  FROM pg_namespace
  WHERE nspname NOT IN (
    'pg_catalog','information_schema',
    'auth','storage','realtime','supabase_functions','vault',
    -- managed/extension schemas that should never be exported
    'cron','extensions','net','graphql','graphql_public'
  )
    AND nspname NOT LIKE 'pg_toast%'
    AND nspname NOT LIKE 'pg_temp%'
    AND nspname NOT LIKE 'supabase_%'
  ORDER BY 1;
$function$;

CREATE OR REPLACE FUNCTION public.tqc__list_user_tables()
RETURNS TABLE(schema_name text, table_name text)
LANGUAGE sql
STABLE
SET search_path TO 'public', 'pg_catalog'
AS $function$
  SELECT n.nspname::text AS schema_name,
         c.relname::text AS table_name
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind = 'r'
    AND n.nspname IN (SELECT s.schema_name FROM public.tqc__list_user_schemas() s)
  ORDER BY n.nspname, c.relname;
$function$;

CREATE OR REPLACE FUNCTION public.tqc_generate_schema_dump()
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  out text := '';
  s record;
  r record;
  v_schema_name text;
  v_table_name text;
BEGIN
  out := out || '-- schema.sql\n';
  out := out || '-- Generated by backend schema-dump\n';
  out := out || '-- Run on an empty database.\n\n';

  -- Schemas
  FOR s IN SELECT us.schema_name FROM public.tqc__list_user_schemas() us LOOP
    out := out || format('CREATE SCHEMA IF NOT EXISTS %I;\n', s.schema_name);
  END LOOP;
  out := out || E'\n';

  -- Enum types
  FOR r IN
    SELECT n.nspname AS schema_name,
           t.typname AS type_name,
           array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    JOIN pg_enum e ON e.enumtypid = t.oid
    WHERE n.nspname IN (SELECT us.schema_name FROM public.tqc__list_user_schemas() us)
    GROUP BY 1,2
    ORDER BY 1,2
  LOOP
    out := out || format(
      'CREATE TYPE %I.%I AS ENUM (%s);\n',
      r.schema_name,
      r.type_name,
      (SELECT string_agg(quote_literal(x), ', ') FROM unnest(r.labels) AS x)
    );
  END LOOP;
  out := out || E'\n';

  -- Sequences
  FOR r IN
    SELECT n.nspname AS schema_name,
           c.relname AS sequence_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'S'
      AND n.nspname IN (SELECT us.schema_name FROM public.tqc__list_user_schemas() us)
    ORDER BY 1,2
  LOOP
    out := out || format('CREATE SEQUENCE IF NOT EXISTS %I.%I;\n', r.schema_name, r.sequence_name);
  END LOOP;
  out := out || E'\n';

  -- Tables (columns only)
  FOR v_schema_name, v_table_name IN
    SELECT t.schema_name, t.table_name FROM public.tqc__list_user_tables() t
  LOOP
    out := out || format('-- Table: %I.%I\n', v_schema_name, v_table_name);
    out := out || format('CREATE TABLE IF NOT EXISTS %I.%I (\n', v_schema_name, v_table_name);

    out := out || (
      WITH tbl AS (
        SELECT c.oid AS table_oid
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = v_schema_name AND c.relname = v_table_name
      )
      SELECT string_agg(col_line, E',\n')
      FROM (
        SELECT
          format(
            '  %I %s%s%s%s',
            a.attname,
            format_type(a.atttypid, a.atttypmod),
            CASE
              WHEN a.attidentity IN ('a','d') THEN
                CASE WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY' ELSE ' GENERATED BY DEFAULT AS IDENTITY' END
              ELSE ''
            END,
            CASE
              WHEN ad.adbin IS NOT NULL AND a.attidentity = '' THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
              ELSE ''
            END,
            CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END
          ) AS col_line
        FROM tbl
        JOIN pg_attribute a ON a.attrelid = tbl.table_oid
        LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
        WHERE a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum
      ) cols
    );

    out := out || E'\n);\n\n';
  END LOOP;

  -- Constraints
  out := out || '-- Constraints\n';
  FOR r IN
    SELECT n.nspname AS schema_name,
           c.relname AS table_name,
           con.conname,
           pg_get_constraintdef(con.oid, true) AS condef,
           con.contype
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname IN (SELECT us.schema_name FROM public.tqc__list_user_schemas() us)
      AND c.relkind = 'r'
    ORDER BY n.nspname, c.relname,
      CASE con.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'f' THEN 3 WHEN 'c' THEN 4 ELSE 9 END,
      con.conname
  LOOP
    out := out || format('ALTER TABLE %I.%I ADD CONSTRAINT %I %s;\n', r.schema_name, r.table_name, r.conname, r.condef);
  END LOOP;
  out := out || E'\n';

  -- Indexes (excluding constraint-backed)
  out := out || '-- Indexes\n';
  FOR r IN
    SELECT n.nspname AS schema_name,
           t.relname AS table_name,
           i.relname AS index_name,
           pg_get_indexdef(i.oid) AS indexdef
    FROM pg_index ix
    JOIN pg_class i ON i.oid = ix.indexrelid
    JOIN pg_class t ON t.oid = ix.indrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    LEFT JOIN pg_constraint con ON con.conindid = i.oid
    WHERE con.oid IS NULL
      AND n.nspname IN (SELECT us.schema_name FROM public.tqc__list_user_schemas() us)
    ORDER BY 1,2,3
  LOOP
    out := out || r.indexdef || ';\n';
  END LOOP;
  out := out || E'\n';

  -- Triggers (skip internal triggers)
  out := out || '-- Triggers\n';
  FOR r IN
    SELECT n.nspname AS schema_name,
           c.relname AS table_name,
           tg.tgname AS trigger_name,
           pg_get_triggerdef(tg.oid, true) AS triggerdef
    FROM pg_trigger tg
    JOIN pg_class c ON c.oid = tg.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE NOT tg.tgisinternal
      AND n.nspname IN (SELECT us.schema_name FROM public.tqc__list_user_schemas() us)
    ORDER BY 1,2,3
  LOOP
    out := out || r.triggerdef || ';\n';
  END LOOP;

  RETURN out;
END;
$function$;

CREATE OR REPLACE FUNCTION public.tqc_generate_data_dump()
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  out text := '';
  v_schema_name text;
  v_table_name text;
  cols text;
  values_expr text;
  rows_text text;
  rows_sql text;
BEGIN
  out := out || '-- data.sql\n';
  out := out || '-- Generated by backend data-dump\n';
  out := out || '-- Run AFTER schema.sql\n\n';

  out := out || 'BEGIN;\n';

  -- Disable triggers to tolerate FK ordering/cycles
  FOR v_schema_name, v_table_name IN
    SELECT t.schema_name, t.table_name FROM public.tqc__list_user_tables() t
  LOOP
    out := out || format('ALTER TABLE %I.%I DISABLE TRIGGER ALL;\n', v_schema_name, v_table_name);
  END LOOP;
  out := out || E'\n';

  FOR v_schema_name, v_table_name IN
    SELECT t.schema_name, t.table_name FROM public.tqc__list_user_tables() t
  LOOP
    SELECT string_agg(format('%I', c.column_name), ', ' ORDER BY c.ordinal_position)
      INTO cols
    FROM information_schema.columns c
    WHERE c.table_schema = v_schema_name AND c.table_name = v_table_name;

    SELECT string_agg(format('quote_nullable(%I)', c.column_name), ' || '', '' || ' ORDER BY c.ordinal_position)
      INTO values_expr
    FROM information_schema.columns c
    WHERE c.table_schema = v_schema_name AND c.table_name = v_table_name;

    out := out || format('-- Data: %I.%I\n', v_schema_name, v_table_name);

    rows_sql := format(
      $q$
      SELECT string_agg(
        format('INSERT INTO %I.%I (%s) OVERRIDING SYSTEM VALUE VALUES (%s);', %s),
        E'\n'
      )
      FROM %I.%I
      $q$,
      v_schema_name,
      v_table_name,
      cols,
      '%s',
      values_expr,
      v_schema_name,
      v_table_name
    );

    rows_sql := replace(rows_sql, '%s', values_expr);

    EXECUTE rows_sql INTO rows_text;

    IF rows_text IS NOT NULL AND length(rows_text) > 0 THEN
      out := out || rows_text || E'\n\n';
    ELSE
      out := out || E'-- (no rows)\n\n';
    END IF;
  END LOOP;

  FOR v_schema_name, v_table_name IN
    SELECT t.schema_name, t.table_name FROM public.tqc__list_user_tables() t
  LOOP
    out := out || format('ALTER TABLE %I.%I ENABLE TRIGGER ALL;\n', v_schema_name, v_table_name);
  END LOOP;

  out := out || 'COMMIT;\n';

  RETURN out;
END;
$function$;
