-- Recruitment Engine V2 Tables

-- 1. Project Configs (The Brain)
-- Stores the JITC configuration for a specific Job.
CREATE TABLE IF NOT EXISTS public.recruitment_project_configs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID REFERENCES public.jobs(id) ON DELETE CASCADE,
    version INT DEFAULT 1,
    is_active BOOLEAN DEFAULT true,
    config JSONB NOT NULL, -- The Project Config Schema
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    parent_config_id UUID REFERENCES public.recruitment_project_configs(id)
);

-- 2. Search Queue (The Harvester Orchestrator)
-- Stores individual search tasks generated by the Strategy Agent.
CREATE TABLE IF NOT EXISTS public.recruitment_search_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_config_id UUID REFERENCES public.recruitment_project_configs(id),
    strategy_name TEXT, -- e.g., 'Competitor Poach', 'Title Broadcast'
    query_payload JSONB, -- { "query": "...", "platform": "linkedin" }
    status TEXT DEFAULT 'pending', -- pending, processing, completed, failed
    priority INT DEFAULT 1,
    external_source TEXT, -- 'linkedin', 'google', 'github'
    result_count INT DEFAULT 0,
    error_log TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    processed_at TIMESTAMP WITH TIME ZONE
);

-- 3. Candidate Scores (The Analyzer Result)
-- Stores the Tier 1 & Tier 2 analysis results for a candidate-project pair.
CREATE TABLE IF NOT EXISTS public.recruitment_candidate_scores (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    candidate_id UUID REFERENCES public.candidate_profiles(id) ON DELETE CASCADE,
    project_config_id UUID REFERENCES public.recruitment_project_configs(id),
    
    total_score FLOAT, -- 0-100
    tier_1_verdict TEXT, -- 'pass' or 'reject'
    tier_2_analysis JSONB, -- { "evidence": [...], "risks": [...], "interview_questions": [...] }
    
    human_feedback TEXT, -- 'approve', 'reject', 'maybe'
    human_notes TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE(candidate_id, project_config_id)
);

-- 4. Enable RLS
ALTER TABLE public.recruitment_project_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recruitment_search_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recruitment_candidate_scores ENABLE ROW LEVEL SECURITY;

-- 5. Policies (Authenticated users default)
-- In a real prod environment, this should be stricter (e.g. only company members of the job).
-- But for this OS, we assume authenticated users have access.

-- Configs
CREATE POLICY "Enable read/write for authenticated users on configs" 
ON public.recruitment_project_configs FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Search Queue
CREATE POLICY "Enable read/write for authenticated users on search_queue" 
ON public.recruitment_search_queue FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Scores
CREATE POLICY "Enable read/write for authenticated users on candidate_scores" 
ON public.recruitment_candidate_scores FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 6. Add namespace support to embeddings
-- We add it to intelligence_embeddings as the primary vector store for this engine.
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'intelligence_embeddings' AND column_name = 'vector_namespace') THEN
        ALTER TABLE public.intelligence_embeddings ADD COLUMN vector_namespace TEXT;
        CREATE INDEX IF NOT EXISTS idx_intelligence_embeddings_namespace ON public.intelligence_embeddings(vector_namespace);
    END IF;
END $$;

-- 7. Add Missing Indexes (Performance)
CREATE INDEX IF NOT EXISTS idx_recruitment_project_configs_job_id 
ON public.recruitment_project_configs(job_id);

CREATE INDEX IF NOT EXISTS idx_recruitment_search_queue_status 
ON public.recruitment_search_queue(status);

CREATE INDEX IF NOT EXISTS idx_recruitment_candidate_scores_project_config_id 
ON public.recruitment_candidate_scores(project_config_id);

-- ============================================
-- 8. LLM Prompt Templates (Admin-Editable)
-- ============================================
CREATE TABLE IF NOT EXISTS public.llm_prompt_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT UNIQUE NOT NULL, -- Unique identifier like 'recruitment.calibration.system'
    name TEXT NOT NULL,
    description TEXT,
    system_prompt TEXT NOT NULL,
    user_prompt_template TEXT, -- Optional template with {{variable}} placeholders
    model TEXT DEFAULT 'gpt-4o',
    temperature FLOAT DEFAULT 0.2,
    max_tokens INT,
    is_active BOOLEAN DEFAULT true,
    version INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Enable RLS
ALTER TABLE public.llm_prompt_templates ENABLE ROW LEVEL SECURITY;

-- Only admins can manage prompts
CREATE POLICY "Admins can manage prompt templates" 
ON public.llm_prompt_templates FOR ALL TO authenticated 
USING (public.is_admin_or_strategist(auth.uid()))
WITH CHECK (public.is_admin_or_strategist(auth.uid()));

-- Authenticated users can read active prompts (for Edge Functions)
CREATE POLICY "Authenticated users can read active prompts" 
ON public.llm_prompt_templates FOR SELECT TO authenticated 
USING (is_active = true);

-- Service role has full access
CREATE POLICY "Service role manages prompts" 
ON public.llm_prompt_templates FOR ALL TO service_role 
USING (true) WITH CHECK (true);

-- Create index on slug for fast lookups
CREATE INDEX IF NOT EXISTS idx_llm_prompt_templates_slug ON public.llm_prompt_templates(slug);

-- ============================================
-- 9. Seed Initial Prompts
-- ============================================
INSERT INTO public.llm_prompt_templates (slug, name, description, system_prompt, user_prompt_template, model, temperature) VALUES
(
    'recruitment.calibration.system',
    'Recruitment Calibration Agent',
    'Converts a Job Description into a structured Project Configuration for the recruitment engine.',
    E'You are the Calibration Engine for a high-precision recruitment OS.\nYour inputs are:\n1. Job Description (Text)\n2. Intake Notes (Text/JSON)\n\nYour output MUST be a valid JSON object adhering strictly to the provided Schema.\nNO markdown formatting. Just the raw JSON string.\n\nRULES:\n- "rejection_gates" must be binary and aggressive. If the JD says "Must speak German", the gate is "Language != German".\n- "scoring_weights" must reflect the JD''s emphasis. If "Python" is mentioned 10 times, technical_skills weight goes up.\n- "competitors" should be inferred from the context.\n\nSchema:\n{{schema}}',
    E'JOB TITLE: {{job_title}}\n\nJOB DESCRIPTION:\n{{job_description}}\n\nINTAKE NOTES:\n{{intake_notes}}',
    'gpt-4o',
    0.2
),
(
    'recruitment.analyzer.tier1',
    'Recruitment Analyzer - Tier 1 (Gatekeeper)',
    'Fast, cheap check to see if a candidate passes the rejection gates.',
    E'You are a Strict Gatekeeper.\nCandidate Profile:\n{{candidate}}\n\nRejection Gates:\n{{gates}}\n\nTask: Evaluate if the candidate FAILS any gate.\nOutput JSON: { "pass": boolean, "failed_gate_reason": "string or null" }',
    NULL,
    'gpt-4o-mini',
    0.0
),
(
    'recruitment.analyzer.tier2',
    'Recruitment Analyzer - Tier 2 (Expert)',
    'Deep analysis for candidates who passed Tier 1. Generates scores, evidence, risks, and interview questions.',
    E'You are an Expert Recruiter performing deep candidate analysis.\nCandidate Profile:\n{{candidate}}\n\nJob Configuration:\n{{config}}\n\nTask:\n1. Score the candidate (0-100) based on "scoring_weights".\n2. Extract "Evidence" bullets (direct quotes from their profile).\n3. Identify Risks (gaps, short tenures, missing skills).\n4. Generate 3 Interview Questions that probe the risks.\n\nOutput JSON:\n{\n  "total_score": number,\n  "evidence": { "technical": "...", "soft_skills": "...", "leadership": "..." },\n  "risks": ["..."],\n  "interview_questions": ["..."]\n}',
    NULL,
    'gpt-4o',
    0.0
)
ON CONFLICT (slug) DO NOTHING;
