
INSERT INTO skills_taxonomy (canonical_name, display_name, slug, category, tech_relevance, demand_trend, is_verified) VALUES
('javascript', 'JavaScript', 'javascript', 'technical', 0.95, 'rising', true),
('typescript', 'TypeScript', 'typescript', 'technical', 0.95, 'rising', true),
('python', 'Python', 'python', 'technical', 0.95, 'rising', true),
('java', 'Java', 'java', 'technical', 0.85, 'stable', true),
('csharp', 'C#', 'csharp', 'technical', 0.80, 'stable', true),
('go', 'Go', 'go', 'technical', 0.80, 'rising', true),
('rust', 'Rust', 'rust', 'technical', 0.70, 'rising', true),
('swift', 'Swift', 'swift', 'technical', 0.75, 'stable', true),
('kotlin', 'Kotlin', 'kotlin', 'technical', 0.75, 'rising', true),
('php', 'PHP', 'php', 'technical', 0.65, 'declining', true),
('ruby', 'Ruby', 'ruby', 'technical', 0.60, 'declining', true),
('cpp', 'C++', 'cpp', 'technical', 0.70, 'stable', true),
('sql', 'SQL', 'sql', 'technical', 0.90, 'stable', true),
('react', 'React', 'react', 'technical', 0.95, 'rising', true),
('vuejs', 'Vue.js', 'vuejs', 'technical', 0.75, 'stable', true),
('angular', 'Angular', 'angular', 'technical', 0.70, 'stable', true),
('nextjs', 'Next.js', 'nextjs', 'technical', 0.85, 'rising', true),
('tailwind_css', 'Tailwind CSS', 'tailwind-css', 'technical', 0.85, 'rising', true),
('html_css', 'HTML/CSS', 'html-css', 'technical', 0.90, 'stable', true),
('nodejs', 'Node.js', 'nodejs', 'technical', 0.90, 'rising', true),
('django', 'Django', 'django', 'technical', 0.70, 'stable', true),
('spring_boot', 'Spring Boot', 'spring-boot', 'technical', 0.75, 'stable', true),
('expressjs', 'Express.js', 'expressjs', 'technical', 0.80, 'stable', true),
('fastapi', 'FastAPI', 'fastapi', 'technical', 0.70, 'rising', true),
('graphql', 'GraphQL', 'graphql', 'technical', 0.75, 'rising', true),
('rest_api', 'REST API Design', 'rest-api-design', 'technical', 0.90, 'stable', true),
('microservices', 'Microservices', 'microservices', 'technical', 0.85, 'stable', true),
('serverless', 'Serverless', 'serverless', 'technical', 0.75, 'rising', true),
('machine_learning', 'Machine Learning', 'machine-learning', 'technical', 0.90, 'rising', true),
('deep_learning', 'Deep Learning', 'deep-learning', 'technical', 0.80, 'rising', true),
('nlp', 'Natural Language Processing', 'nlp', 'technical', 0.85, 'rising', true),
('data_engineering', 'Data Engineering', 'data-engineering', 'technical', 0.85, 'rising', true),
('data_analytics', 'Data Analytics', 'data-analytics', 'technical', 0.90, 'rising', true),
('llm_genai', 'LLM / Generative AI', 'llm-generative-ai', 'technical', 0.95, 'rising', true),
('prompt_engineering', 'Prompt Engineering', 'prompt-engineering', 'technical', 0.80, 'rising', true),
('react_native', 'React Native', 'react-native', 'technical', 0.80, 'stable', true),
('flutter', 'Flutter', 'flutter', 'technical', 0.75, 'rising', true),
('ios_dev', 'iOS Development', 'ios-development', 'technical', 0.80, 'stable', true),
('android_dev', 'Android Development', 'android-development', 'technical', 0.80, 'stable', true),
('cybersecurity', 'Cybersecurity', 'cybersecurity', 'technical', 0.80, 'rising', true),
('gdpr_compliance', 'GDPR Compliance', 'gdpr-compliance', 'technical', 0.60, 'rising', true),
('aws', 'AWS', 'aws', 'tool', 0.90, 'stable', true),
('gcp', 'Google Cloud (GCP)', 'gcp', 'tool', 0.80, 'rising', true),
('azure', 'Microsoft Azure', 'azure', 'tool', 0.85, 'rising', true),
('docker', 'Docker', 'docker', 'tool', 0.90, 'stable', true),
('kubernetes', 'Kubernetes', 'kubernetes', 'tool', 0.85, 'rising', true),
('terraform', 'Terraform', 'terraform', 'tool', 0.80, 'rising', true),
('postgresql', 'PostgreSQL', 'postgresql', 'tool', 0.90, 'rising', true),
('mongodb', 'MongoDB', 'mongodb', 'tool', 0.75, 'stable', true),
('redis', 'Redis', 'redis', 'tool', 0.80, 'stable', true),
('figma', 'Figma', 'figma', 'tool', 0.40, 'rising', true),
('salesforce', 'Salesforce', 'salesforce', 'tool', 0.30, 'stable', true),
('hubspot', 'HubSpot', 'hubspot', 'tool', 0.30, 'stable', true),
('jira', 'JIRA', 'jira', 'tool', 0.55, 'stable', true),
('linear_tool', 'Linear', 'linear-tool', 'tool', 0.45, 'rising', true),
('google_analytics', 'Google Analytics', 'google-analytics', 'tool', 0.30, 'stable', true),
('product_management', 'Product Management', 'product-management', 'soft', 0.60, 'rising', true),
('product_strategy', 'Product Strategy', 'product-strategy', 'soft', 0.55, 'rising', true),
('user_research', 'User Research', 'user-research', 'soft', 0.50, 'rising', true),
('ab_testing', 'A/B Testing', 'ab-testing', 'soft', 0.55, 'stable', true),
('agile_scrum', 'Agile / Scrum', 'agile-scrum', 'soft', 0.55, 'stable', true),
('ui_design', 'UI Design', 'ui-design', 'soft', 0.50, 'stable', true),
('ux_design', 'UX Design', 'ux-design', 'soft', 0.50, 'rising', true),
('design_systems', 'Design Systems', 'design-systems', 'soft', 0.55, 'rising', true),
('brand_design', 'Brand Design', 'brand-design', 'soft', 0.35, 'stable', true),
('digital_marketing', 'Digital Marketing', 'digital-marketing', 'soft', 0.30, 'stable', true),
('content_marketing', 'Content Marketing', 'content-marketing', 'soft', 0.25, 'stable', true),
('seo_skill', 'SEO', 'seo-skill', 'soft', 0.30, 'stable', true),
('copywriting', 'Copywriting', 'copywriting', 'soft', 0.25, 'stable', true),
('brand_strategy', 'Brand Strategy', 'brand-strategy', 'soft', 0.30, 'stable', true),
('b2b_sales', 'B2B Sales', 'b2b-sales', 'soft', 0.20, 'stable', true),
('business_dev', 'Business Development', 'business-development', 'soft', 0.25, 'stable', true),
('customer_success', 'Customer Success', 'customer-success', 'soft', 0.30, 'rising', true),
('negotiation', 'Negotiation', 'negotiation', 'soft', 0.20, 'stable', true),
('project_management', 'Project Management', 'project-management', 'soft', 0.30, 'stable', true),
('change_management', 'Change Management', 'change-management', 'soft', 0.25, 'stable', true),
('financial_modeling', 'Financial Modeling', 'financial-modeling', 'soft', 0.20, 'stable', true),
('financial_analysis', 'Financial Analysis', 'financial-analysis', 'soft', 0.20, 'stable', true),
('team_leadership', 'Team Leadership', 'team-leadership', 'leadership', 0.40, 'stable', true),
('strategic_planning', 'Strategic Planning', 'strategic-planning', 'leadership', 0.35, 'stable', true),
('stakeholder_mgmt', 'Stakeholder Management', 'stakeholder-management', 'leadership', 0.35, 'stable', true),
('cross_functional', 'Cross-functional Collaboration', 'cross-functional', 'leadership', 0.35, 'stable', true),
('mentoring', 'Mentoring & Coaching', 'mentoring-coaching', 'leadership', 0.30, 'rising', true),
('remote_mgmt', 'Remote Team Management', 'remote-team-management', 'leadership', 0.35, 'rising', true),
('fashion_buying', 'Fashion Buying', 'fashion-buying', 'industry', 0.10, 'stable', true),
('trend_forecasting', 'Trend Forecasting', 'trend-forecasting', 'industry', 0.10, 'stable', true),
('visual_merchandising', 'Visual Merchandising', 'visual-merchandising', 'industry', 0.10, 'stable', true),
('beauty_product_dev', 'Beauty Product Development', 'beauty-product-dev', 'industry', 0.10, 'stable', true),
('luxury_brand_mgmt', 'Luxury Brand Management', 'luxury-brand-mgmt', 'industry', 0.15, 'stable', true),
('ecommerce_ops', 'E-commerce Operations', 'ecommerce-ops', 'industry', 0.50, 'rising', true),
('sustainability_esg', 'Sustainability / ESG', 'sustainability-esg', 'industry', 0.30, 'rising', true),
('dtc_strategy', 'DTC Strategy', 'dtc-strategy', 'industry', 0.40, 'rising', true),
('omnichannel', 'Omnichannel Strategy', 'omnichannel-strategy', 'industry', 0.40, 'rising', true),
('customer_experience', 'Customer Experience', 'customer-experience', 'industry', 0.40, 'rising', true),
('marketplace_mgmt', 'Marketplace Management', 'marketplace-mgmt', 'industry', 0.40, 'rising', true),
('talent_acquisition', 'Talent Acquisition', 'talent-acquisition', 'industry', 0.25, 'stable', true),
('employer_branding', 'Employer Branding', 'employer-branding', 'industry', 0.25, 'rising', true),
('people_operations', 'People Operations', 'people-ops', 'industry', 0.25, 'rising', true),
('revenue_operations', 'Revenue Operations', 'revenue-ops', 'industry', 0.35, 'rising', true)
ON CONFLICT (slug) DO NOTHING;

UPDATE skills_taxonomy SET beauty_relevance = 0.95, luxury_fashion_relevance = 0.95 WHERE slug IN ('fashion-buying', 'visual-merchandising', 'beauty-product-dev', 'luxury-brand-mgmt', 'trend-forecasting');
UPDATE skills_taxonomy SET beauty_relevance = 0.80, luxury_fashion_relevance = 0.80 WHERE slug IN ('ecommerce-ops', 'dtc-strategy', 'omnichannel-strategy', 'brand-design', 'brand-strategy');
UPDATE skills_taxonomy SET beauty_relevance = 0.60, luxury_fashion_relevance = 0.50 WHERE slug IN ('sustainability-esg', 'customer-experience', 'digital-marketing', 'content-marketing');
