-- Migration to archive unused tables
-- Auto-generated by scripts/archive_migration_generator.py

CREATE SCHEMA IF NOT EXISTS archive;

ALTER TABLE IF EXISTS public.test_partner_table SET SCHEMA archive;