// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/** Prefer VITE_SUPABASE_URL; VITE_SITE_URL is a legacy alias some deployments use for the same Supabase project URL. */
const supabaseUrl =
  (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim() ||
  (import.meta.env.VITE_SITE_URL as string | undefined)?.trim() ||
  '';
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseKey) {
  console.warn(
    'Supabase URL or Key is missing. The app is running in a mode where env vars are not set (e.g. preview). ' +
    'Set VITE_SUPABASE_URL (or legacy VITE_SITE_URL) and VITE_SUPABASE_ANON_KEY in .env or your build environment.'
  );
}

// Use a dummy URL if missing to prevent createClient from crashing immediately
export const supabase = createClient<Database>(
  supabaseUrl || 'https://placeholder-project.supabase.co',
  supabaseKey || 'placeholder-key',
  {
    auth: {
      storageKey: 'supabase-auth-token',
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      headers: {
        'x-application-name': 'thequantumclub',
      },
    },
  }
);